"use client";
import { useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { EnterpriseHeader, EnterpriseStyles, Panel, Stat, Badge } from "@/components/admin/EnterpriseUI";
import { supabase } from "@/lib/supabase-client";
import { ExternalLink, PackageSearch, Plus, Ship, UserPlus, X } from "lucide-react";

type Customer={id?:string;company_name:string;contact_name:string;email:string;phone:string;country:string;billing_address:string;shipping_address:string;registration_number:string;preferred_currency:string;incoterm:string;payment_terms:string;assigned_salesperson:string;status:string;notes:string};
type Shipment={id?:string;customer_id:string;reference_number:string;shipment_type:string;carrier_type:string;carrier_name:string;tracking_number:string;bl_number:string;container_number:string;vessel_name:string;voyage_number:string;origin:string;destination:string;etd:string;eta:string;current_status:string;tracking_url:string;notes:string};
const blankCustomer:Customer={company_name:"",contact_name:"",email:"",phone:"",country:"",billing_address:"",shipping_address:"",registration_number:"",preferred_currency:"USD",incoterm:"FOB",payment_terms:"",assigned_salesperson:"",status:"active",notes:""};
const blankShipment:Shipment={customer_id:"",reference_number:"",shipment_type:"container",carrier_type:"custom",carrier_name:"",tracking_number:"",bl_number:"",container_number:"",vessel_name:"",voyage_number:"",origin:"",destination:"",etd:"",eta:"",current_status:"booked",tracking_url:"",notes:""};
export default function Page(){
 const[customers,setClients]=useState<any[]>([]),[shipments,setShipments]=useState<any[]>([]),[customerOpen,setCustomerOpen]=useState(false),[shipmentOpen,setShipmentOpen]=useState(false),[customer,setCustomer]=useState<Customer>(blankCustomer),[shipment,setShipment]=useState<Shipment>(blankShipment),[saving,setSaving]=useState(false),[search,setSearch]=useState("");
 async function load(){const[a,b]=await Promise.all([supabase.from("customer_accounts").select("*").order("created_at",{ascending:false}),supabase.from("customer_shipments").select("*,customer_accounts(company_name)").order("created_at",{ascending:false})]);setClients(a.data||[]);setShipments(b.data||[])}
 useEffect(()=>{void load()},[]);
 async function saveCustomer(){if(!customer.company_name.trim()||!customer.email.trim())return alert("Company name and email are required.");setSaving(true);const{error}=await supabase.from("customer_accounts").insert(customer);setSaving(false);if(error)return alert(error.message);setCustomer(blankCustomer);setCustomerOpen(false);await load()}
 async function saveShipment(){if(!shipment.customer_id||!shipment.reference_number.trim())return alert("Client and reference number are required.");setSaving(true);const payload={...shipment,etd:shipment.etd?new Date(shipment.etd).toISOString():null,eta:shipment.eta?new Date(shipment.eta).toISOString():null};const{error}=await supabase.from("customer_shipments").insert(payload);setSaving(false);if(error)return alert(error.message);setShipment(blankShipment);setShipmentOpen(false);await load()}
 const filtered=useMemo(()=>shipments.filter(x=>`${x.reference_number} ${x.customer_accounts?.company_name} ${x.tracking_number} ${x.container_number} ${x.bl_number}`.toLowerCase().includes(search.toLowerCase())),[shipments,search]);
 return <AdminShell><div className="ent-page customer-page"><EnterpriseHeader eyebrow="B2B self-service" title="Client Portal & Shipment Tracking" copy="Create client accounts, keep commercial preferences, and register container, vessel, air-cargo or courier movements." actions={<><button className="ent-btn soft" onClick={()=>setCustomerOpen(true)}><UserPlus/>Add client</button><button className="ent-btn primary" onClick={()=>setShipmentOpen(true)}><Ship/>Add shipment</button></>}/>
 <div className="ent-grid"><Stat label="Clients" value={customers.length}/><Stat label="Active shipments" value={shipments.filter(x=>!["delivered","completed"].includes(x.current_status)).length}/><Stat label="Containers" value={shipments.filter(x=>x.shipment_type==="container").length}/><Stat label="Courier parcels" value={shipments.filter(x=>x.shipment_type==="courier").length}/></div>
 <Panel title="Shipment registry" copy="Manual tracking works immediately; provider APIs can be connected later"><div className="shipment-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search client, reference, BL, container or tracking number"/></div><div className="table-scroll"><table className="ent-table"><thead><tr><th>Reference</th><th>Client</th><th>Mode / Carrier</th><th>Tracking details</th><th>Route</th><th>ETA</th><th>Status</th><th>Open</th></tr></thead><tbody>{filtered.length?filtered.map(x=><tr key={x.id}><td><strong>{x.reference_number}</strong></td><td>{x.customer_accounts?.company_name||"—"}</td><td>{x.shipment_type}<br/><small>{x.carrier_name||x.carrier_type}</small></td><td>{x.container_number||x.tracking_number||x.bl_number||"—"}<br/><small>{x.vessel_name||""}</small></td><td>{x.origin||"—"} → {x.destination||"—"}</td><td>{x.eta?new Date(x.eta).toLocaleDateString():"—"}</td><td><Badge tone={x.current_status==="delivered"?"good":"warn"}>{x.current_status}</Badge></td><td>{x.tracking_url?<a href={x.tracking_url} target="_blank" rel="noreferrer"><ExternalLink/></a>:"—"}</td></tr>):<tr><td colSpan={8}>No shipments yet.</td></tr>}</tbody></table></div></Panel>
 <div className="ent-two"><Panel title="Client accounts"><div className="ent-list">{customers.length?customers.map(x=><article key={x.id}><div><h3>{x.company_name}</h3><p>{x.contact_name||"No contact"} · {x.email} · {x.country||"Country not set"}</p></div><Badge tone={x.status==="active"?"good":"neutral"}>{x.status}</Badge></article>):<div className="ent-empty">No client accounts yet.</div>}</div></Panel><Panel title="Supported shipment modes"><div className="ent-list">{[["Ocean container","Container no., BL, vessel, voyage, ETD and ETA"],["Courier parcel","DHL, FedEx, UPS, Aramex, TCS, Leopards or custom"],["Air cargo","AWB, airline, flight and airport milestones"],["Custom logistics","Any provider with a manual tracking URL"]].map(([a,b])=><article key={a}><div><h3>{a}</h3><p>{b}</p></div><PackageSearch/></article>)}</div></Panel></div>
 {customerOpen&&<Modal title="Add Client" close={()=>setCustomerOpen(false)}><div className="form-grid">{[["Company name","company_name"],["Contact person","contact_name"],["Email","email"],["Phone / WhatsApp","phone"],["Country","country"],["Registration / Tax no.","registration_number"],["Assigned salesperson","assigned_salesperson"]].map(([label,key])=><Field key={key} label={label}><input value={(customer as any)[key]} onChange={e=>setCustomer({...customer,[key]:e.target.value})}/></Field>)}<Field label="Currency"><select value={customer.preferred_currency} onChange={e=>setCustomer({...customer,preferred_currency:e.target.value})}>{["USD","EUR","GBP","AED","CAD","PKR"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Incoterm"><select value={customer.incoterm} onChange={e=>setCustomer({...customer,incoterm:e.target.value})}>{["EXW","FOB","CFR","CIF","DAP","DDP"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select value={customer.status} onChange={e=>setCustomer({...customer,status:e.target.value})}><option>active</option><option>inactive</option><option>prospect</option></select></Field><Field label="Billing address"><textarea value={customer.billing_address} onChange={e=>setCustomer({...customer,billing_address:e.target.value})}/></Field><Field label="Shipping address"><textarea value={customer.shipping_address} onChange={e=>setCustomer({...customer,shipping_address:e.target.value})}/></Field><Field label="Payment terms"><textarea value={customer.payment_terms} onChange={e=>setCustomer({...customer,payment_terms:e.target.value})}/></Field><Field label="Notes"><textarea value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})}/></Field></div><Actions close={()=>setCustomerOpen(false)} save={saveCustomer} saving={saving}/></Modal>}
 {shipmentOpen&&<Modal title="Add Shipment" close={()=>setShipmentOpen(false)}><div className="form-grid"><Field label="Customer"><select value={shipment.customer_id} onChange={e=>setShipment({...shipment,customer_id:e.target.value})}><option value="">Select client</option>{customers.map(x=><option key={x.id} value={x.id}>{x.company_name}</option>)}</select></Field>{[["Reference number","reference_number"],["Carrier name","carrier_name"],["Tracking number / AWB","tracking_number"],["BL number","bl_number"],["Container number","container_number"],["Vessel name","vessel_name"],["Voyage number","voyage_number"],["Origin","origin"],["Destination","destination"],["Tracking URL","tracking_url"]].map(([label,key])=><Field key={key} label={label}><input value={(shipment as any)[key]} onChange={e=>setShipment({...shipment,[key]:e.target.value})}/></Field>)}<Field label="Mode"><select value={shipment.shipment_type} onChange={e=>setShipment({...shipment,shipment_type:e.target.value})}><option value="container">Ocean container</option><option value="courier">Courier</option><option value="air_cargo">Air cargo</option><option value="custom">Custom</option></select></Field><Field label="Carrier"><select value={shipment.carrier_type} onChange={e=>setShipment({...shipment,carrier_type:e.target.value})}>{["custom","dhl","fedex","ups","aramex","tcs","leopards","maersk","msc","cma_cgm"].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></Field><Field label="Status"><select value={shipment.current_status} onChange={e=>setShipment({...shipment,current_status:e.target.value})}>{["booked","processing","shipped","in_transit","customs","out_for_delivery","delivered","delayed"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="ETD"><input type="datetime-local" value={shipment.etd} onChange={e=>setShipment({...shipment,etd:e.target.value})}/></Field><Field label="ETA"><input type="datetime-local" value={shipment.eta} onChange={e=>setShipment({...shipment,eta:e.target.value})}/></Field><Field label="Notes"><textarea value={shipment.notes} onChange={e=>setShipment({...shipment,notes:e.target.value})}/></Field></div><Actions close={()=>setShipmentOpen(false)} save={saveShipment} saving={saving}/></Modal>}
 <EnterpriseStyles/><style jsx>{`.shipment-search{margin-bottom:14px}.shipment-search input{width:100%;border:1px solid var(--line);border-radius:12px;padding:12px;background:var(--surface-2)}.table-scroll{overflow:auto}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{position:fixed;inset:0;z-index:2500;background:rgba(8,12,25,.72);display:grid;place-items:center;padding:18px}.modal-card{width:min(900px,100%);max-height:92vh;overflow:auto;background:var(--surface);border:1px solid var(--line);border-radius:24px;padding:24px}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.modal-head h2{font-size:26px}.modal-head button{width:38px;height:38px;border-radius:10px;border:1px solid var(--line)}.field{display:flex;flex-direction:column;gap:7px;font-size:11px;font-weight:800}.field input,.field select,.field textarea{border:1px solid var(--line);background:var(--surface-2);border-radius:11px;padding:11px}.field textarea{min-height:92px}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.modal-actions button{padding:11px 16px;border-radius:11px;font-weight:800}.modal-actions .save{color:white}@media(max-width:700px){.form-grid{grid-template-columns:1fr}}`}</style></div></AdminShell>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card"><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Actions({close,save,saving}:{close:()=>void;save:()=>void;saving:boolean}){return <div className="modal-actions"><button onClick={close}>Cancel</button><button className="cms-gradient-button save" onClick={save} disabled={saving}>{saving?"Saving…":"Save"}</button></div>}
