export type CmsImageSlotSeed = {
  page_slug: string;
  section_slug: string;
  slot_key: string;
  title: string;
  current_url: string;
  default_url: string;
  alt_text: string;
  recommended_width: number;
  recommended_height: number;
  display_order: number;
  is_active: boolean;
};

export type CmsTextSeed = {
  page_slug: string;
  section_slug: string;
  field_key: string;
  field_label: string;
  field_type: "text" | "textarea";
  default_value: string;
  display_order: number;
};

export const cmsPageLabels: Record<string, string> = {
  global: "Branding / Footer",
  home: "Homepage",
  about: "About Page",
  products: "Products Page",
  "private-label": "Private Label",
  certifications: "Certifications",
  contact: "Contact Page",
  blog: "Blog Page",
  faqs: "FAQ Page",
  "privacy-policy": "Privacy Policy",
  "terms-and-conditions": "Terms & Conditions",
};

export const cmsImageRegistry: CmsImageSlotSeed[] = [
  ["global","branding","logo","Shared Logo — Legacy Fallback","/logo.png","The Salt Origin logo",400,220],
  ["global","branding","header_logo","Header / Navbar Logo","/logo.png","The Salt Origin header logo",500,220],
  ["global","branding","footer_logo","Footer Logo","/logo.png","The Salt Origin footer logo",500,220],
  ["home","hero","products","Hero Section — Product Collection","/hero-products.png","Himalayan Pink Salt product collection",900,900],
  ["home","hero","mountains","Hero Section — Mountain Background","/mountains-bg.png","Himalayan mountain background",1920,900],
  ["home","private_label","custom_labels","Private Label — Custom Bottles","/custom-labels.png","Custom bottles",600,400],
  ["home","private_label","custom_packaging","Private Label — Custom Packaging","/custom-packaging.png","Custom packaging",600,400],
  ["home","private_label","pouch","Private Label Program — Pouch","/pouches.png","Private label Himalayan pink salt pouch",700,900],
  ["home","private_label","jar","Private Label Program — Jar","/pet-jars.png","Private label Himalayan pink salt jar",700,900],
  ["home","private_label","grinder","Private Label Program — Grinder","/grinder-bottles.png","Private label Himalayan pink salt grinder",700,900],
  ["home","private_label","bulk","Private Label Program — Bulk Bag","/white-sack.png","Private label Himalayan pink salt bulk bag",700,900],
  ["home","private_program","pouch","Homepage Private Label — Pouch","/pouches.png","Private label pouch packaging",700,900],
  ["home","private_program","jar","Homepage Private Label — Jar","/pet-jars.png","Private label jar packaging",700,900],
  ["home","private_program","grinder","Homepage Private Label — Grinder","/grinder-bottles.png","Private label grinder packaging",700,900],
  ["home","private_program","bulk_packaging","Homepage Private Label — Bulk Packaging","/white-sack.png","Bulk Himalayan pink salt packaging",700,900],
  ["home","private_program","bulk_bags","Homepage Private Label — Bulk Bags","/white-sack.png","Bulk salt bags",700,900],
  ["home","product_families","edible","Product Families — Edible Salt","/hero-banner.png","Edible Himalayan pink salt",900,560],
  ["home","product_families","grinders","Product Families — Grinders & Shakers","/grinder-bottles.png","Himalayan pink salt grinders and shakers",900,560],
  ["home","product_families","bulk","Product Families — Bulk Supply","/white-sack.png","Bulk Himalayan pink salt supply",900,560],
  ["home","product_families","animal","Product Families — Animal Lick Salt","/product-2.png","Animal lick Himalayan salt",900,560],
  ["home","product_families","lamps","Product Families — Salt Lamps & Décor","/product-5.png","Himalayan salt lamps and decor",900,560],
  ["home","product_families","tiles","Product Families — Salt Tiles & Bricks","/product-4.png","Himalayan salt tiles and bricks",900,560],
  ["home","products","pet_bottles","Product Range — PET Bottles","/pet-bottles.png","PET salt bottles",600,600],
  ["home","products","pet_jars","Product Range — PET Jars","/pet-jars.png","PET salt jars",600,600],
  ["home","products","grinders","Product Range — Grinder Collection","/grinder-bottles.png","Salt grinder bottles",600,600],
  ["home","products","pouches","Product Range — Stand-Up Pouch","/standup-pouch.png","Stand-up salt pouch",600,600],
  ["home","collections","retail","Signature Collection — Retail Packaging","/product-2.png","Retail packaging collection",900,700],
  ["home","collections","bulk","Signature Collection — Bulk Supply","/white-sack.png","Bulk salt supply",900,700],
  ["home","collections","private_label","Signature Collection — Private Label","/custom-labels.png","Private label salt packaging",900,700],
  ["home","collections","animal_lick","Signature Collection — Animal Lick Salt","/hero-banner.png","Animal lick salt collection",900,700],
  ["home","collections","foodservice","Signature Collection — Foodservice","/product-5.png","Foodservice pink salt format",900,700],
  ["home","collections","gourmet","Signature Collection — Gourmet & Lifestyle","/product-4.png","Gourmet pink salt collection",900,700],
  ["home","quality","iso","Quality — ISO Certificate","/cert-iso.png","ISO certificate",400,400],
  ["home","quality","haccp","Quality — HACCP Certificate","/cert-haccp.png","HACCP certificate",400,400],
  ["home","quality","gmp","Quality — GMP Certificate","/cert-gmp.png","GMP certificate",400,400],
  ["home","quality","halal","Quality — Halal Certificate","/cert-halal.png","Halal certificate",400,400],
  ["home","quality","fda","Quality — FDA Certificate","/cert-fda.png","FDA registration",400,400],
  ["home","quality","food","Quality — Food Certificate","/cert-food.png","Food certificate",400,400],
  ["home","export","map","Export Markets — World Map","/world-map.png","World export map",1400,700],
  ["about","hero","banner","About Page — Hero Banner","/hero-banner.png","About The Salt Origin",1600,900],
  ["about","hero","mountains","About Page — Mountain Background","/mountains-bg.png","Himalayan mountain illustration",1920,900],
  ["about","hero","reference","About Page — Hero Mountain Artwork","/about-hero-mountains-reference.png","Himalayan mountain artwork",1600,700],
  ["about","story","collage","About Page — Product Collage","/product-collage.png","Salt product collage",1200,800],
  ["about","story","visual","About Page — Story Mountain Visual","/about-story-reference.png","Himalayan mountain origin story",900,900],
  ["about","founder","portrait","About Page — Founder Portrait","/founder-portrait-reference.png","Founder portrait",900,900],
  ["products","hero","banner","Products — Hero Salt Collection","/hero-banner.png","Himalayan pink salt product collection",1600,900],
  ["products","bulk_packaging","bag","Products — Bulk Packaging Bag","/white-sack.png","Himalayan pink salt bulk packaging bag",800,800],
  ["products","retail","shaker","Products — Salt Shaker","/shaker-bottles.png","Salt shaker collection",800,800],
  ["products","retail","jar","Products — Salt Jar","/pet-jars.png","Salt jar collection",800,800],
  ["products","retail","pouch","Products — Stand-Up Pouch","/pouches.png","Stand-up pouch collection",800,800],
  ["products","grinder","plastic","Products — Plastic Grinder","/grinder-bottles.png","Plastic grinder bottles",800,800],
  ["products","grinder","ceramic","Products — Ceramic Grinder","/ceramic-grinders.png","Ceramic grinder bottles",800,800],
  ["products","bulk","bag","Products — Bulk Salt Bag","/white-sack.png","Bulk salt bag",800,800],
  ["private-label","hero","salt_accent","Private Label — Hero Banner","/hero-banner.png","Himalayan pink salt private label banner",1600,900],
  ["private-label","studio","packaging_visual","Private Label — Packaging Studio Visual","/custom-packaging.png","Private label packaging formats",1100,900],
  ["certifications","cards","iso","Certifications Page — ISO","/cert-iso.png","ISO certification",500,500],
  ["certifications","cards","haccp","Certifications Page — HACCP","/cert-haccp.png","HACCP certification",500,500],
  ["certifications","cards","gmp","Certifications Page — GMP","/cert-gmp.png","GMP certification",500,500],
  ["certifications","cards","halal","Certifications Page — Halal","/cert-halal.png","Halal certification",500,500],
  ["certifications","cards","fda","Certifications Page — FDA","/cert-fda.png","FDA registration",500,500],
  ["certifications","cards","food","Certifications Page — Food Safety","/cert-food.png","Food safety certification",500,500],
  ["contact","hero","banner","Contact Page — Hero Image","/hero-banner.png","Contact The Salt Origin",1600,900],
  ["blog","listing","default","Blog — Default Featured Image","/og-image.jpg","Himalayan Pink Salt blog",1200,630],
].map((row, index) => {
  const [page_slug, section_slug, slot_key, title, url, alt_text, recommended_width, recommended_height] = row as [string,string,string,string,string,string,number,number];
  return { page_slug, section_slug, slot_key, title, current_url: url, default_url: url, alt_text, recommended_width, recommended_height, display_order: index + 1, is_active: true };
});

export const cmsTextRegistry: CmsTextSeed[] = [
  ["global","navbar","home","Home Menu Label","text","Home"],
  ["global","navbar","about","About Menu Label","text","About Us"],
  ["global","navbar","products","Products Menu Label","text","Products"],
  ["global","navbar","private_label","Private Label Menu Label","text","Private Label"],
  ["global","navbar","certifications","Certifications Menu Label","text","Certifications"],
  ["global","navbar","blog","Blog Menu Label","text","Blog"],
  ["global","navbar","faq","FAQ Menu Label","text","FAQ"],
  ["global","navbar","contact","Contact Menu Label","text","Contact"],
  ["global","navbar","quote","Quote Button Label","text","Get Quote"],
  ["global","branding","logo_alt","Header & Footer Logo Alt Text","text","The Salt Origin"],
  ["global","branding","header_brand_name","Header Brand Name","text","The Salt Origin"],
  ["global","branding","header_brand_subtitle","Header Brand Subtitle","text","PINK SALT · PAKISTAN"],
  ["global","footer","brand_tagline","Footer Brand Tagline","text","Himalayan Pink Salt Exporter"],
  ["global","footer","social_title","Footer Social Media Heading","text","Connect with us"],
  ["global","footer","quick_links_title","Footer Quick Links Heading Legacy","text","Quick Links"],
  ["global","footer","explore_title","Footer Explore Heading","text","EXPLORE"],
  ["global","footer","company_title","Footer Company Heading","text","COMPANY"],
  ["global","footer","b2b_title","Footer B2B Heading","text","B2B DESK"],
  ["global","footer","contact_title","Footer Contact Heading","text","Contact Info"],
  ["global","footer","policies_title","Footer Policies Heading","text","Policies"],
  ["global","footer","quote_button","Footer Quote Button Label","text","Get Quote"],
  ["global","footer","copyright","Footer Copyright Line","textarea","© {year} {site}. All Rights Reserved."],
  ["global","footer","privacy_label","Footer Privacy Link Label","text","Privacy Policy"],
  ["global","footer","terms_label","Footer Terms Link Label","text","Terms & Conditions"],
  ["global","footer","bottom_note","Footer Bottom Note","textarea","Premium Himalayan Pink Salt\nSupplier & Private Label Partner"],
  ["global","footer","website_credit","Website Designed / Developed By Line","textarea",""],
  ["home","hero","badge","Hero Badge","text","PREMIUM QUALITY"],
  ["home","hero","title","Hero Main Heading","textarea","Himalayan Pink Salt,"],
  ["home","hero","title_accent","Hero Heading Accent / Italic Segment","text","refined for global commerce."],
  ["home","hero","description","Hero Description","textarea","We provide premium quality Himalayan Pink Salt in multiple forms and packaging, trusted by importers, distributors and brands worldwide."],
  ["home","hero","primary_button","Explore Products Button","text","Explore Products"],
  ["home","hero","secondary_button","Request Quote Button","text","Request Quote"],
  ["home","private_label","title","Private Label Heading Legacy","text","PRIVATE LABEL SOLUTIONS"],
  ["home","private_label","description","Private Label Description Legacy","textarea","We help brands create their identity with fully customized bottles and packaging."],
  ["home","private_label","eyebrow","Private Label Program Eyebrow","text","PRIVATE LABEL PROGRAM"],
  ["home","private_label","title_main","Private Label Heading Main","text","Private Label."],
  ["home","private_label","title_accent","Private Label Heading Accent","text","Built Around Your Brand."],
  ["home","private_label","description_v2","Private Label Program Description","textarea","From concept to shelf, we create fully customized Himalayan pink salt packaging that reflects your identity and connects with your customers. You imagine it, we make it real."],
  ["home","private_label","feature_one_title","Feature 1 Heading","text","MULTIPLE FORMATS"],
  ["home","private_label","feature_one_text","Feature 1 Text","textarea","Pouch, Jar, Grinder or Bulk — we’ve got you covered."],
  ["home","private_label","feature_two_title","Feature 2 Heading","text","FULLY CUSTOMIZABLE"],
  ["home","private_label","feature_two_text","Feature 2 Text","textarea","Your logo, colors, labels & design — 100% yours."],
  ["home","private_label","feature_three_title","Feature 3 Heading","text","PREMIUM QUALITY"],
  ["home","private_label","feature_three_text","Feature 3 Text","textarea","100% natural Himalayan pink salt, processed with care."],
  ["home","private_label","feature_four_title","Feature 4 Heading","text","GLOBAL SUPPLY"],
  ["home","private_label","feature_four_text","Feature 4 Text","textarea","Reliable export, on-time delivery, worldwide."],
  ["home","private_label","button","Private Label Explore Button","text","Explore Solutions"],
  ["home","private_label","quote_button","Private Label Quote Button","text","Request Private Label Quote"],
  ["home","private_label","collection_title","Packaging Collection Heading","text","TAILORED PACKAGING COLLECTION"],
  ["home","private_label","pouch_title","Pouch Heading","text","POUCH"],
  ["home","private_label","pouch_text","Pouch Description","text","Stand-up & Ziplock"],
  ["home","private_label","jar_title","Jar Heading","text","JAR"],
  ["home","private_label","jar_text","Jar Description","text","Plastic / Glass"],
  ["home","private_label","grinder_title","Grinder Heading","text","GRINDER"],
  ["home","private_label","grinder_text","Grinder Description","text","Plastic / Glass"],
  ["home","private_label","bulk_title","Bulk Heading","text","BULK"],
  ["home","private_label","bulk_text","Bulk Description","text","5kg to 25kg+"],
  ["home","private_label","support_title","Dedicated Support Heading","text","DEDICATED SUPPORT"],
  ["home","private_label","support_text","Dedicated Support Text","textarea","Our team is with you at every step — from design approval to final delivery."],
  ["home","private_label","compliance_title","Quality & Compliance Heading","text","QUALITY & COMPLIANCE"],
  ["home","private_label","compliance_text","Quality & Compliance Text","textarea","Manufactured in certified facilities with strict quality control and international food safety standards."],
  ["home","private_label","bullet_bottles","Private Label Bullet — Bottles","text","Custom Bottles"],
  ["home","private_label","bullet_packaging","Private Label Bullet — Packaging","text","Custom Packaging"],
  ["home","private_label","bottles_title","Custom Bottles Card Heading","text","Custom Bottles"],
  ["home","private_label","bottles_text","Custom Bottles Card Description","textarea","Choose your bottle style, size and design to match your brand identity."],
  ["home","private_label","packaging_title","Custom Packaging Card Heading","text","Custom Packaging"],
  ["home","private_label","packaging_text","Custom Packaging Card Description","textarea","Custom printed pouches and jars with your logo, colors and design."],
  ["home","products","title","Product Range Heading","text","OUR PRODUCT RANGE"],
  ["home","products","description","Product Range Description","textarea","Premium Himalayan Pink Salt products for retail, private label and global distribution."],
  ["home","products","pet_bottles_title","PET Bottles Card Heading","text","PET Bottles"],
  ["home","products","pet_bottles_text","PET Bottles Card Description","textarea","Multiple sizes for everyday use and retail."],
  ["home","products","pet_jars_title","PET Jars Card Heading","text","PET Jars"],
  ["home","products","pet_jars_text","PET Jars Card Description","textarea","Fine grain salt in convenient PET jars."],
  ["home","products","grinders_title","Grinder Card Heading","text","Grinder Collection"],
  ["home","products","grinders_text","Grinder Card Description","textarea","Plastic and ceramic grinder bottles."],
  ["home","products","pouches_title","Pouches Card Heading","text","Stand-Up Pouches"],
  ["home","products","pouches_text","Pouches Card Description","textarea","Premium zip-lock pouches for maximum freshness."],
  ["home","products","view_button","Product Card Button","text","View Products"],
  ["home","private_program","eyebrow","Private Label Program Eyebrow","text","PRIVATE LABEL PROGRAM"],
  ["home","private_program","title_black","Private Label Program Heading — Black","text","We Build It."],
  ["home","private_program","title_accent","Private Label Program Heading — Accent","text","You Brand It. We Deliver."],
  ["home","private_program","description","Private Label Program Description","textarea","From concept to customer, we create premium Himalayan pink salt products in packaging that represents your brand and values."],
  ["home","private_program","benefit_1_title","Benefit 1 Heading","text","PURE & NATURAL"],
  ["home","private_program","benefit_1_text","Benefit 1 Text","textarea","100% pure Himalayan pink salt. No additives, no compromises."],
  ["home","private_program","benefit_2_title","Benefit 2 Heading","text","CERTIFIED QUALITY"],
  ["home","private_program","benefit_2_text","Benefit 2 Text","textarea","International quality standards with strict food safety control."],
  ["home","private_program","benefit_3_title","Benefit 3 Heading","text","GLOBAL REACH"],
  ["home","private_program","benefit_3_text","Benefit 3 Text","textarea","Reliable production and on-time delivery to international markets."],
  ["home","private_program","benefit_4_title","Benefit 4 Heading","text","YOUR BRAND IDENTITY"],
  ["home","private_program","benefit_4_text","Benefit 4 Text","textarea","Your logo, your label, your packaging — built around your brand."],
  ["home","private_program","solutions_eyebrow","Packaging Solutions Eyebrow","text","WHAT WE OFFER"],
  ["home","private_program","solutions_title","Packaging Solutions Heading","text","Packaging Solutions"],
  ["home","private_program","solutions_accent","Packaging Solutions Accent","text","Designed Around Your Brand"],
  ["home","private_program","pouch_title","Pouch Heading","text","POUCH"],
  ["home","private_program","pouch_text","Pouch Text","text","Stand-up & ziplock pouches"],
  ["home","private_program","pouch_note","Pouch Note","text","Multiple sizes available"],
  ["home","private_program","jar_title","Jar Heading","text","JAR"],
  ["home","private_program","jar_text","Jar Text","text","Plastic or glass jars"],
  ["home","private_program","jar_note","Jar Note","text","Custom sizes & labels"],
  ["home","private_program","grinder_title","Grinder Heading","text","GRINDER"],
  ["home","private_program","grinder_text","Grinder Text","text","Grinder bottles (plastic/glass)"],
  ["home","private_program","grinder_note","Grinder Note","text","Refillable & retail ready"],
  ["home","private_program","bulk_packaging_title","Bulk Packaging Heading","text","BULK PACKAGING"],
  ["home","private_program","bulk_packaging_text","Bulk Packaging Text","text","5kg, 10kg, 25kg+ options"],
  ["home","private_program","bulk_packaging_note","Bulk Packaging Note","text","For brands & distributors"],
  ["home","private_program","bulk_bags_title","Bulk Bags Heading","text","BULK BAGS"],
  ["home","private_program","bulk_bags_text","Bulk Bags Text","text","25kg+ HDPE / PP bags"],
  ["home","private_program","bulk_bags_note","Bulk Bags Note","text","Custom printing available"],
  ["home","private_program","view_options","Packaging Card Button","text","VIEW OPTIONS"],
  ["home","product_families","eyebrow","Product Families Eyebrow","text","PRODUCT FAMILIES"],
  ["home","product_families","title","Product Families Heading","text","Product Families for International Buyers."],
  ["home","product_families","view_all","Product Families View All","text","View All Products"],
  ["home","product_families","explore","Product Families Card Button","text","Explore"],
  ["home","product_families","edible_title","Edible Salt Heading","text","Edible Salt"],
  ["home","product_families","edible_text","Edible Salt Text","textarea","Pure, natural and additive-free Himalayan pink salt for food & culinary use."],
  ["home","product_families","grinders_title","Grinders & Shakers Heading","text","Grinders & Shakers"],
  ["home","product_families","grinders_text","Grinders & Shakers Text","textarea","Convenient formats with consistent grain sizes and premium presentation."],
  ["home","product_families","bulk_title","Bulk Supply Heading","text","Bulk Supply"],
  ["home","product_families","bulk_text","Bulk Supply Text","textarea","High-volume supply in bulk bags or cartons for industrial & food manufacturing."],
  ["home","product_families","animal_title","Animal Lick Salt Heading","text","Animal Lick Salt"],
  ["home","product_families","animal_text","Animal Lick Salt Text","textarea","Naturally rich in minerals for livestock and animal well-being."],
  ["home","product_families","lamps_title","Salt Lamps & Décor Heading","text","Salt Lamps & Décor"],
  ["home","product_families","lamps_text","Salt Lamps & Décor Text","textarea","Handcrafted salt lamps and décor pieces for wellness and ambient living."],
  ["home","product_families","tiles_title","Salt Tiles & Bricks Heading","text","Salt Tiles & Bricks"],
  ["home","product_families","tiles_text","Salt Tiles & Bricks Text","textarea","Himalayan salt tiles and bricks for construction, spa and interior design."],
  ["home","why_choose","title","Why Choose Us Heading","text","WHY CHOOSE US"],
  ["home","why_choose","description","Why Choose Us Description","textarea","Dependable export supply, flexible order planning, market-ready packaging, documentation support and specification-focused quality."],
  ["home","why_choose","item_1_title","Why Choose Item 1 Heading","text","Reliable Supply"],
  ["home","why_choose","item_1_text","Why Choose Item 1 Description","textarea","Planned production and dependable export supply for wholesalers, distributors and private-label programs."],
  ["home","why_choose","item_2_title","Why Choose Item 2 Heading","text","Flexible MOQ"],
  ["home","why_choose","item_2_text","Why Choose Item 2 Description","textarea","Order quantities suited to trial launches, growing brands and established importers."],
  ["home","why_choose","item_3_title","Why Choose Item 3 Heading","text","Custom Packaging"],
  ["home","why_choose","item_3_text","Why Choose Item 3 Description","textarea","PET bottles, grinders, jars and stand-up pouches customized for your brand and target market."],
  ["home","why_choose","item_4_title","Why Choose Item 4 Heading","text","Export Support"],
  ["home","why_choose","item_4_text","Why Choose Item 4 Description","textarea","Support for product specifications, commercial documents and international shipment coordination."],
  ["home","why_choose","item_5_title","Why Choose Item 5 Heading","text","Quality Focused"],
  ["home","why_choose","item_5_text","Why Choose Item 5 Description","textarea","Specification-based packing and defined quality checks for food-grade Himalayan Pink Salt."],
  ["home","why_choose","item_6_title","Why Choose Item 6 Heading","text","Global Reach"],
  ["home","why_choose","item_6_text","Why Choose Item 6 Description","textarea","Responsive B2B support for retail, foodservice and distribution buyers across international markets."],
  ["home","collections","title","Signature Collections Heading","textarea","Product families for international buyers."],
  ["home","collections","description","Signature Collections Description","textarea","A refined collection architecture covering retail, private label, bulk, livestock, foodservice and premium market formats."],
  ["home","collections","retail_eyebrow","Retail Collection Eyebrow","text","Retail Collection"],
  ["home","collections","retail_title","Retail Collection Heading","text","Retail Packaging"],
  ["home","collections","retail_text","Retail Collection Description","textarea","Shelf-ready formats designed for grocery, gourmet, specialty retail and private-label programs."],
  ["home","collections","bulk_eyebrow","Bulk Collection Eyebrow","text","Bulk Collection"],
  ["home","collections","bulk_title","Bulk Collection Heading","text","Bulk Supply"],
  ["home","collections","bulk_text","Bulk Collection Description","textarea","Commercial formats for importers, foodservice buyers and ingredient-led supply programs."],
  ["home","collections","private_label_eyebrow","Private Label Collection Eyebrow","text","Private Label"],
  ["home","collections","private_label_title","Private Label Collection Heading","text","Custom Brand Programs"],
  ["home","collections","private_label_text","Private Label Collection Description","textarea","Packaging and brand-development support for buyers building a premium salt range under their own identity."],
  ["home","collections","animal_lick_eyebrow","Animal Lick Collection Eyebrow","text","Livestock Range"],
  ["home","collections","animal_lick_title","Animal Lick Collection Heading","text","Animal Lick Salt"],
  ["home","collections","animal_lick_text","Animal Lick Collection Description","textarea","A dedicated commercial category for livestock and agricultural buyers requiring trade-ready salt formats."],
  ["home","collections","foodservice_eyebrow","Foodservice Collection Eyebrow","text","Hospitality Range"],
  ["home","collections","foodservice_title","Foodservice Collection Heading","text","Foodservice Packs"],
  ["home","collections","foodservice_text","Foodservice Collection Description","textarea","Professional salt formats for chefs, restaurants, catering, hospitality and refill requirements."],
  ["home","collections","gourmet_eyebrow","Gourmet Collection Eyebrow","text","Gourmet Range"],
  ["home","collections","gourmet_title","Gourmet Collection Heading","text","Gourmet & Lifestyle"],
  ["home","collections","gourmet_text","Gourmet Collection Description","textarea","Presentation-led formats for gifting, gourmet shelves and curated premium salt collections."],
  ["home","quality","title","Quality Standards Heading","text","OUR QUALITY STANDARDS"],
  ["home","quality","description","Quality Standards Description","textarea","Certified quality you can trust."],
  ["home","export","title","Export Markets Heading","text","TRUSTED BY BUYERS IN 50+ COUNTRIES"],
  ["home","export","countries","Export Destinations Number","text","50+"],
  ["home","export","buyers","International Buyers Number","text","500+"],
  ["home","export","destinations_label","Export Destinations Label","text","Export Destinations"],
  ["home","export","buyers_label","International Buyers Label","text","International Buyers"],
  ["home","export","supply_value","Supply Capability Value","text","Bulk"],
  ["home","export","supply_label","Supply Capability Label","text","Supply Capability"],
  ["home","export","quality_value","Export Quality Value","text","100%"],
  ["home","export","quality_label","Export Quality Label","text","Export Quality Focused"],
  ["products","hero","eyebrow","Products Eyebrow","text","PRODUCTS"],
  ["products","hero","title_main","Products Heading Main","text","Our "],
  ["products","hero","title_accent","Products Heading Accent / Italic","text","Products"],
  ["products","hero","description_one","Products Hero Description Line 1","text","Naturally pure. Rich in minerals. Responsibly sourced."],
  ["products","hero","description_two","Products Hero Description Line 2","textarea","A complete range of Himalayan pink salt products crafted for every industry and need."],
  ["products","categories","edible_name","Edible Salt Category Name","text","Edible Salt"],
  ["products","categories","edible_subtitle","Edible Salt Category Subtitle","text","For Food & Beverages"],
  ["products","categories","lamps_name","Salt Lamps Category Name","text","Salt Lamps"],
  ["products","categories","lamps_subtitle","Salt Lamps Category Subtitle","text","For Decor & Wellness"],
  ["products","categories","tiles_name","Salt Tiles / Bricks Category Name","text","Salt Tiles / Bricks"],
  ["products","categories","tiles_subtitle","Salt Tiles / Bricks Category Subtitle","text","For Walls & Decor"],
  ["products","categories","slabs_name","Cooking Plates / Slabs Category Name","text","Cooking Plates / Slabs"],
  ["products","categories","slabs_subtitle","Cooking Plates / Slabs Category Subtitle","text","For Culinary & Serving"],
  ["products","categories","lick_name","Animal Lick Salt Category Name","text","Animal Lick Salt"],
  ["products","categories","lick_subtitle","Animal Lick Salt Category Subtitle","text","For Livestock"],
  ["products","categories","bulk_name","Bulk & Raw Salt Category Name","text","Bulk & Raw Salt"],
  ["products","categories","bulk_subtitle","Bulk & Raw Salt Category Subtitle","text","For Bulk Supply"],
  ["products","product_family","edible_eyebrow","Edible Salt Eyebrow","text","EDIBLE SALT"],
  ["products","product_family","edible_title_main","Edible Salt Heading Main","text","Edible Salt "],
  ["products","product_family","edible_title_accent","Edible Salt Heading Accent / Italic","text","Products"],
  ["products","product_family","edible_description","Edible Salt Description","textarea","Extra fine powder, coarse crystals and future flake formats in retail-ready packaging."],
  ["products","product_family","collection_title_accent","Other Family Heading Accent / Italic","text","Products"],
  ["products","product_family","collection_description","Other Family Description","textarea","Commercial Himalayan pink salt formats prepared for this product family and buyer requirements."],
  ["products","product_family","tab_granules","Coarse Tab Label","text","Coarse"],
  ["products","product_family","tab_powder","Extra Fine Powder Tab Label","text","Extra Fine Powder"],
  ["products","product_family","tab_flakes","Flakes Tab Label","text","Flakes"],
  ["products","product_family","grain_label","Product Form / Grain Label","text","Form / Grain"],
  ["products","product_family","packaging_label","Product Packaging Label","text","Packaging"],
  ["products","product_family","pack_size_label","Product Pack Sizes Label","text","Pack Sizes"],
  ["products","product_family","view_details","Product Card Link Label","text","View Details"],
  ["products","product_family","catalog_note","Catalog Availability Label","text","Available for enquiry"],
  ["products","bulk_packaging","eyebrow","Bulk Packaging Eyebrow","text","BULK PACKAGING"],
  ["products","bulk_packaging","title_main","Bulk Packaging Heading Main","text","Bulk Packaging "],
  ["products","bulk_packaging","title_accent","Bulk Packaging Heading Accent / Italic","text","Options"],
  ["products","bulk_packaging","description","Bulk Packaging Description","textarea","High quality pink salt available in bulk for industrial, food processing, and export needs."],
  ["products","bulk_packaging","bag_label","Bulk Bag Type Label","text","Woven / PP Bag"],

  ["about","hero","crumbs","About Breadcrumb","text","HOME / ABOUT US"],
  ["about","hero","title_main","About Heading Main","text","The Legacy of "],
  ["about","hero","title_accent","About Heading Accent / Italic","text","the Mountains"],
  ["about","hero","description","About Hero Description","textarea","A 250-million-year-old journey—from the pristine foothills of the Himalayas directly to your brand."],
  ["about","story","eyebrow","Story Eyebrow","text","Our Story & Mission"],
  ["about","story","title_main","Story Heading Main","text","Custodians of Earth’s "],
  ["about","story","title_accent","Story Heading Accent / Italic","text","Purest Treasure"],
  ["about","story","body_one","Story Paragraph 1","textarea","Long before modern civilization, ancient, unpolluted oceans crystallized deep beneath the majestic peaks of the Himalayas. Locked away from time and toxins for 250 million years, this naturally pink, mineral-rich treasure remained untouched."],
  ["about","story","body_two","Story Paragraph 2","textarea","At The Salt Origin, our story doesn’t start with a business plan, it starts with a profound respect for this legacy. We realized that this ancient gift deserved to be shared with the world in its most authentic form."],
  ["about","story","body_three","Story Paragraph 3","textarea","But we didn’t just want to be another company moving boxes across oceans. We wanted to build a bridge between the rugged, beautiful salt mines of Pakistan and the retail shelves of the world."],
  ["about","story","body_four","Story Paragraph 4","textarea","Today, we are proud to be the silent force behind global brands, empowering them to share a piece of the earth’s purest history with their customers."],
  ["about","founder","eyebrow","Founder Eyebrow","text","A Message from the Founder"],
  ["about","founder","title_main","Founder Heading Main","text","Building a Partnership "],
  ["about","founder","title_accent","Founder Heading Accent / Italic","text","Built on Peace of Mind"],
  ["about","founder","message","Founder Message","textarea","Every great brand is built on a foundation of absolute trust. When I founded The Salt Origin, I looked at the global export market and saw a missing piece: genuine, human connection.\n\nI saw international buyers struggling with inconsistent quality, broken promises, and the anxiety of managing supply chains from thousands of miles away. I wanted to change that.\n\nMy vision was to build more than just an export company; I wanted to build a bridge of absolute reliability. I wanted you to feel the passion we have for this extraordinary pink salt, and the deep respect we have for your business.\n\nWhen you choose to work with us, you aren’t just another order number—you become part of our story. We take on the heavy lifting so you can focus on what you do best: growing your brand, knowing your supply chain is in safe, caring hands."],
  ["about","founder","name","Founder Name","text","Hamza Khan"],
  ["about","founder","role","Founder Role","textarea","Founder, The Salt Origin & The Khan & Co."],
  ["about","quality","eyebrow","Quality Eyebrow","text","Our Commitment to Quality"],
  ["about","quality","title_main","Quality Heading Main","text","Protecting "],
  ["about","quality","title_accent","Quality Heading Accent / Italic","text","the Purity"],
  ["about","quality","body_one","Quality Paragraph 1","textarea","A natural gift that has remained pure for millions of years demands the highest level of respect. We refuse to compromise on how this treasure is handled."],
  ["about","quality","body_two","Quality Paragraph 2","textarea","To honor the salt’s natural perfection and to protect your consumers, every single batch is meticulously processed, refined, and packaged within state-of-the-art, internationally certified facilities."],
  ["about","quality","body_three","Quality Paragraph 3","textarea","We don’t just meet global food safety standards; we embrace them as our moral obligation to you. This is our promise: flawless execution from the ancient mines to your customer’s table."],
  ["about","quality","natural_title","Quality Card — Naturally Pure","text","Naturally Pure"],
  ["about","quality","natural_text","Quality Card — Naturally Pure Text","text","250-million-year-old pristine Himalayan salt"],
  ["about","quality","facility_title","Quality Card — Certified Facilities","text","Certified Facilities"],
  ["about","quality","facility_text","Quality Card — Certified Facilities Text","text","Processed in internationally certified & audited plants"],
  ["about","quality","standards_title","Quality Card — Global Standards","text","Global Standards"],
  ["about","quality","standards_text","Quality Card — Global Standards Text","text","Exceeding food safety standards worldwide"],
  ["about","quality","execution_title","Quality Card — Flawless Execution","text","Flawless Execution"],
  ["about","quality","execution_text","Quality Card — Flawless Execution Text","text","From ancient mines to your customer’s table"],

  ["private-label","hero","crumbs","Private Label Breadcrumb","text","HOME / PRIVATE LABEL"],
  ["private-label","hero","title_main","Private Label Heading Main","text","Your brand. Our "],
  ["private-label","hero","title_accent","Private Label Heading Accent / Italic","text","origin."],
  ["private-label","hero","description_current","Private Label Hero Description","textarea","Premium private-label Himalayan pink salt solutions crafted to reflect your brand and meet your market needs."],
  ["private-label","hero","feature_1_title","Private Label Hero Feature 1","text","Custom Branding"],
  ["private-label","hero","feature_1_text","Private Label Hero Feature 1 Text","text","Your logo, identity and label direction."],
  ["private-label","hero","feature_2_title","Private Label Hero Feature 2","text","Wide Packaging Range"],
  ["private-label","hero","feature_2_text","Private Label Hero Feature 2 Text","text","Pouches, jars, bottles and grinders."],
  ["private-label","hero","feature_3_title","Private Label Hero Feature 3","text","Market-Ready Quality"],
  ["private-label","hero","feature_3_text","Private Label Hero Feature 3 Text","text","Food-grade, consistent and reliable."],
  ["private-label","hero","feature_4_title","Private Label Hero Feature 4","text","Global Supply"],
  ["private-label","hero","feature_4_text","Private Label Hero Feature 4 Text","text","Export planning for international markets."],
  ["private-label","hero","quote_button","Private Label Hero Quote Button","text","Start Your Private Label Quote"],
  ["private-label","studio","eyebrow","Packaging Studio Eyebrow","text","Packaging Studio"],
  ["private-label","studio","title_main","Packaging Studio Heading Main","text","Choose the format your market "],
  ["private-label","studio","title_accent","Packaging Studio Heading Accent / Italic","text","expects."],
  ["private-label","studio","description","Packaging Studio Description","textarea","Select from a focused range of private-label packaging formats designed for retail, distribution and export programs."],
  ["private-label","studio","pouches_title","Packaging Format — Pouches","text","Pouches"],
  ["private-label","studio","pouches_text","Packaging Format — Pouches Text","text","Stand-up & gusseted"],
  ["private-label","studio","jars_title","Packaging Format — Jars","text","Jars"],
  ["private-label","studio","jars_text","Packaging Format — Jars Text","text","Round & square"],
  ["private-label","studio","bottles_title","Packaging Format — Bottles","text","Bottles"],
  ["private-label","studio","bottles_text","Packaging Format — Bottles Text","text","Shakers & PET"],
  ["private-label","studio","grinders_title","Packaging Format — Grinders","text","Grinders"],
  ["private-label","studio","grinders_text","Packaging Format — Grinders Text","text","Plastic, ceramic & glass"],
  ["private-label","studio","bulk_title","Packaging Format — Bulk","text","Bulk"],
  ["private-label","studio","bulk_text","Packaging Format — Bulk Text","text","Commercial formats"],
  ["private-label","studio","branding_title","Branding Label","text","Branding"],
  ["private-label","studio","branding_text","Branding Text","text","Front, back and regulatory panel"],
  ["private-label","studio","formats_title","Formats Label","text","Formats"],
  ["private-label","studio","formats_text","Formats Text","text","Pouch, jar, grinder or bulk"],
  ["private-label","studio","commercial_title","Commercial Label","text","Commercial"],
  ["private-label","studio","commercial_text","Commercial Text","text","MOQ, volume and destination"],
  ["private-label","studio","quote_button","Private Label Quote Button","text","Start Your Private Label Quote"],
  ["private-label","studio","mockup_title","Mockup Heading","text","Interactive mockup"],
  ["private-label","studio","mockup_text","Mockup Description","text","Preview packaging formats in real time."],
  ["private-label","range","eyebrow","Private Label Range Eyebrow","text","Our Private Label Range"],
  ["private-label","range","title_main","Private Label Range Heading Main","text","Packaging options for "],
  ["private-label","range","title_accent","Private Label Range Heading Accent / Italic","text","every market."],
  ["private-label","range","description","Private Label Range Description","textarea","Choose the salt form and packaging format that best fits your retail, distributor or private-label program."],
  ["private-label","workflow","eyebrow","Workflow Eyebrow","text","Private Label Workflow"],
  ["private-label","workflow","title_main","Workflow Heading Main","text","From concept to "],
  ["private-label","workflow","title_accent","Workflow Heading Accent / Italic","text","production-ready."],
  ["private-label","workflow","description","Workflow Description","textarea","A clear commercial path keeps packaging, specification and approvals moving efficiently."],
  ["private-label","workflow","brief_title","Step 1 Heading","text","Brief"],
  ["private-label","workflow","brief_text","Step 1 Text","textarea","Market, product, pack size, target volume and deadline."],
  ["private-label","workflow","spec_title","Step 2 Heading","text","Specification"],
  ["private-label","workflow","spec_text","Step 2 Text","textarea","Grain, packaging materials and quality requirements."],
  ["private-label","workflow","artwork_title","Step 3 Heading","text","Artwork"],
  ["private-label","workflow","artwork_text","Step 3 Text","textarea","Brand files, label panel structure and approvals."],
  ["private-label","workflow","production_title","Step 4 Heading","text","Production"],
  ["private-label","workflow","production_text","Step 4 Text","textarea","Final commercial approval, packing and dispatch."],
  ["private-label","workspace","eyebrow","Buyer Workspace Eyebrow","text","Buyer Workspace"],
  ["private-label","workspace","title_main","Buyer Workspace Heading Main","text","Build a complete "],
  ["private-label","workspace","title_accent","Buyer Workspace Heading Accent / Italic","text","private-label brief."],
  ["private-label","workspace","description","Buyer Workspace Description","textarea","Prepare the inputs your sales and production teams need before commercial approval."],
  ["private-label","workspace","artwork_title","Workspace Card — Artwork","text","Artwork Upload"],
  ["private-label","workspace","artwork_text","Workspace Card — Artwork Text","textarea","Share logo, dieline and brand guidelines."],
  ["private-label","workspace","moq_title","Workspace Card — MOQ","text","MOQ Planning"],
  ["private-label","workspace","moq_text","Workspace Card — MOQ Text","textarea","Match packaging format with commercial volume."],
  ["private-label","workspace","sample_title","Workspace Card — Sample","text","Sample Request"],
  ["private-label","workspace","sample_text","Workspace Card — Sample Text","textarea","Request product or packaging samples before production."],
  ["private-label","workspace","quote_title","Workspace Card — Quote","text","Quote Portal"],
  ["private-label","workspace","quote_text","Workspace Card — Quote Text","textarea","Review quotations, revisions and approved documents."],
  ["private-label","workspace","link_label","Workspace Card Link Label","text","Start request"],
  ["private-label","cta","title_current","Private Label CTA Heading","text","Ready to build your private-label salt range?"],
  ["private-label","cta","description_current","Private Label CTA Description","textarea","Share your target market, packaging format and expected volume."],
  ["private-label","cta","button","Private Label CTA Button","text","Start Private Label Quote"],

  ["certifications","hero","crumbs","Certifications Breadcrumb","text","HOME / CERTIFICATIONS"],
  ["certifications","hero","title_main","Certifications Heading Main","text","Quality you can "],
  ["certifications","hero","title_accent","Certifications Heading Accent / Italic","text","verify."],
  ["certifications","hero","description_current","Certifications Hero Description","textarea","Our Himalayan pink salt products are manufactured and packed through certified facilities, with supporting documents available for qualified buyer review."],
  ["certifications","documents","eyebrow","Certification Center Eyebrow","text","Certified Manufacturing & Packing Facility"],
  ["certifications","documents","title_main","Certification Center Heading Main","text","Facility documentation, "],
  ["certifications","documents","title_accent","Certification Center Heading Accent / Italic","text","organized."],
  ["certifications","documents","description","Certification Center Description","textarea","The Salt Origin works with certified manufacturing and packing facilities. Supporting documents are available to qualified buyers after verification."],
  ["certifications","documents","access_note","Document Access Note","textarea","Certificate copies, registration details, issue/expiry dates and supporting files are shared only after internal verification and buyer-access approval."],
  ["certifications","documents","request_title","Document Request Heading","text","Need facility documents for your import review?"],
  ["certifications","documents","request_text","Document Request Text","textarea","Request the exact certificates and supporting files required by your company."],
  ["certifications","documents","request_button","Document Request Button","text","Request Documents"],

  ["contact","hero","crumbs","Contact Breadcrumb","text","HOME / CONTACT"],
  ["contact","hero","title_main","Contact Heading Main","text","Start a "],
  ["contact","hero","title_accent","Contact Heading Accent / Italic","text","commercial conversation."],
  ["contact","hero","description","Contact Hero Description","textarea","A focused B2B contact page with sales routing, inquiry qualification and clear response expectations."],
  ["contact","contact-details","eyebrow","Contact Details Eyebrow","text","Get in touch"],
  ["contact","contact-details","title","Contact Details Heading","text","Tell us what you need."],
  ["contact","contact-details","description","Contact Details Description","textarea","Connect with the appropriate commercial team for product, private-label, documentation and export inquiries."],
  ["contact","contact-details","sales_label","Sales Inquiries Label","text","Sales inquiries"],
  ["contact","contact-details","private_label_label","Private Label Contact Label","text","Private label"],
  ["contact","contact-details","private_label_text","Private Label Contact Text","text","Packaging, branding and retail program inquiries"],
  ["contact","contact-details","documents_label","Documentation Contact Label","text","Documentation"],
  ["contact","contact-details","documents_text","Documentation Contact Text","text","Facility certificates, COA, lab reports and product specifications"],
  ["contact","contact-details","location_label","Location Label","text","Location"],
  ["contact","form","form_eyebrow","Form Eyebrow","text","B2B Inquiry Form"],
  ["contact","form","form_title","Form Heading","text","Send a message"],
  ["contact","form","full_name","Full Name Label","text","Full Name"],
  ["contact","form","business_email","Business Email Label","text","Business Email"],
  ["contact","form","company","Company Label","text","Company"],
  ["contact","form","whatsapp","WhatsApp / Phone Label","text","WhatsApp / Phone"],
  ["contact","form","country","Country Label","text","Country"],
  ["contact","form","inquiry_type","Inquiry Type Label","text","Inquiry Type"],
  ["contact","form","volume","Estimated Volume Label","text","Estimated Volume"],
  ["contact","form","message","Message Label","text","Message"],
  ["contact","form","submit","Inquiry Submit Button","text","Send Inquiry"],

  ["blog","hero","crumbs","Blog Breadcrumb","text","HOME / BLOG"],
  ["blog","hero","title_main","Blog Heading Main","text","The Salt "],
  ["blog","hero","title_accent","Blog Heading Accent / Italic","text","Journal."],
  ["blog","hero","description","Blog Hero Description","textarea","Editorial content designed for SEO, commercial education and buyer confidence — without looking like generic filler."],
  ["blog","listing","newsletter_title","Newsletter Heading","text","Subscribe to the Salt Journal"],
  ["blog","listing","newsletter_text","Newsletter Description","text","Product guides, private-label notes and export updates."],
  ["blog","listing","open_article","Blog Card Link Label","text","Open article →"],
  ["blog","cta","title","Blog CTA Heading","text","Planning your next salt program?"],
  ["blog","cta","description","Blog CTA Description","textarea","Turn your product, packaging and destination requirements into a focused commercial conversation with our B2B team."],
  ["blog","cta","quote_button","Blog CTA Quote Button","text","Get a Quote"],
  ["blog","cta","products_button","Blog CTA Products Button","text","Browse Products"],

  ["faqs","hero","crumbs","FAQ Breadcrumb","text","HOME / FAQ"],
  ["faqs","hero","title_main","FAQ Heading Main","text","Buyer questions, "],
  ["faqs","hero","title_accent","FAQ Heading Accent / Italic","text","answered."],
  ["faqs","hero","description","FAQ Hero Description","textarea","Built to reduce friction for importers, distributors, private-label buyers and retail teams."],
  ["faqs","faq","eyebrow","FAQ B2B Card Eyebrow","text","Need more detail?"],
  ["faqs","faq","title","FAQ B2B Card Heading","text","Talk to the B2B desk."],
  ["faqs","faq","description","FAQ B2B Card Description","textarea","If a question is product-specific, send the product, packaging, volume and destination so it reaches the right commercial person."],
  ["faqs","faq","button","FAQ B2B Card Button","text","Ask Sales"],
  ["privacy-policy","content","title","Privacy Policy Heading","text","Privacy Policy"],
  ["privacy-policy","content","introduction","Privacy Policy Introduction","textarea",""],
  ["privacy-policy","content","body","Privacy Policy Content","textarea",""],
  ["terms-and-conditions","content","title","Terms & Conditions Heading","text","Terms & Conditions"],
  ["terms-and-conditions","content","introduction","Terms & Conditions Introduction","textarea",""],
  ["terms-and-conditions","content","body","Terms & Conditions Content","textarea",""],
  ["global","footer","description","Footer Description","textarea","Premium Himalayan pink salt for retail, foodservice, private label and global B2B supply. Clear specifications, responsive service and export-focused support for international buyers."],].map((row, index) => {
  const [page_slug, section_slug, field_key, field_label, field_type, default_value] = row as [string,string,string,string,"text"|"textarea",string];
  return { page_slug, section_slug, field_key, field_label, field_type, default_value, display_order: index + 1 };
});
