export type CmsImageSlotSeed = {
  page_slug: string;
  section_slug: string;
  slot_key: string;
  title: string;
  current_url: string;
  default_url: string;
  alt_text: string;
  recommended_width: number;
  recommended_height: number;
  display_order: number;
  is_active: boolean;
};

export type CmsTextSeed = {
  page_slug: string;
  section_slug: string;
  field_key: string;
  field_label: string;
  field_type: "text" | "textarea";
  default_value: string;
  display_order: number;
};

export const cmsPageLabels: Record<string, string> = {
  global: "Branding / Footer",
  home: "Homepage",
  about: "About Page",
  products: "Products Page",
  "private-label": "Private Label",
  certifications: "Certifications",
  contact: "Contact Page",
  blog: "Blog Page",
  faqs: "FAQ Page",
  "privacy-policy": "Privacy Policy",
  "terms-and-conditions": "Terms & Conditions",
};

export const cmsImageRegistry: CmsImageSlotSeed[] = [
  ["global","branding","logo","Shared Logo — Legacy Fallback","/logo.png","The Salt Origin logo",400,220],
  ["global","branding","header_logo","Header / Navbar Logo","/logo.png","The Salt Origin header logo",500,220],
  ["global","branding","footer_logo","Footer Logo","/logo.png","The Salt Origin footer logo",500,220],
  ["home","hero","products","Hero Section — Product Collection","/hero-products.png","Himalayan Pink Salt product collection",900,900],
  ["home","hero","mountains","Hero Section — Mountain Background","/mountains-bg.png","Himalayan mountain background",1920,900],
  ["home","private_label","custom_labels","Private Label — Custom Bottles","/custom-labels.png","Custom bottles",600,400],
  ["home","private_label","custom_packaging","Private Label — Custom Packaging","/custom-packaging.png","Custom packaging",600,400],
  ["home","products","pet_bottles","Product Range — PET Bottles","/pet-bottles.png","PET salt bottles",600,600],
  ["home","products","pet_jars","Product Range — PET Jars","/pet-jars.png","PET salt jars",600,600],
  ["home","products","grinders","Product Range — Grinder Collection","/grinder-bottles.png","Salt grinder bottles",600,600],
  ["home","products","pouches","Product Range — Stand-Up Pouch","/standup-pouch.png","Stand-up salt pouch",600,600],
  ["home","collections","retail","Signature Collection — Retail Packaging","/product-2.png","Retail packaging collection",900,700],
  ["home","collections","bulk","Signature Collection — Bulk Supply","/white-sack.png","Bulk salt supply",900,700],
  ["home","collections","private_label","Signature Collection — Private Label","/custom-labels.png","Private label salt packaging",900,700],
  ["home","collections","animal_lick","Signature Collection — Animal Lick Salt","/hero-banner.png","Animal lick salt collection",900,700],
  ["home","collections","foodservice","Signature Collection — Foodservice","/product-5.png","Foodservice pink salt format",900,700],
  ["home","collections","gourmet","Signature Collection — Gourmet & Lifestyle","/product-4.png","Gourmet pink salt collection",900,700],
  ["home","quality","iso","Quality — ISO Certificate","/cert-iso.png","ISO certificate",400,400],
  ["home","quality","haccp","Quality — HACCP Certificate","/cert-haccp.png","HACCP certificate",400,400],
  ["home","quality","gmp","Quality — GMP Certificate","/cert-gmp.png","GMP certificate",400,400],
  ["home","quality","halal","Quality — Halal Certificate","/cert-halal.png","Halal certificate",400,400],
  ["home","quality","fda","Quality — FDA Certificate","/cert-fda.png","FDA registration",400,400],
  ["home","quality","food","Quality — Food Certificate","/cert-food.png","Food certificate",400,400],
  ["home","export","map","Export Markets — World Map","/world-map.png","World export map",1400,700],
  ["about","hero","banner","About Page — Hero Banner","/hero-banner.png","About The Salt Origin",1600,900],
  ["about","hero","mountains","About Page — Mountain Background","/mountains-bg.png","Himalayan mountain illustration",1920,900],
  ["about","story","collage","About Page — Product Collage","/product-collage.png","Salt product collage",1200,800],
  ["products","retail","shaker","Products — Salt Shaker","/shaker-bottles.png","Salt shaker collection",800,800],
  ["products","retail","jar","Products — Salt Jar","/pet-jars.png","Salt jar collection",800,800],
  ["products","retail","pouch","Products — Stand-Up Pouch","/pouches.png","Stand-up pouch collection",800,800],
  ["products","grinder","plastic","Products — Plastic Grinder","/grinder-bottles.png","Plastic grinder bottles",800,800],
  ["products","grinder","ceramic","Products — Ceramic Grinder","/ceramic-grinders.png","Ceramic grinder bottles",800,800],
  ["products","bulk","bag","Products — Bulk Salt Bag","/white-sack.png","Bulk salt bag",800,800],
  ["private-label","hero","main","Private Label — Hero Image","/custom-logo-design.png","Private label salt branding",1200,900],
  ["private-label","process","labels","Private Label — Labels","/custom-labels.png","Custom labels",800,600],
  ["private-label","process","packaging","Private Label — Packaging","/custom-packaging.png","Custom packaging",800,600],
  ["certifications","cards","iso","Certifications Page — ISO","/cert-iso.png","ISO certification",500,500],
  ["certifications","cards","haccp","Certifications Page — HACCP","/cert-haccp.png","HACCP certification",500,500],
  ["certifications","cards","gmp","Certifications Page — GMP","/cert-gmp.png","GMP certification",500,500],
  ["certifications","cards","halal","Certifications Page — Halal","/cert-halal.png","Halal certification",500,500],
  ["certifications","cards","fda","Certifications Page — FDA","/cert-fda.png","FDA registration",500,500],
  ["contact","hero","banner","Contact Page — Hero Image","/hero-banner.png","Contact The Salt Origin",1600,900],
  ["blog","listing","default","Blog — Default Featured Image","/og-image.jpg","Himalayan Pink Salt blog",1200,630],
].map((row, index) => {
  const [page_slug, section_slug, slot_key, title, url, alt_text, recommended_width, recommended_height] = row as [string,string,string,string,string,string,number,number];
  return { page_slug, section_slug, slot_key, title, current_url: url, default_url: url, alt_text, recommended_width, recommended_height, display_order: index + 1, is_active: true };
});

export const cmsTextRegistry: CmsTextSeed[] = [
  ["global","navbar","home","Home Menu Label","text","Home"],
  ["global","navbar","about","About Menu Label","text","About Us"],
  ["global","navbar","products","Products Menu Label","text","Products"],
  ["global","navbar","private_label","Private Label Menu Label","text","Private Label"],
  ["global","navbar","certifications","Certifications Menu Label","text","Certifications"],
  ["global","navbar","blog","Blog Menu Label","text","Blog"],
  ["global","navbar","faq","FAQ Menu Label","text","FAQ"],
  ["global","navbar","contact","Contact Menu Label","text","Contact"],
  ["global","navbar","quote","Quote Button Label","text","Get Quote"],
  ["global","branding","logo_alt","Header & Footer Logo Alt Text","text","The Salt Origin"],
  ["global","footer","brand_tagline","Footer Brand Tagline","text","Himalayan Pink Salt Exporter"],
  ["global","footer","social_title","Footer Social Media Heading","text","Connect with us"],
  ["global","footer","quick_links_title","Footer Quick Links Heading","text","Quick Links"],
  ["global","footer","contact_title","Footer Contact Heading","text","Contact Info"],
  ["global","footer","policies_title","Footer Policies Heading","text","Policies"],
  ["global","footer","quote_button","Footer Quote Button Label","text","Get Quote"],
  ["global","footer","copyright","Footer Copyright Line","textarea","© {year} {site}. All Rights Reserved."],
  ["global","footer","privacy_label","Footer Privacy Link Label","text","Privacy Policy"],
  ["global","footer","terms_label","Footer Terms Link Label","text","Terms & Conditions"],
  ["global","footer","bottom_note","Footer Bottom Note","textarea","Premium Himalayan Pink Salt\nSupplier & Private Label Partner"],
  ["global","footer","website_credit","Website Designed / Developed By Line","textarea",""],
  ["home","hero","badge","Hero Badge","text","PREMIUM QUALITY"],
  ["home","hero","title","Hero Main Heading","textarea","Himalayan Pink Salt Solutions For Global Markets"],
  ["home","hero","description","Hero Description","textarea","We provide premium quality Himalayan Pink Salt in multiple forms and packaging, trusted by importers, distributors and brands worldwide."],
  ["home","hero","primary_button","Explore Products Button","text","Explore Products"],
  ["home","hero","secondary_button","Request Quote Button","text","Request Quote"],
  ["home","private_label","title","Private Label Heading","text","PRIVATE LABEL SOLUTIONS"],
  ["home","private_label","description","Private Label Description","textarea","We help brands create their identity with fully customized bottles and packaging."],
  ["home","private_label","bullet_bottles","Private Label Bullet — Bottles","text","Custom Bottles"],
  ["home","private_label","bullet_packaging","Private Label Bullet — Packaging","text","Custom Packaging"],
  ["home","private_label","button","Private Label Button","text","Learn More"],
  ["home","private_label","bottles_title","Custom Bottles Card Heading","text","Custom Bottles"],
  ["home","private_label","bottles_text","Custom Bottles Card Description","textarea","Choose your bottle style, size and design to match your brand identity."],
  ["home","private_label","packaging_title","Custom Packaging Card Heading","text","Custom Packaging"],
  ["home","private_label","packaging_text","Custom Packaging Card Description","textarea","Custom printed pouches and jars with your logo, colors and design."],
  ["home","products","title","Product Range Heading","text","OUR PRODUCT RANGE"],
  ["home","products","description","Product Range Description","textarea","Premium Himalayan Pink Salt products for retail, private label and global distribution."],
  ["home","products","pet_bottles_title","PET Bottles Card Heading","text","PET Bottles"],
  ["home","products","pet_bottles_text","PET Bottles Card Description","textarea","Multiple sizes for everyday use and retail."],
  ["home","products","pet_jars_title","PET Jars Card Heading","text","PET Jars"],
  ["home","products","pet_jars_text","PET Jars Card Description","textarea","Fine grain salt in convenient PET jars."],
  ["home","products","grinders_title","Grinder Card Heading","text","Grinder Collection"],
  ["home","products","grinders_text","Grinder Card Description","textarea","Plastic and ceramic grinder bottles."],
  ["home","products","pouches_title","Pouches Card Heading","text","Stand-Up Pouches"],
  ["home","products","pouches_text","Pouches Card Description","textarea","Premium zip-lock pouches for maximum freshness."],
  ["home","products","view_button","Product Card Button","text","View Products"],
  ["home","why_choose","title","Why Choose Us Heading","text","WHY CHOOSE US"],
  ["home","why_choose","description","Why Choose Us Description","textarea","Dependable export supply, flexible order planning, market-ready packaging, documentation support and specification-focused quality."],
  ["home","why_choose","item_1_title","Why Choose Item 1 Heading","text","Reliable Supply"],
  ["home","why_choose","item_1_text","Why Choose Item 1 Description","textarea","Planned production and dependable export supply for wholesalers, distributors and private-label programs."],
  ["home","why_choose","item_2_title","Why Choose Item 2 Heading","text","Flexible MOQ"],
  ["home","why_choose","item_2_text","Why Choose Item 2 Description","textarea","Order quantities suited to trial launches, growing brands and established importers."],
  ["home","why_choose","item_3_title","Why Choose Item 3 Heading","text","Custom Packaging"],
  ["home","why_choose","item_3_text","Why Choose Item 3 Description","textarea","PET bottles, grinders, jars and stand-up pouches customized for your brand and target market."],
  ["home","why_choose","item_4_title","Why Choose Item 4 Heading","text","Export Support"],
  ["home","why_choose","item_4_text","Why Choose Item 4 Description","textarea","Support for product specifications, commercial documents and international shipment coordination."],
  ["home","why_choose","item_5_title","Why Choose Item 5 Heading","text","Quality Focused"],
  ["home","why_choose","item_5_text","Why Choose Item 5 Description","textarea","Specification-based packing and defined quality checks for food-grade Himalayan Pink Salt."],
  ["home","why_choose","item_6_title","Why Choose Item 6 Heading","text","Global Reach"],
  ["home","why_choose","item_6_text","Why Choose Item 6 Description","textarea","Responsive B2B support for retail, foodservice and distribution buyers across international markets."],
  ["home","collections","title","Signature Collections Heading","textarea","Product families for international buyers."],
  ["home","collections","description","Signature Collections Description","textarea","A refined collection architecture covering retail, private label, bulk, livestock, foodservice and premium market formats."],
  ["home","collections","retail_eyebrow","Retail Collection Eyebrow","text","Retail Collection"],
  ["home","collections","retail_title","Retail Collection Heading","text","Retail Packaging"],
  ["home","collections","retail_text","Retail Collection Description","textarea","Shelf-ready formats designed for grocery, gourmet, specialty retail and private-label programs."],
  ["home","collections","bulk_eyebrow","Bulk Collection Eyebrow","text","Bulk Collection"],
  ["home","collections","bulk_title","Bulk Collection Heading","text","Bulk Supply"],
  ["home","collections","bulk_text","Bulk Collection Description","textarea","Commercial formats for importers, foodservice buyers and ingredient-led supply programs."],
  ["home","collections","private_label_eyebrow","Private Label Collection Eyebrow","text","Private Label"],
  ["home","collections","private_label_title","Private Label Collection Heading","text","Custom Brand Programs"],
  ["home","collections","private_label_text","Private Label Collection Description","textarea","Packaging and brand-development workflows for buyers building a premium salt range under their own identity."],
  ["home","collections","animal_lick_eyebrow","Animal Lick Collection Eyebrow","text","Livestock Range"],
  ["home","collections","animal_lick_title","Animal Lick Collection Heading","text","Animal Lick Salt"],
  ["home","collections","animal_lick_text","Animal Lick Collection Description","textarea","A dedicated commercial category for livestock and agricultural buyers requiring trade-ready salt formats."],
  ["home","collections","foodservice_eyebrow","Foodservice Collection Eyebrow","text","Hospitality Range"],
  ["home","collections","foodservice_title","Foodservice Collection Heading","text","Foodservice Packs"],
  ["home","collections","foodservice_text","Foodservice Collection Description","textarea","Professional salt formats for chefs, restaurants, catering, hospitality and refill requirements."],
  ["home","collections","gourmet_eyebrow","Gourmet Collection Eyebrow","text","Gourmet Range"],
  ["home","collections","gourmet_title","Gourmet Collection Heading","text","Gourmet & Lifestyle"],
  ["home","collections","gourmet_text","Gourmet Collection Description","textarea","Presentation-led formats for gifting, gourmet shelves and curated premium salt collections."],
  ["home","quality","title","Quality Standards Heading","text","OUR QUALITY STANDARDS"],
  ["home","quality","description","Quality Standards Description","textarea","Certified quality you can trust."],
  ["home","export","title","Export Markets Heading","text","TRUSTED BY BUYERS IN 50+ COUNTRIES"],
  ["home","export","countries","Export Destinations Number","text","50+"],
  ["home","export","buyers","International Buyers Number","text","500+"],
  ["home","export","destinations_label","Export Destinations Label","text","Export Destinations"],
  ["home","export","buyers_label","International Buyers Label","text","International Buyers"],
  ["home","export","supply_value","Supply Capability Value","text","Bulk"],
  ["home","export","supply_label","Supply Capability Label","text","Supply Capability"],
  ["home","export","quality_value","Export Quality Value","text","100%"],
  ["home","export","quality_label","Export Quality Label","text","Export Quality Focused"],
  ["products","hero","eyebrow","Products Eyebrow","text","PRODUCTS"],
  ["products","hero","title","Products Page Heading","textarea","Himalayan Pink Salt Product Collection"],
  ["products","hero","description","Products Page Description","textarea","Export-ready Himalayan Pink Salt products available in retail packaging, grinder bottles, stand-up pouches, bulk supply and private label solutions."],
  ["products","retail","title","Retail Packaging Heading","text","RETAIL PACKAGING"],
  ["products","grinder","title","Grinder Collection Heading","text","GRINDER COLLECTION"],
  ["products","bulk","title","Bulk Packaging Heading","text","BULK SALT PACKAGING"],
  ["products","private_label","title","Private Label Solutions Heading","text","PRIVATE LABEL SOLUTIONS"],
  ["products","comparison","title","Product Comparison Heading","text","PRODUCT COMPARISON"],
  ["about","hero","eyebrow","About Eyebrow","text","ABOUT US"],
  ["about","hero","title","About Main Heading","textarea","The Origin of Purity"],
  ["about","hero","description","About Hero Description","textarea","Your sourcing partner for authentic Himalayan Pink Salt from Pakistan."],
  ["about","story","eyebrow","Who We Are Eyebrow","text","WHO WE ARE"],
  ["about","story","title","Who We Are Heading","text","Who We Are"],
  ["about","story","body_one","Who We Are Paragraph 1","textarea","The Salt Origin connects international buyers with authentic Himalayan Pink Salt sourced from Pakistan and prepared for global retail, foodservice and private-label markets."],
  ["about","story","body_two","Who We Are Paragraph 2","textarea","As an export-focused B2B supplier, we support distributors, wholesalers and brands with dependable supply, defined product specifications, market-ready packaging and responsive commercial service."],
  ["about","mission","eyebrow","Mission Eyebrow","text","OUR PURPOSE"],
  ["about","mission","title","Mission Heading","text","Our Mission"],
  ["about","mission","text","Mission Description","textarea","To deliver dependable Himalayan Pink Salt solutions with clear specifications, consistent service and long-term value for international buyers."],
  ["about","vision","eyebrow","Vision Eyebrow","text","OUR DIRECTION"],
  ["about","vision","title","Vision Heading","text","Our Vision"],
  ["about","vision","text","Vision Description","textarea","To become a trusted international partner for Himalayan Pink Salt, private-label development and export-ready product programs."],
  ["about","founder","eyebrow","Founder Message Eyebrow","text","FOUNDER'S MESSAGE"],
  ["about","founder","title","Founder Message Heading","textarea","Meet the Vision Behind The Salt Origin"],
  ["about","founder","message","Founder Message","textarea","We started The Salt Origin with a simple purpose: to close the gap between the source of Himalayan Pink Salt and serious international buyers. Our focus is not only to supply a product, but to build trust through clear communication, dependable quality and responsible export support."],
  ["about","founder","name","Founder Name","text","Muhammad Hamza Khan"],
  ["about","founder","role","Founder Role","textarea","CEO & Founder, The Salt Origin & Khan & Co."],
  ["private-label","hero","eyebrow","Private Label Eyebrow","text","PRIVATE LABEL MANUFACTURER"],
  ["private-label","hero","title","Private Label Main Heading","textarea","Launch Your Own Himalayan Pink Salt Brand"],
  ["certifications","hero","eyebrow","Certifications Eyebrow","text","QUALITY & COMPLIANCE"],
  ["certifications","hero","title","Certifications Main Heading","textarea","Certified Quality You Can Trust"],
  ["contact","hero","eyebrow","Contact Eyebrow","text","CONTACT"],
  ["contact","hero","title","Contact Main Heading","textarea","Let’s Discuss Your Requirements"],
  ["contact","hero","description","Contact Hero Description","textarea","Tell us what you need, where you sell and how you want the product packed. Our export team will respond with the right product, packaging and quotation path."],
  ["contact","hero","quote_button","Contact Quote Button","text","Request Quote"],
  ["contact","hero","whatsapp_button","Contact WhatsApp Button","text","WhatsApp Us"],
  ["contact","snapshot","eyebrow","Direct Contact Eyebrow","text","DIRECT CONTACT"],
  ["contact","snapshot","title","Direct Contact Heading","textarea","Speak With Our Export Team"],
  ["contact","snapshot","description","Direct Contact Description","textarea","Use the channel that is easiest for you. Commercial inquiries are reviewed by our B2B team."],
  ["contact","snapshot","email_label","Email Label","text","Email"],
  ["contact","snapshot","phone_label","Phone Label","text","Phone / WhatsApp"],
  ["contact","snapshot","location_label","Location Label","text","Location"],
  ["contact","snapshot","hours_label","Business Hours Label","text","Business Hours"],
  ["contact","snapshot","hours_value","Business Hours Value","textarea","Mon–Sat · 09:00 AM–06:00 PM"],
  ["contact","form","eyebrow","Contact Form Eyebrow","text","START YOUR INQUIRY"],
  ["contact","form","title","Contact Form Heading","textarea","Build the Right Salt Program for Your Market"],
  ["contact","form","description","Contact Form Description","textarea","Share your target market, preferred packaging, estimated quantity and timeline. The more detail you provide, the more relevant our response can be."],
  ["contact","form","benefit_one_title","Contact Benefit 1 Heading","text","Commercially Relevant Reply"],
  ["contact","form","benefit_one_text","Contact Benefit 1 Text","textarea","Product and packaging guidance matched to your inquiry."],
  ["contact","form","benefit_two_title","Contact Benefit 2 Heading","text","Export-Focused Support"],
  ["contact","form","benefit_two_text","Contact Benefit 2 Text","textarea","Documentation and shipment considerations for international buyers."],
  ["contact","form","benefit_three_title","Contact Benefit 3 Heading","text","Private Label Ready"],
  ["contact","form","benefit_three_text","Contact Benefit 3 Text","textarea","Custom branding and retail packaging options for qualified projects."],
  ["contact","help","eyebrow","Help Section Eyebrow","text","HOW WE CAN HELP"],
  ["contact","help","title","Help Section Heading","textarea","Support Across the Buyer Journey"],
  ["contact","help","private_label_title","Private Label Help Heading","text","Private Label Development"],
  ["contact","help","private_label_text","Private Label Help Text","textarea","Branding, labels and market-ready packaging support."],
  ["contact","help","bulk_orders_title","Bulk Orders Help Heading","text","Bulk Orders"],
  ["contact","help","bulk_orders_text","Bulk Orders Help Text","textarea","Commercial supply planning for distributors and wholesalers."],
  ["contact","help","specifications_title","Specifications Help Heading","text","Product Specifications"],
  ["contact","help","specifications_text","Specifications Help Text","textarea","Grades, grain sizes, packaging and technical product details."],
  ["contact","help","documents_title","Export Documents Help Heading","text","Export Documentation"],
  ["contact","help","documents_text","Export Documents Help Text","textarea","Commercial and shipment documentation support for international trade."],
  ["contact","help","samples_title","Samples Help Heading","text","Sample Requests"],
  ["contact","help","samples_text","Samples Help Text","textarea","Product and packaging samples for qualified buyer projects."],
  ["contact","help","quality_title","Quality Help Heading","text","Quality & Compliance"],
  ["contact","help","quality_text","Quality Help Text","textarea","Certification, COA and compliance information where available."],

  ["faqs","hero","eyebrow","FAQ Eyebrow","text","BUYER SUPPORT"],
  ["faqs","hero","title","FAQ Page Heading","textarea","Frequently Asked Questions"],
  ["faqs","hero","description","FAQ Page Description","textarea","Clear answers for importers, distributors, wholesalers and private-label buyers."],
  ["privacy-policy","content","title","Privacy Policy Heading","text","Privacy Policy"],
  ["privacy-policy","content","introduction","Privacy Policy Introduction","textarea",""],
  ["privacy-policy","content","body","Privacy Policy Content","textarea",""],
  ["terms-and-conditions","content","title","Terms & Conditions Heading","text","Terms & Conditions"],
  ["terms-and-conditions","content","introduction","Terms & Conditions Introduction","textarea",""],
  ["terms-and-conditions","content","body","Terms & Conditions Content","textarea",""],
  ["global","footer","description","Footer Description","textarea","Premium Himalayan Pink Salt supplier for global markets. Purity from the Himalayas, trusted worldwide."],
].map((row, index) => {
  const [page_slug, section_slug, field_key, field_label, field_type, default_value] = row as [string,string,string,string,"text"|"textarea",string];
  return { page_slug, section_slug, field_key, field_label, field_type, default_value, display_order: index + 1 };
});
