-- THE SALT ORIGIN ENTERPRISE CMS V10
-- Run in Supabase SQL Editor after taking a database backup.

create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null,
  label text not null,
  url text not null default '',
  icon_key text,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists social_links_platform_unique on public.social_links(platform);

insert into public.social_links(platform,label,url,icon_key,enabled,display_order) values
('facebook','Facebook','','facebook',true,1),
('instagram','Instagram','','instagram',true,2),
('linkedin','LinkedIn','','linkedin',true,3),
('tiktok','TikTok','','tiktok',true,4),
('youtube','YouTube','','youtube',true,5),
('pinterest','Pinterest','','pinterest',true,6),
('x','X / Twitter','','x',true,7)
on conflict (platform) do nothing;

alter table public.social_links enable row level security;
drop policy if exists "Authenticated users manage social links" on public.social_links;
create policy "Authenticated users manage social links"
on public.social_links for all to authenticated using (true) with check (true);

create table if not exists public.social_scheduled_posts (
  id uuid primary key default gen_random_uuid(),
  caption text not null,
  hashtags text not null default '',
  keywords text not null default '',
  image_url text not null default '',
  platforms text[] not null default '{}',
  scheduled_at timestamptz not null,
  status text not null default 'scheduled',
  platform_results jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.social_scheduled_posts enable row level security;
drop policy if exists "Authenticated users manage social schedule" on public.social_scheduled_posts;
create policy "Authenticated users manage social schedule"
on public.social_scheduled_posts for all to authenticated using (true) with check (true);

create index if not exists social_scheduled_posts_due_idx
on public.social_scheduled_posts(status, scheduled_at);

create table if not exists public.blog_automation_settings (
  id bigint generated by default as identity primary key,
  enabled boolean not null default false,
  frequency text not null default 'daily',
  approval_required boolean not null default true,
  default_language text not null default 'en',
  topic_focus text not null default 'Himalayan pink salt sourcing, private-label packaging, retail trends, food-industry applications and export guidance',
  updated_at timestamptz not null default now()
);

alter table public.blog_automation_settings
  add column if not exists default_language text not null default 'en',
  add column if not exists topic_focus text not null default 'Himalayan pink salt sourcing, private-label packaging, retail trends, food-industry applications and export guidance',
  add column if not exists updated_at timestamptz not null default now();

insert into public.blog_automation_settings(enabled,frequency,approval_required,default_language,topic_focus)
select false,'daily',true,'en','Himalayan pink salt sourcing, private-label packaging, retail trends, food-industry applications and export guidance'
where not exists(select 1 from public.blog_automation_settings);

alter table public.blog_automation_settings enable row level security;
drop policy if exists "Authenticated users manage blog automation" on public.blog_automation_settings;
create policy "Authenticated users manage blog automation"
on public.blog_automation_settings for all to authenticated using (true) with check (true);

-- Recommended: keep approval_required=true so AI-created posts remain drafts.
