-- THE SALT ORIGIN — LIVE ENTERPRISE B2B CMS
-- Schema-only migration for the existing website and Supabase project.
-- Safe to re-run. This file inserts no leads, metrics, tasks, quotations, shipments,
-- companies, contacts, activities, products, certifications or other placeholder records.

create extension if not exists pgcrypto;

-- Core website tables are created only when absent. Existing production rows are preserved.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  email text,
  phone text,
  company text,
  country text,
  product text,
  message text,
  status text default 'new',
  notes text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text,
  name text,
  slug text unique,
  subtitle text,
  category text,
  description text,
  short_description text,
  image text,
  gallery jsonb not null default '[]'::jsonb,
  status text default 'draft'
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  slug text unique not null,
  description text,
  status text default 'draft'
);

create table if not exists public.seo_settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  page_slug text unique not null,
  meta_title text,
  meta_description text,
  keywords text,
  canonical_url text,
  og_title text,
  og_description text,
  og_image text
);

create table if not exists public.page_content (
  id bigint generated by default as identity primary key,
  page_slug text unique not null,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.media_library (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  file_name text not null,
  file_url text not null,
  file_type text,
  alt_text text,
  folder text default 'general',
  file_size bigint
);

alter table public.media_library add column if not exists storage_bucket text not null default 'cms-media';
alter table public.media_library add column if not exists storage_path text;

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  title text not null,
  slug text unique not null,
  excerpt text,
  content text,
  featured_image text,
  status text default 'draft',
  seo_title text,
  seo_description text
);

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  site_name text,
  contact_email text,
  whatsapp_number text,
  address text,
  footer_text text,
  favicon_url text,
  app_icon_url text,
  notification_email text,
  pwa_enabled boolean default true
);

create table if not exists public.cms_roles (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  description text,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.cms_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role_name text default 'super_admin',
  enabled boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_languages (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cms_text_entries (
  id uuid primary key default gen_random_uuid(),
  page_slug text not null,
  section_slug text not null,
  field_key text not null,
  field_label text,
  field_type text default 'text',
  default_value text,
  display_order integer not null default 0,
  style_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(page_slug, section_slug, field_key)
);

create table if not exists public.cms_text_translations (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.cms_text_entries(id) on delete cascade,
  language_code text not null,
  value text,
  updated_at timestamptz not null default now(),
  unique(entry_id, language_code)
);

create table if not exists public.cms_image_slots (
  id uuid primary key default gen_random_uuid(),
  page_slug text not null,
  section_slug text not null,
  slot_key text not null,
  slot_label text,
  current_url text,
  default_url text,
  alt_text text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique(page_slug, section_slug, slot_key)
);

create table if not exists public.marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  campaign_type text not null default 'campaign',
  subject text,
  content text,
  audience_filter jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  scheduled_at timestamptz,
  sent_at timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_scheduled_posts (
  id uuid primary key default gen_random_uuid(),
  caption text not null default '',
  hashtags text not null default '',
  keywords text not null default '',
  image_url text not null default '',
  platforms text[] not null default '{}',
  scheduled_at timestamptz,
  status text not null default 'draft',
  platform_results jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_accounts (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid references auth.users(id) on delete set null,
  company_name text not null,
  contact_name text,
  email text,
  phone text,
  country text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.customer_shipments (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customer_accounts(id) on delete cascade,
  reference_number text unique not null,
  shipment_type text not null default 'container',
  carrier_type text not null default 'custom',
  carrier_name text,
  tracking_number text,
  bl_number text,
  container_number text,
  vessel_name text,
  voyage_number text,
  origin text,
  destination text,
  etd timestamptz,
  eta timestamptz,
  current_status text not null default 'booked',
  tracking_url text,
  milestones jsonb not null default '[]'::jsonb,
  documents jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_letterheads (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  company_name text not null,
  logo_url text,
  address text,
  email text,
  phone text,
  website text,
  bank_details text,
  signature_url text,
  stamp_url text,
  footer_text text,
  is_default boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null default 'quotation',
  document_number text unique,
  status text not null default 'Draft',
  currency text not null default 'USD',
  issue_date date default current_date,
  valid_until date,
  buyer_name text,
  buyer_company text,
  buyer_email text,
  buyer_phone text,
  buyer_address text,
  buyer_country text,
  incoterm text,
  payment_terms text,
  delivery_terms text,
  origin_country text default 'Pakistan',
  destination_port text,
  freight numeric default 0,
  insurance numeric default 0,
  discount numeric default 0,
  tax_rate numeric default 0,
  subtotal numeric default 0,
  tax_amount numeric default 0,
  grand_total numeric default 0,
  notes text,
  items jsonb not null default '[]'::jsonb,
  letterhead_id uuid references public.document_letterheads(id) on delete set null,
  inquiry_id bigint references public.inquiries(id) on delete set null,
  parent_document_id uuid references public.business_documents(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- COMPANIES AND CONTACTS
-- -----------------------------------------------------------------------------
create table if not exists public.b2b_companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  country text,
  company_type text not null default 'Prospect',
  industry text,
  website text,
  primary_contact_name text,
  primary_contact_email text,
  products_of_interest text[] not null default '{}',
  estimated_annual_volume text,
  tier text not null default 'New',
  relationship_status text not null default 'Prospect',
  preferred_buyer boolean not null default false,
  repeat_client boolean not null default false,
  assigned_manager uuid references auth.users(id) on delete set null,
  last_activity_at timestamptz,
  next_follow_up_at timestamptz,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists b2b_companies_name_idx on public.b2b_companies(lower(name));
create index if not exists b2b_companies_country_idx on public.b2b_companies(country);
create index if not exists b2b_companies_status_idx on public.b2b_companies(relationship_status);
drop trigger if exists trg_b2b_companies_updated_at on public.b2b_companies;
create trigger trg_b2b_companies_updated_at before update on public.b2b_companies for each row execute function public.set_updated_at();

create table if not exists public.b2b_contacts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid references public.b2b_companies(id) on delete set null,
  name text not null,
  job_title text,
  country text,
  email text,
  phone_whatsapp text,
  lifecycle text not null default 'New Contact',
  source text,
  product_interest text,
  owner_id uuid references auth.users(id) on delete set null,
  last_contact_at timestamptz,
  next_follow_up_at timestamptz,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists b2b_contacts_email_unique on public.b2b_contacts(lower(email)) where email is not null and btrim(email) <> '';
create index if not exists b2b_contacts_company_idx on public.b2b_contacts(company_id);
create index if not exists b2b_contacts_lifecycle_idx on public.b2b_contacts(lifecycle);
drop trigger if exists trg_b2b_contacts_updated_at on public.b2b_contacts;
create trigger trg_b2b_contacts_updated_at before update on public.b2b_contacts for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- LEADS — EXISTING WEBSITE INQUIRIES BECOME THE LIVE CRM SOURCE
-- -----------------------------------------------------------------------------
alter table if exists public.inquiries add column if not exists company_id uuid references public.b2b_companies(id) on delete set null;
alter table if exists public.inquiries add column if not exists contact_id uuid references public.b2b_contacts(id) on delete set null;
alter table if exists public.inquiries add column if not exists buyer_type text;
alter table if exists public.inquiries add column if not exists packaging_requirement text;
alter table if exists public.inquiries add column if not exists estimated_volume text;
alter table if exists public.inquiries add column if not exists lead_source text default 'Website Inquiry';
alter table if exists public.inquiries add column if not exists lifecycle_stage text default 'New Inquiry';
alter table if exists public.inquiries add column if not exists lead_temperature text default 'New';
alter table if exists public.inquiries add column if not exists assigned_manager uuid references auth.users(id) on delete set null;
alter table if exists public.inquiries add column if not exists last_contact_at timestamptz;
alter table if exists public.inquiries add column if not exists next_follow_up_at timestamptz;
alter table if exists public.inquiries add column if not exists won_at timestamptz;
alter table if exists public.inquiries add column if not exists lost_at timestamptz;
alter table if exists public.inquiries add column if not exists lost_reason text;
alter table if exists public.inquiries add column if not exists form_name text;
alter table if exists public.inquiries add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table if exists public.inquiries add column if not exists updated_at timestamptz not null default now();
create index if not exists inquiries_lifecycle_idx on public.inquiries(lifecycle_stage);
create index if not exists inquiries_created_idx on public.inquiries(created_at desc);
create index if not exists inquiries_followup_idx on public.inquiries(next_follow_up_at) where next_follow_up_at is not null;
drop trigger if exists trg_inquiries_updated_at on public.inquiries;
create trigger trg_inquiries_updated_at before update on public.inquiries for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- CLIENTS — EXTEND THE EXISTING CLIENT ACCOUNT TABLE
-- -----------------------------------------------------------------------------
alter table if exists public.customer_accounts add column if not exists industry text;
alter table if exists public.customer_accounts add column if not exists website text;
alter table if exists public.customer_accounts add column if not exists segment text default 'New Client';
alter table if exists public.customer_accounts add column if not exists tier text default 'New';
alter table if exists public.customer_accounts add column if not exists products text[] not null default '{}';
alter table if exists public.customer_accounts add column if not exists last_quotation text;
alter table if exists public.customer_accounts add column if not exists last_shipment text;
alter table if exists public.customer_accounts add column if not exists last_contact_at timestamptz;
alter table if exists public.customer_accounts add column if not exists assigned_manager uuid references auth.users(id) on delete set null;
alter table if exists public.customer_accounts add column if not exists repeat_client boolean not null default false;
alter table if exists public.customer_accounts add column if not exists preferred_buyer boolean not null default false;
alter table if exists public.customer_accounts add column if not exists notes text;
alter table if exists public.customer_accounts add column if not exists updated_at timestamptz not null default now();
drop trigger if exists trg_customer_accounts_updated_at on public.customer_accounts;
create trigger trg_customer_accounts_updated_at before update on public.customer_accounts for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- QUOTATIONS AND EXPORT DOCUMENTS — EXTEND EXISTING DOCUMENT TABLE
-- -----------------------------------------------------------------------------
alter table if exists public.business_documents add column if not exists contact_id uuid references public.b2b_contacts(id) on delete set null;
alter table if exists public.business_documents add column if not exists company_id uuid references public.b2b_companies(id) on delete set null;
alter table if exists public.business_documents add column if not exists port_of_loading text;
alter table if exists public.business_documents add column if not exists port_of_discharge text;
alter table if exists public.business_documents add column if not exists shipment_method text;
alter table if exists public.business_documents add column if not exists total_quantity numeric default 0;
alter table if exists public.business_documents add column if not exists quantity_unit text;
alter table if exists public.business_documents add column if not exists sent_at timestamptz;
alter table if exists public.business_documents add column if not exists delivered_at timestamptz;
alter table if exists public.business_documents add column if not exists viewed_at timestamptz;
alter table if exists public.business_documents add column if not exists accepted_at timestamptz;
alter table if exists public.business_documents add column if not exists rejected_at timestamptz;
alter table if exists public.business_documents add column if not exists next_follow_up_at timestamptz;
alter table if exists public.business_documents add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table if exists public.business_documents add column if not exists email_message text;
alter table if exists public.business_documents add column if not exists whatsapp_message text;
alter table if exists public.business_documents add column if not exists revision_number integer not null default 0;
create index if not exists business_documents_status_idx on public.business_documents(status, document_type);
create index if not exists business_documents_followup_idx on public.business_documents(next_follow_up_at) where next_follow_up_at is not null;

-- -----------------------------------------------------------------------------
-- PRODUCTION AND SHIPMENTS — EXTEND EXISTING SHIPMENT TABLE
-- -----------------------------------------------------------------------------
alter table if exists public.customer_shipments add column if not exists company_id uuid references public.b2b_companies(id) on delete set null;
alter table if exists public.customer_shipments add column if not exists client_name text;
alter table if exists public.customer_shipments add column if not exists country text;
alter table if exists public.customer_shipments add column if not exists product text;
alter table if exists public.customer_shipments add column if not exists quantity text;
alter table if exists public.customer_shipments add column if not exists incoterm text;
alter table if exists public.customer_shipments add column if not exists freight_mode text;
alter table if exists public.customer_shipments add column if not exists container_type text;
alter table if exists public.customer_shipments add column if not exists current_stage text default 'Contract Confirmed';
alter table if exists public.customer_shipments add column if not exists completion integer not null default 0;
alter table if exists public.customer_shipments add column if not exists document_status text default 'Pending';
alter table if exists public.customer_shipments add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table if exists public.customer_shipments add column if not exists delay_reason text;
alter table if exists public.customer_shipments add column if not exists recent_update text;
alter table if exists public.customer_shipments add column if not exists status text default 'Active';
create index if not exists customer_shipments_stage_idx on public.customer_shipments(current_stage, status);
create index if not exists customer_shipments_eta_idx on public.customer_shipments(eta);

-- -----------------------------------------------------------------------------
-- FOLLOW-UPS AND ACTIVITY
-- -----------------------------------------------------------------------------
create table if not exists public.b2b_followups (
  id uuid primary key default gen_random_uuid(),
  inquiry_id bigint references public.inquiries(id) on delete cascade,
  company_id uuid references public.b2b_companies(id) on delete cascade,
  contact_id uuid references public.b2b_contacts(id) on delete cascade,
  document_id uuid references public.business_documents(id) on delete cascade,
  title text not null,
  due_at timestamptz not null,
  priority text not null default 'Normal',
  status text not null default 'Open',
  assigned_to uuid references auth.users(id) on delete set null,
  notes text,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists b2b_followups_due_idx on public.b2b_followups(status, due_at);
drop trigger if exists trg_b2b_followups_updated_at on public.b2b_followups;
create trigger trg_b2b_followups_updated_at before update on public.b2b_followups for each row execute function public.set_updated_at();

create table if not exists public.b2b_activities (
  id uuid primary key default gen_random_uuid(),
  activity_type text not null,
  module text not null,
  record_id text,
  title text not null,
  description text,
  company_name text,
  country text,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists b2b_activities_created_idx on public.b2b_activities(created_at desc);
create index if not exists b2b_activities_module_idx on public.b2b_activities(module, created_at desc);

-- -----------------------------------------------------------------------------
-- APPROVAL CENTER
-- -----------------------------------------------------------------------------
create table if not exists public.approval_items (
  id uuid primary key default gen_random_uuid(),
  content_type text not null,
  record_id text,
  title text not null,
  creator_name text,
  creator_id uuid references auth.users(id) on delete set null,
  ai_agent text,
  status text not null default 'Draft',
  preview_url text,
  change_summary text,
  comments jsonb not null default '[]'::jsonb,
  reviewer_id uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  scheduled_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists approval_items_status_idx on public.approval_items(status, created_at desc);
drop trigger if exists trg_approval_items_updated_at on public.approval_items;
create trigger trg_approval_items_updated_at before update on public.approval_items for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- CERTIFICATIONS
-- -----------------------------------------------------------------------------
create table if not exists public.certifications (
  id uuid primary key default gen_random_uuid(),
  document_name text not null,
  category text not null,
  issuing_authority text,
  certificate_number text,
  issue_date date,
  expiry_date date,
  applicable_products text[] not null default '{}',
  applicable_markets text[] not null default '{}',
  visibility text not null default 'Private',
  file_url text,
  thumbnail_url text,
  expiry_reminder_days integer not null default 60,
  status text not null default 'Draft',
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists certifications_expiry_idx on public.certifications(expiry_date);
drop trigger if exists trg_certifications_updated_at on public.certifications;
create trigger trg_certifications_updated_at before update on public.certifications for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- FORMS
-- -----------------------------------------------------------------------------
create table if not exists public.website_forms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  form_type text not null default 'General Inquiry',
  website_placement text,
  fields jsonb not null default '[]'::jsonb,
  status text not null default 'Draft',
  assigned_owner uuid references auth.users(id) on delete set null,
  notifications jsonb not null default '{}'::jsonb,
  submission_count integer not null default 0,
  last_submission_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_website_forms_updated_at on public.website_forms;
create trigger trg_website_forms_updated_at before update on public.website_forms for each row execute function public.set_updated_at();

create table if not exists public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  form_id uuid references public.website_forms(id) on delete set null,
  inquiry_id bigint references public.inquiries(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  source_page text,
  created_at timestamptz not null default now()
);
create index if not exists form_submissions_form_idx on public.form_submissions(form_id, created_at desc);

-- -----------------------------------------------------------------------------
-- SAMPLE REQUESTS
-- -----------------------------------------------------------------------------
create table if not exists public.sample_requests (
  id uuid primary key default gen_random_uuid(),
  request_number text unique,
  inquiry_id bigint references public.inquiries(id) on delete set null,
  company_id uuid references public.b2b_companies(id) on delete set null,
  company_name text,
  country text,
  product_samples text,
  packaging_sample text,
  request_date date not null default current_date,
  courier text,
  tracking_number text,
  cost_responsibility text,
  status text not null default 'Requested',
  follow_up_date date,
  owner_id uuid references auth.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create sequence if not exists public.sample_request_seq start 1001;
create or replace function public.assign_sample_request_number()
returns trigger language plpgsql as $$
begin
  if new.request_number is null or btrim(new.request_number) = '' then
    new.request_number := 'SR-' || to_char(current_date,'YYYY') || '-' || lpad(nextval('public.sample_request_seq')::text,5,'0');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_assign_sample_request_number on public.sample_requests;
create trigger trg_assign_sample_request_number before insert on public.sample_requests for each row execute function public.assign_sample_request_number();
drop trigger if exists trg_sample_requests_updated_at on public.sample_requests;
create trigger trg_sample_requests_updated_at before update on public.sample_requests for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- OUTREACH / FAQ INTELLIGENCE / GEO / AI AGENTS / SAVED REPORTS
-- -----------------------------------------------------------------------------
create table if not exists public.outreach_opportunities (
  id uuid primary key default gen_random_uuid(),
  website text not null,
  country text,
  opportunity_type text,
  authority_score integer,
  relevance_score integer,
  contact_person text,
  contact_email text,
  status text not null default 'Identified',
  last_contact_at timestamptz,
  follow_up_date date,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_outreach_updated_at on public.outreach_opportunities;
create trigger trg_outreach_updated_at before update on public.outreach_opportunities for each row execute function public.set_updated_at();

create table if not exists public.faq_research_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  source text,
  source_mode text not null default 'Connection Required',
  demand_score integer,
  target_country text,
  related_keyword text,
  recommended_category text,
  ai_answer text,
  answer_length integer,
  schema_preview jsonb not null default '{}'::jsonb,
  internal_links jsonb not null default '[]'::jsonb,
  reference_notes text,
  status text not null default 'New Suggestion',
  approved_at timestamptz,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_faq_research_updated_at on public.faq_research_questions;
create trigger trg_faq_research_updated_at before update on public.faq_research_questions for each row execute function public.set_updated_at();

create table if not exists public.geo_audits (
  id uuid primary key default gen_random_uuid(),
  page_path text not null,
  page_title text,
  ai_visibility_score integer,
  answer_readiness_score integer,
  entity_consistency_score integer,
  citation_opportunities integer,
  status text not null default 'Needs Review',
  recommendations jsonb not null default '[]'::jsonb,
  llms_txt_excerpt text,
  last_audited_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_geo_audits_updated_at on public.geo_audits;
create trigger trg_geo_audits_updated_at before update on public.geo_audits for each row execute function public.set_updated_at();

create table if not exists public.ai_agents (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  purpose text,
  status text not null default 'Paused',
  last_run_at timestamptz,
  tasks_completed integer not null default 0,
  pending_approvals integer not null default 0,
  settings jsonb not null default '{}'::jsonb,
  last_activity text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_ai_agents_updated_at on public.ai_agents;
create trigger trg_ai_agents_updated_at before update on public.ai_agents for each row execute function public.set_updated_at();

create table if not exists public.saved_reports (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  report_type text not null,
  date_from date,
  date_to date,
  country_filter text,
  owner_filter uuid references auth.users(id) on delete set null,
  filters jsonb not null default '{}'::jsonb,
  status text not null default 'Ready',
  generated_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_saved_reports_updated_at on public.saved_reports;
create trigger trg_saved_reports_updated_at before update on public.saved_reports for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- MARKETING / SOCIAL / BLOG APPROVAL FIELDS
-- -----------------------------------------------------------------------------
alter table if exists public.marketing_campaigns add column if not exists objective text;
alter table if exists public.marketing_campaigns add column if not exists target_countries text[] not null default '{}';
alter table if exists public.marketing_campaigns add column if not exists target_audience text;
alter table if exists public.marketing_campaigns add column if not exists channels text[] not null default '{}';
alter table if exists public.marketing_campaigns add column if not exists landing_page text;
alter table if exists public.marketing_campaigns add column if not exists leads_generated integer not null default 0;
alter table if exists public.marketing_campaigns add column if not exists owner_id uuid references auth.users(id) on delete set null;

alter table if exists public.social_scheduled_posts add column if not exists title text;
alter table if exists public.social_scheduled_posts add column if not exists campaign_id uuid references public.marketing_campaigns(id) on delete set null;
alter table if exists public.social_scheduled_posts add column if not exists platform_content jsonb not null default '{}'::jsonb;
alter table if exists public.social_scheduled_posts add column if not exists platform_images jsonb not null default '{}'::jsonb;
alter table if exists public.social_scheduled_posts add column if not exists approval_status text not null default 'Draft';
alter table if exists public.social_scheduled_posts add column if not exists reviewer_id uuid references auth.users(id) on delete set null;
alter table if exists public.social_scheduled_posts add column if not exists approved_at timestamptz;

alter table if exists public.blog_posts add column if not exists target_country text;
alter table if exists public.blog_posts add column if not exists primary_keyword text;
alter table if exists public.blog_posts add column if not exists geo_score integer not null default 0;
alter table if exists public.blog_posts add column if not exists approval_status text not null default 'Draft';
alter table if exists public.blog_posts add column if not exists reviewer_id uuid references auth.users(id) on delete set null;
alter table if exists public.blog_posts add column if not exists approved_at timestamptz;

-- -----------------------------------------------------------------------------
-- LIVE ACTIVITY TRIGGERS
-- -----------------------------------------------------------------------------
create or replace function public.log_inquiry_activity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('created','Leads',new.id::text,'New inquiry received',coalesce(new.name,'Website visitor') || ' submitted an inquiry',new.company,new.country,jsonb_build_object('email',new.email,'product',new.product,'source',coalesce(new.lead_source,'Website Inquiry')));
  elsif tg_op = 'UPDATE' and (old.lifecycle_stage is distinct from new.lifecycle_stage or old.status is distinct from new.status) then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('status_changed','Leads',new.id::text,'Lead status updated',coalesce(old.lifecycle_stage,old.status,'New') || ' → ' || coalesce(new.lifecycle_stage,new.status,'New'),new.company,new.country,jsonb_build_object('email',new.email,'product',new.product));
  end if;
  return new;
end;
$$;
drop trigger if exists trg_log_inquiry_activity on public.inquiries;
create trigger trg_log_inquiry_activity after insert or update on public.inquiries for each row execute function public.log_inquiry_activity();

create or replace function public.log_document_activity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('created','Quotations',new.id::text,coalesce(new.document_number,'Document') || ' created',initcap(replace(new.document_type,'_',' ')),new.buyer_company,new.buyer_country,jsonb_build_object('status',new.status,'grand_total',new.grand_total,'currency',new.currency));
  elsif tg_op = 'UPDATE' and old.status is distinct from new.status then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('status_changed','Quotations',new.id::text,coalesce(new.document_number,'Document') || ' status updated',coalesce(old.status,'Draft') || ' → ' || coalesce(new.status,'Draft'),new.buyer_company,new.buyer_country,jsonb_build_object('status',new.status));
  end if;
  return new;
end;
$$;
drop trigger if exists trg_log_document_activity on public.business_documents;
create trigger trg_log_document_activity after insert or update on public.business_documents for each row execute function public.log_document_activity();

create or replace function public.log_shipment_activity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('created','Shipments',new.id::text,coalesce(new.reference_number,'Shipment') || ' created',coalesce(new.current_stage,new.current_status,'Booked'),new.client_name,new.country,jsonb_build_object('completion',new.completion,'eta',new.eta));
  elsif tg_op = 'UPDATE' and (old.current_stage is distinct from new.current_stage or old.current_status is distinct from new.current_status) then
    insert into public.b2b_activities(activity_type,module,record_id,title,description,company_name,country,metadata)
    values('status_changed','Shipments',new.id::text,coalesce(new.reference_number,'Shipment') || ' updated',coalesce(new.current_stage,new.current_status,'Booked'),new.client_name,new.country,jsonb_build_object('completion',new.completion,'eta',new.eta));
  end if;
  return new;
end;
$$;
drop trigger if exists trg_log_shipment_activity on public.customer_shipments;
create trigger trg_log_shipment_activity after insert or update on public.customer_shipments for each row execute function public.log_shipment_activity();

-- -----------------------------------------------------------------------------
-- ROW LEVEL SECURITY — AUTHENTICATED CMS USERS ONLY
-- -----------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'b2b_companies','b2b_contacts','b2b_followups','b2b_activities','approval_items',
    'certifications','website_forms','form_submissions','sample_requests','outreach_opportunities',
    'faq_research_questions','geo_audits','ai_agents','saved_reports'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated manage %s" on public.%I', t, t);
    execute format('create policy "authenticated manage %s" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

-- Ensure authenticated CMS users can manage live operational tables.
do $$
declare t text;
begin
  foreach t in array array['inquiries','business_documents','customer_accounts','customer_shipments','marketing_campaigns','social_scheduled_posts','blog_posts'] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists "enterprise cms authenticated manage" on public.%I', t);
      execute format('create policy "enterprise cms authenticated manage" on public.%I for all to authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;

-- Keep public website form submission permissions intact.
-- Existing website routes use the service role server-side, so no public select policy is added.

-- COMPETITOR INTELLIGENCE
create table if not exists public.competitor_profiles (
  id uuid primary key default gen_random_uuid(),
  domain text not null unique,
  company_name text,
  country text,
  market_focus text,
  estimated_visibility numeric,
  top_keywords jsonb not null default '[]'::jsonb,
  new_pages integer not null default 0,
  new_blogs integer not null default 0,
  content_gaps jsonb not null default '[]'::jsonb,
  backlink_gaps jsonb not null default '[]'::jsonb,
  status text not null default 'Active',
  last_checked_at timestamptz,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_competitor_profiles_updated_at on public.competitor_profiles;
create trigger trg_competitor_profiles_updated_at before update on public.competitor_profiles for each row execute function public.set_updated_at();
alter table public.competitor_profiles enable row level security;
drop policy if exists "authenticated manage competitor_profiles" on public.competitor_profiles;
create policy "authenticated manage competitor_profiles" on public.competitor_profiles for all to authenticated using (true) with check (true);

-- =============================================================================
-- FINAL FUNCTIONAL MODULES REQUIRED BY THE NEW CMS
-- =============================================================================

-- Compatibility fields and public website support tables used by the preserved production website.
-- These statements never overwrite existing content.
alter table public.site_settings add column if not exists brand_json jsonb not null default '{}'::jsonb;
alter table public.site_settings add column if not exists config_json jsonb not null default '{}'::jsonb;
alter table public.site_settings add column if not exists updated_at timestamptz not null default now();

alter table public.categories add column if not exists subtitle text;
alter table public.categories add column if not exists image text;

alter table public.cms_languages add column if not exists native_name text;
alter table public.cms_languages add column if not exists direction text not null default 'ltr';
alter table public.cms_languages add column if not exists enabled boolean not null default true;
alter table public.cms_languages add column if not exists display_order integer not null default 0;

alter table public.inquiries add column if not exists whatsapp text;
alter table public.inquiries add column if not exists quantity text;
alter table public.inquiries add column if not exists buyer_type text;
alter table public.inquiries add column if not exists packaging_requirement text;
alter table public.inquiries add column if not exists estimated_volume text;
alter table public.inquiries add column if not exists lead_source text;
alter table public.inquiries add column if not exists lifecycle_stage text;
alter table public.inquiries add column if not exists lead_temperature text;
alter table public.inquiries add column if not exists last_contact_at timestamptz;
alter table public.inquiries add column if not exists next_follow_up_at timestamptz;
alter table public.inquiries add column if not exists assigned_manager text;
alter table public.inquiries add column if not exists form_name text;
alter table public.inquiries add column if not exists source_page text;
alter table public.inquiries add column if not exists updated_at timestamptz not null default now();

create table if not exists public.homepage (
  id bigint generated by default as identity primary key,
  hero_title text,
  hero_description text,
  hero_image text,
  private_label_title text,
  private_label_description text,
  export_countries text,
  buyers_count text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.homepage add column if not exists hero_title text;
alter table public.homepage add column if not exists hero_description text;
alter table public.homepage add column if not exists hero_image text;
alter table public.homepage add column if not exists private_label_title text;
alter table public.homepage add column if not exists private_label_description text;
alter table public.homepage add column if not exists export_countries text;
alter table public.homepage add column if not exists buyers_count text;
alter table public.homepage add column if not exists updated_at timestamptz not null default now();

create table if not exists public.cms_faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null default '',
  category text,
  status text not null default 'draft',
  display_order integer not null default 0,
  source text,
  target_country text,
  related_keyword text,
  demand_score numeric,
  schema_json jsonb not null default '{}'::jsonb,
  internal_links jsonb not null default '[]'::jsonb,
  reference_notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.cms_faqs add column if not exists source text;
alter table public.cms_faqs add column if not exists target_country text;
alter table public.cms_faqs add column if not exists related_keyword text;
alter table public.cms_faqs add column if not exists demand_score numeric;
alter table public.cms_faqs add column if not exists schema_json jsonb not null default '{}'::jsonb;
alter table public.cms_faqs add column if not exists internal_links jsonb not null default '[]'::jsonb;
alter table public.cms_faqs add column if not exists reference_notes text;
alter table public.cms_faqs add column if not exists display_order integer not null default 0;
alter table public.cms_faqs add column if not exists updated_at timestamptz not null default now();

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  status text not null default 'subscribed',
  language text not null default 'en',
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.newsletter_subscribers add column if not exists status text not null default 'subscribed';
alter table public.newsletter_subscribers add column if not exists language text not null default 'en';
alter table public.newsletter_subscribers add column if not exists source text;
alter table public.newsletter_subscribers add column if not exists updated_at timestamptz not null default now();

create table if not exists public.social_links (
  id uuid primary key default gen_random_uuid(),
  platform text not null,
  label text,
  url text not null,
  icon_key text,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.social_links add column if not exists label text;
alter table public.social_links add column if not exists icon_key text;
alter table public.social_links add column if not exists enabled boolean not null default true;
alter table public.social_links add column if not exists display_order integer not null default 0;
alter table public.social_links add column if not exists updated_at timestamptz not null default now();

create table if not exists public.blog_automation_settings (
  id uuid primary key default gen_random_uuid(),
  enabled boolean not null default true,
  topic_focus text,
  default_language text not null default 'English',
  approval_required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.blog_automation_settings add column if not exists enabled boolean not null default true;
alter table public.blog_automation_settings alter column enabled set default true;
update public.blog_automation_settings set enabled = true where enabled is false;
alter table public.blog_automation_settings add column if not exists topic_focus text;
alter table public.blog_automation_settings add column if not exists default_language text not null default 'English';
alter table public.blog_automation_settings add column if not exists approval_required boolean not null default true;
alter table public.blog_automation_settings add column if not exists updated_at timestamptz not null default now();

alter table public.blog_posts add column if not exists content_type text not null default 'blog';
alter table public.blog_posts add column if not exists keywords text[] not null default '{}';
alter table public.blog_posts add column if not exists category text;
alter table public.blog_posts add column if not exists author text;
alter table public.blog_posts add column if not exists geo_score numeric;
alter table public.blog_posts add column if not exists seo_score numeric;
alter table public.blog_posts add column if not exists scheduled_at timestamptz;
alter table public.blog_posts add column if not exists updated_at timestamptz not null default now();
alter table public.blog_posts add column if not exists image_prompt text;
alter table public.blog_posts add column if not exists internal_links jsonb not null default '[]'::jsonb;
alter table public.blog_posts add column if not exists reading_time text;
alter table public.blog_posts add column if not exists research_model text;

-- Legacy product content fields used by the unchanged public website.
alter table public.products add column if not exists grain_type text;
alter table public.products add column if not exists sizes text;
alter table public.products add column if not exists packaging_type text;
alter table public.products add column if not exists packaging text;
alter table public.products add column if not exists best_for text;
alter table public.products add column if not exists features jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists specifications jsonb not null default '{}'::jsonb;
alter table public.products add column if not exists brochure_url text;
alter table public.products add column if not exists featured boolean not null default false;
alter table public.products add column if not exists display_order integer not null default 0;

-- Existing public website storage buckets. No files are inserted.
insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;
insert into storage.buckets (id, name, public) values ('site-media', 'site-media', true)
on conflict (id) do update set public = excluded.public;

-- Complete B2B product information fields. No public retail price or inventory fields are added.
alter table public.products add column if not exists product_code text;
alter table public.products add column if not exists product_type text;
alter table public.products add column if not exists grade text;
alter table public.products add column if not exists origin text;
alter table public.products add column if not exists color text;
alter table public.products add column if not exists granulation text;
alter table public.products add column if not exists mesh_size text;
alter table public.products add column if not exists purity text;
alter table public.products add column if not exists moisture text;
alter table public.products add column if not exists applications jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists packaging_options jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists available_pack_sizes text;
alter table public.products add column if not exists bulk_packaging text;
alter table public.products add column if not exists private_label_available boolean not null default false;
alter table public.products add column if not exists moq text;
alter table public.products add column if not exists production_capacity text;
alter table public.products add column if not exists lead_time text;
alter table public.products add column if not exists hs_code text;
alter table public.products add column if not exists incoterms text[] not null default '{}';
alter table public.products add column if not exists port_of_loading text;
alter table public.products add column if not exists certifications jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists lab_reports jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists coa_url text;
alter table public.products add column if not exists msds_url text;
alter table public.products add column if not exists specification_sheet_url text;
alter table public.products add column if not exists catalogue_downloads jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists available_markets text[] not null default '{}';
alter table public.products add column if not exists seo_title text;
alter table public.products add column if not exists seo_description text;
alter table public.products add column if not exists updated_at timestamptz not null default now();

alter table public.categories add column if not exists heading text;
alter table public.categories add column if not exists featured_image text;
alter table public.categories add column if not exists banner_image text;
alter table public.categories add column if not exists icon text;
alter table public.categories add column if not exists applications jsonb not null default '[]'::jsonb;
alter table public.categories add column if not exists seo_title text;
alter table public.categories add column if not exists seo_description text;
alter table public.categories add column if not exists geo_summary text;
alter table public.categories add column if not exists display_order integer not null default 0;
alter table public.categories add column if not exists updated_at timestamptz not null default now();

-- Quotation, proforma, commercial invoice, packing list and contract fields.
alter table public.business_documents add column if not exists shipping_address text;
alter table public.business_documents add column if not exists certifications text[] not null default '{}';
alter table public.business_documents add column if not exists company_name text;
alter table public.business_documents add column if not exists company_email text;
alter table public.business_documents add column if not exists company_phone text;
alter table public.business_documents add column if not exists company_address text;
alter table public.business_documents add column if not exists company_website text;
alter table public.business_documents add column if not exists authorized_by text;
alter table public.business_documents add column if not exists authorized_title text;
alter table public.business_documents add column if not exists signature_url text;
alter table public.business_documents add column if not exists bank_details text;
alter table public.business_documents add column if not exists updated_at timestamptz not null default now();

create sequence if not exists public.business_document_seq start 1001;
create or replace function public.assign_business_document_number()
returns trigger language plpgsql as $$
declare prefix text;
begin
  if new.document_number is null or btrim(new.document_number) = '' then
    prefix := case lower(replace(new.document_type,' ','_'))
      when 'quotation' then 'QT'
      when 'proforma_invoice' then 'PI'
      when 'commercial_invoice' then 'CI'
      when 'packing_list' then 'PL'
      when 'sales_contract' then 'SC'
      when 'order_confirmation' then 'OC'
      when 'sample_invoice' then 'SI'
      when 'coa_cover_document' then 'COA'
      else 'DOC' end;
    new.document_number := prefix || '-' || to_char(current_date,'YYYY') || '-' || lpad(nextval('public.business_document_seq')::text,5,'0');
  end if;
  return new;
end;
$$;
drop trigger if exists trg_assign_business_document_number on public.business_documents;
create trigger trg_assign_business_document_number before insert on public.business_documents for each row execute function public.assign_business_document_number();
drop trigger if exists trg_business_documents_updated_at on public.business_documents;
create trigger trg_business_documents_updated_at before update on public.business_documents for each row execute function public.set_updated_at();

-- AI content drafts are stored as draft/review records only.
create table if not exists public.content_drafts (
  id uuid primary key default gen_random_uuid(),
  tool text,
  topic text,
  target_country text,
  target_audience text,
  buyer_type text,
  product text,
  search_intent text,
  primary_keyword text,
  secondary_keywords text[] not null default '{}',
  tone text,
  language text,
  content_length text,
  cta text,
  internal_links text,
  reference_notes text,
  brand_voice text,
  title text not null,
  slug text,
  meta_title text,
  meta_description text,
  excerpt text,
  content text,
  faq jsonb not null default '[]'::jsonb,
  image_prompt text,
  images jsonb not null default '[]'::jsonb,
  seo_score integer not null default 0,
  geo_score integer not null default 0,
  quality_score integer not null default 0,
  status text not null default 'Draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.website_assets (
  id uuid primary key default gen_random_uuid(),
  title text,
  filename text,
  file_url text not null,
  asset_type text,
  website_page text,
  website_section text,
  dimensions text,
  file_type text,
  file_size bigint,
  alt_text text,
  caption text,
  tags text[] not null default '{}',
  usage_count integer not null default 0,
  status text not null default 'Active',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Social records retain separate copy and images for every selected platform.
alter table public.social_scheduled_posts add column if not exists title text;
alter table public.social_scheduled_posts add column if not exists campaign_id uuid references public.marketing_campaigns(id) on delete set null;
alter table public.social_scheduled_posts add column if not exists platform_content jsonb not null default '{}'::jsonb;
alter table public.social_scheduled_posts add column if not exists platform_images jsonb not null default '{}'::jsonb;
alter table public.social_scheduled_posts add column if not exists approval_status text not null default 'Draft';
alter table public.social_scheduled_posts add column if not exists reviewer_id uuid references auth.users(id) on delete set null;
alter table public.social_scheduled_posts add column if not exists approved_at timestamptz;
alter table public.social_scheduled_posts add column if not exists last_error text;
alter table public.social_scheduled_posts add column if not exists brief jsonb not null default '{}'::jsonb;
alter table public.social_scheduled_posts add column if not exists updated_at timestamptz not null default now();

alter table public.approval_items add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.automation_workflows (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  nodes jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  approval_required boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  workflow_id uuid references public.automation_workflows(id) on delete set null,
  workflow_name text,
  status text not null default 'Running',
  current_node_index integer not null default 0,
  steps jsonb not null default '[]'::jsonb,
  completed_node_ids jsonb not null default '[]'::jsonb,
  approval_item_id uuid references public.approval_items(id) on delete set null,
  started_at timestamptz not null default now(),
  approved_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_versions (
  id uuid primary key default gen_random_uuid(),
  page_slug text not null,
  content jsonb not null default '{}'::jsonb,
  seo jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.website_editor_drafts (
  id uuid primary key default gen_random_uuid(),
  page_slug text unique not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'Draft',
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.keyword_research_runs (
  id uuid primary key default gen_random_uuid(),
  research_date date not null default current_date,
  market text not null default 'global',
  provider text,
  primary_keywords jsonb not null default '[]'::jsonb,
  secondary_keywords jsonb not null default '[]'::jsonb,
  questions jsonb not null default '[]'::jsonb,
  competitor_topics jsonb not null default '[]'::jsonb,
  content_opportunities jsonb not null default '[]'::jsonb,
  source_summary text,
  status text not null default 'ready',
  created_at timestamptz not null default now(),
  unique(research_date, market)
);
alter table public.keyword_research_runs add column if not exists provider text;

create table if not exists public.integration_connections (
  id uuid primary key default gen_random_uuid(),
  provider text unique not null,
  label text,
  category text,
  status text not null default 'not_connected',
  config_hint jsonb not null default '{}'::jsonb,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cms_files (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  folder text not null default '/',
  storage_bucket text not null default 'cms-media',
  storage_path text not null,
  public_url text,
  mime_type text,
  size_bytes bigint not null default 0,
  tags text[] not null default '{}',
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Storage bucket used by website editor, images, files, AI content and social assets.
insert into storage.buckets (id, name, public)
values ('cms-media', 'cms-media', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public read CMS media" on storage.objects;
create policy "Public read CMS media" on storage.objects for select using (bucket_id = 'cms-media');
drop policy if exists "Authenticated upload CMS media" on storage.objects;
create policy "Authenticated upload CMS media" on storage.objects for insert to authenticated with check (bucket_id = 'cms-media');
drop policy if exists "Authenticated update CMS media" on storage.objects;
create policy "Authenticated update CMS media" on storage.objects for update to authenticated using (bucket_id = 'cms-media') with check (bucket_id = 'cms-media');
drop policy if exists "Authenticated delete CMS media" on storage.objects;
create policy "Authenticated delete CMS media" on storage.objects for delete to authenticated using (bucket_id = 'cms-media');

-- Public read and authenticated management policies for preserved website image buckets.
do $$
declare bucket text;
begin
  foreach bucket in array array['product-images','site-media'] loop
    execute format('drop policy if exists %I on storage.objects', 'Public read ' || bucket);
    execute format('create policy %I on storage.objects for select using (bucket_id = %L)', 'Public read ' || bucket, bucket);
    execute format('drop policy if exists %I on storage.objects', 'Authenticated upload ' || bucket);
    execute format('create policy %I on storage.objects for insert to authenticated with check (bucket_id = %L)', 'Authenticated upload ' || bucket, bucket);
    execute format('drop policy if exists %I on storage.objects', 'Authenticated update ' || bucket);
    execute format('create policy %I on storage.objects for update to authenticated using (bucket_id = %L) with check (bucket_id = %L)', 'Authenticated update ' || bucket, bucket, bucket);
    execute format('drop policy if exists %I on storage.objects', 'Authenticated delete ' || bucket);
    execute format('create policy %I on storage.objects for delete to authenticated using (bucket_id = %L)', 'Authenticated delete ' || bucket, bucket);
  end loop;
end $$;

-- Public website read/write policies required by the preserved public frontend.
do $$
declare t text;
begin
  foreach t in array array['products','categories','seo_settings','page_content','blog_posts','site_settings','homepage','cms_faqs','social_links','cms_languages','cms_text_entries','cms_text_translations','cms_image_slots'] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists %I on public.%I', 'public read live website content', t);
      execute format('create policy %I on public.%I for select to anon, authenticated using (true)', 'public read live website content', t);
    end if;
  end loop;
end $$;

alter table public.newsletter_subscribers enable row level security;
drop policy if exists "public newsletter subscribe" on public.newsletter_subscribers;
create policy "public newsletter subscribe" on public.newsletter_subscribers for insert to anon, authenticated with check (status = 'subscribed');
drop policy if exists "public newsletter refresh subscription" on public.newsletter_subscribers;
create policy "public newsletter refresh subscription" on public.newsletter_subscribers for update to anon, authenticated using (true) with check (status = 'subscribed');

-- Updated-at triggers for newly introduced tables.
do $$
declare t text;
begin
  foreach t in array array['content_drafts','website_assets','automation_workflows','automation_runs','website_editor_drafts'] loop
    execute format('drop trigger if exists %I on public.%I', 'trg_' || t || '_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', 'trg_' || t || '_updated_at', t);
  end loop;
end $$;

-- Authenticated CMS users can manage CMS records. Public website writes continue through server routes.
do $$
declare t text;
begin
  foreach t in array array[
    'products','categories','seo_settings','page_content','media_library','blog_posts','site_settings','homepage',
    'cms_faqs','newsletter_subscribers','social_links','blog_automation_settings',
    'cms_roles','cms_profiles','cms_languages','cms_text_entries','cms_text_translations','cms_image_slots',
    'document_letterheads','business_documents','content_drafts','website_assets','social_scheduled_posts',
    'automation_workflows','automation_runs','page_versions','website_editor_drafts','keyword_research_runs',
    'integration_connections','cms_files'
  ] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists "live cms authenticated manage" on public.%I', t);
      execute format('create policy "live cms authenticated manage" on public.%I for all to authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;

-- Real admin profile is created from the authenticated Supabase user on first login.
create or replace function public.handle_new_cms_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.cms_profiles(id, full_name, role_name, enabled)
  values(new.id, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email,'@',1)), coalesce(new.raw_app_meta_data->>'role','super_admin'), true)
  on conflict(id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_cms_profile on auth.users;
create trigger on_auth_user_created_cms_profile after insert on auth.users for each row execute function public.handle_new_cms_user();

-- No business data is seeded by this migration.

-- Website navigation and legal-page text slots added by the unified website/CMS update.
-- These are structural CMS fields only; no legal body text or fabricated business data is inserted.
insert into public.cms_text_entries (page_slug, section_slug, field_key, field_label, field_type, default_value, display_order)
values
  ('global','navbar','faq','FAQ Menu Label','text','FAQ',9001),
  ('faqs','hero','eyebrow','FAQ Eyebrow','text','BUYER SUPPORT',9002),
  ('faqs','hero','title','FAQ Page Heading','textarea','Frequently Asked Questions',9003),
  ('faqs','hero','description','FAQ Page Description','textarea','Clear answers for importers, distributors, wholesalers and private-label buyers.',9004),
  ('privacy-policy','content','title','Privacy Policy Heading','text','Privacy Policy',9010),
  ('privacy-policy','content','introduction','Privacy Policy Introduction','textarea','',9011),
  ('privacy-policy','content','body','Privacy Policy Content','textarea','',9012),
  ('terms-and-conditions','content','title','Terms & Conditions Heading','text','Terms & Conditions',9020),
  ('terms-and-conditions','content','introduction','Terms & Conditions Introduction','textarea','',9021),
  ('terms-and-conditions','content','body','Terms & Conditions Content','textarea','',9022)
on conflict (page_slug, section_slug, field_key) do nothing;

-- -----------------------------------------------------------------------------
-- AUGUST 2026 — INTERNAL COMMERCIAL SHEET AND EMAIL REPLY DRAFTS
-- -----------------------------------------------------------------------------
alter table if exists public.b2b_contacts add column if not exists platform text;

create table if not exists public.product_commercial_terms (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  export_reference text,
  pack_size text,
  packaging text,
  currency text not null default 'USD',
  cost_price numeric(18,4),
  ex_factory_price numeric(18,4),
  fob_price numeric(18,4),
  private_label_price numeric(18,4),
  moq text,
  lead_time text,
  notes text,
  status text not null default 'active',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_commercial_terms_product_idx on public.product_commercial_terms(product_id);
create index if not exists product_commercial_terms_status_idx on public.product_commercial_terms(status);
drop trigger if exists trg_product_commercial_terms_updated_at on public.product_commercial_terms;
create trigger trg_product_commercial_terms_updated_at before update on public.product_commercial_terms for each row execute function public.set_updated_at();

create table if not exists public.email_reply_drafts (
  id bigint generated by default as identity primary key,
  incoming_message text not null,
  sender_name text,
  sender_company text,
  product_id bigint references public.products(id) on delete set null,
  subject text,
  reply_body text not null,
  reference_notes text,
  status text not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists trg_email_reply_drafts_updated_at on public.email_reply_drafts;
create trigger trg_email_reply_drafts_updated_at before update on public.email_reply_drafts for each row execute function public.set_updated_at();

do $$
declare t text;
begin
  foreach t in array array['product_commercial_terms','email_reply_drafts'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "enterprise cms authenticated manage" on public.%I', t);
    execute format('create policy "enterprise cms authenticated manage" on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Team Tasks (ClickUp-style daily task management)
create table if not exists public.team_tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  assigned_name text not null,
  assigned_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'To Do',
  priority text not null default 'Normal',
  due_at timestamptz,
  module text,
  related_record_id text,
  created_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.team_tasks add column if not exists list_name text not null default 'General';
alter table public.team_tasks add column if not exists reminder_at timestamptz;
alter table public.team_tasks add column if not exists reminder_sent_at timestamptz;
alter table public.team_tasks add column if not exists recurring_rule text not null default 'None';
alter table public.team_tasks add column if not exists labels text[] not null default '{}';
create index if not exists idx_team_tasks_reminder_at on public.team_tasks(reminder_at);
create index if not exists idx_team_tasks_list_name on public.team_tasks(list_name);
create index if not exists idx_team_tasks_assigned_name on public.team_tasks(assigned_name);
create index if not exists idx_team_tasks_due_at on public.team_tasks(due_at);
create index if not exists idx_team_tasks_status on public.team_tasks(status);
alter table public.team_tasks enable row level security;
drop policy if exists "enterprise cms authenticated manage" on public.team_tasks;
create policy "enterprise cms authenticated manage" on public.team_tasks for all to authenticated using (true) with check (true);
