"use client";
import { useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { ExternalLink, Globe2, Link2, Search, Target, TrendingUp } from "lucide-react";
const demo=[
 {domain:"industry publication",topic:"Himalayan salt private label",authority:"High",gap:"Packaging and MOQ guide",action:"Editorial outreach"},
 {domain:"food ingredients directory",topic:"Bulk pink salt supplier",authority:"High",gap:"Supplier comparison page",action:"Directory submission"},
 {domain:"retail packaging blog",topic:"Stand-up pouch salt packaging",authority:"Medium",gap:"Case study with specifications",action:"Guest article"},
];
export default function BacklinksPage(){const[seed,setSeed]=useState("Himalayan pink salt exporter");const[loading,setLoading]=useState(false);async function run(){setLoading(true);await fetch("/api/seo/keyword-research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed,includeCompetitors:true,includeBacklinks:true})}).catch(()=>null);setLoading(false);alert("Authority and backlink opportunity research queued.")};return <AdminShell><div className="enterprise-page"><header className="enterprise-page-header"><div><p className="enterprise-kicker">OFF-PAGE SEO INTELLIGENCE</p><h1>BACKLINK & COMPETITOR INTELLIGENCE</h1></div></header><section className="research-command"><div><Search/><input value={seed} onChange={e=>setSeed(e.target.value)}/></div><button onClick={run} className="cms-gradient-button">{loading?"Researching…":"Run worldwide research"}</button></section><section className="enterprise-stat-grid four"><article><Globe2/><strong>Worldwide</strong><span>MARKET COVERAGE</span></article><article><Target/><strong>Daily</strong><span>CONTENT GAP SCAN</span></article><article><Link2/><strong>Ready</strong><span>BACKLINK PIPELINE</span></article><article><TrendingUp/><strong>Tracked</strong><span>KEYWORD MOVEMENT</span></article></section><section className="enterprise-table-card"><table><thead><tr><th>Source type</th><th>Ranking topic</th><th>Authority</th><th>Content gap</th><th>Recommended action</th><th/></tr></thead><tbody>{demo.map(row=><tr key={row.domain}><td><b>{row.domain}</b></td><td>{row.topic}</td><td>{row.authority}</td><td>{row.gap}</td><td>{row.action}</td><td><button className="icon-action"><ExternalLink/></button></td></tr>)}</tbody></table></section></div></AdminShell>}
