"use client";

import { useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { adminFetch } from "@/lib/admin-client";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, Clipboard, Copy, Mail, RefreshCw, Save, Sparkles } from "lucide-react";

type Product = { id: number; title?: string; name?: string };
export default function EmailAssistantPage() {
  const [products,setProducts]=useState<Product[]>([]); const [incoming,setIncoming]=useState(""); const [senderName,setSenderName]=useState(""); const [senderCompany,setSenderCompany]=useState(""); const [productId,setProductId]=useState(""); const [extra,setExtra]=useState(""); const [reply,setReply]=useState(""); const [subject,setSubject]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [toast,setToast]=useState("");
  useEffect(()=>{void supabase.from("products").select("id,title,name").order("title").then(({data})=>setProducts(data||[]));},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2300);return()=>clearTimeout(timer)},[toast]);
  async function generate(){if(!incoming.trim()){setError("Paste the buyer inquiry first.");return}setLoading(true);setError("");try{const response=await adminFetch("/api/admin/email-reply",{method:"POST",body:JSON.stringify({incoming,senderName,senderCompany,productId:productId?Number(productId):null,extra})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Reply generation failed.");setReply(String(data.reply||""));setSubject(String(data.subject||""));setToast("Reply generated for review")}catch(e){setError(e instanceof Error?e.message:"Reply generation failed.")}finally{setLoading(false)}}
  async function saveDraft(){if(!reply.trim()){setError("Generate or write a reply before saving.");return}setLoading(true);setError("");const session=await supabase.auth.getSession();const result=await supabase.from("email_reply_drafts").insert({incoming_message:incoming,sender_name:senderName||null,sender_company:senderCompany||null,product_id:productId?Number(productId):null,subject:subject||null,reply_body:reply,reference_notes:extra||null,status:"draft",created_by:session.data.session?.user.id||null});if(result.error)setError(result.error.message);else setToast("Reply saved as a draft");setLoading(false)}
  async function paste(){try{setIncoming(await navigator.clipboard.readText());setToast("Clipboard pasted")}catch{setError("Browser clipboard permission is blocked. Paste the inquiry manually.")}}
  async function copy(){await navigator.clipboard.writeText(`${subject?`Subject: ${subject}\n\n`:""}${reply}`);setToast("Reply copied")}
  return <AdminShell><div className="os-page"><header className="os-page-header"><div><div className="os-page-eyebrow">AI-assisted buyer communication</div><h1 className="os-page-title">Email Reply Assistant</h1><p className="os-page-subtitle">Generate a factual buyer reply using your website content, selected product and internal MOQ, price and payment-term records. Every reply remains a draft until you send it.</p></div><div className="os-page-actions"><button className="os-btn soft" onClick={()=>{setIncoming("");setReply("");setSubject("");setError("")}}><RefreshCw/>Clear</button><button className="os-btn primary" onClick={()=>void generate()} disabled={loading}><Sparkles/>{loading?"Generating…":"Generate Reply"}</button></div></header>
  {error&&<section className="os-card" style={{borderColor:"rgba(239,68,68,.35)"}}><div className="os-card-body"><strong>Reply could not be generated</strong><p className="os-page-subtitle">{error}</p></div></section>}
  <div className="email-assistant-layout"><section className="os-card"><div className="os-card-header"><div><h2>Buyer Inquiry</h2><p>Paste the exact email, WhatsApp message or website inquiry.</p></div><button className="os-btn soft" onClick={()=>void paste()}><Clipboard/>Paste</button></div><div className="os-card-body"><div className="os-form-grid"><label className="os-label"><span>Buyer Name</span><input value={senderName} onChange={e=>setSenderName(e.target.value)}/></label><label className="os-label"><span>Company</span><input value={senderCompany} onChange={e=>setSenderCompany(e.target.value)}/></label><label className="os-label full"><span>Related Product</span><select value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Detect from inquiry / general</option>{products.map(product=><option key={product.id} value={product.id}>{product.title||product.name}</option>)}</select></label><label className="os-label full"><span>Incoming Message *</span><textarea rows={13} value={incoming} onChange={e=>setIncoming(e.target.value)} placeholder="Paste the buyer inquiry here…"/></label><label className="os-label full"><span>Extra Instructions</span><textarea rows={4} value={extra} onChange={e=>setExtra(e.target.value)} placeholder="Example: Keep the reply concise; mention FOB Karachi; ask for destination port."/></label></div></div></section>
  <section className="os-card"><div className="os-card-header"><div><h2>Draft Reply</h2><p>Review and edit before copying or saving.</p></div></div><div className="os-card-body"><label className="os-label"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="os-label" style={{marginTop:12}}><span>Email Body</span><textarea className="email-assistant-preview" value={reply} onChange={e=>setReply(e.target.value)} placeholder="The generated reply will appear here."/></label><div className="os-page-actions" style={{marginTop:14}}><button className="os-btn soft" onClick={()=>void copy()} disabled={!reply}><Copy/>Copy</button><button className="os-btn primary" onClick={()=>void saveDraft()} disabled={loading||!reply}><Save/>Save Draft</button></div></div></section></div>
  <section className="os-card"><div className="os-card-header"><div><h2>Data Used by the Assistant</h2><p>No price, MOQ, certification or payment term is invented.</p></div></div><div className="os-card-body email-context-list"><div><span>Public website content</span><strong>Page content and product records</strong></div><div><span>Internal commercial terms</span><strong>Product Commercial Sheet</strong></div><div><span>Company identity</span><strong>Letterhead and site settings</strong></div><div><span>AI connection</span><strong>OpenAI API required</strong></div><div><span>Sending</span><strong>Manual after review</strong></div></div></section>
  {toast&&<div className="os-toast-stack"><div className="os-toast"><span className="os-toast-icon"><CheckCircle2/></span><div><strong>{toast}</strong><span>The reply has not been sent automatically.</span></div></div></div>}
  </div></AdminShell>
}
