"use client";

import { ChangeEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { ArrowLeft, CheckCircle2, Eye, ImagePlus, Plus, RefreshCw, Save, Trash2, UploadCloud } from "lucide-react";

type Product = Record<string, any> & { id:number; title:string; slug:string; status:string };
type WhyItem = { title:string; text:string; icon:string };
type DetailSettings = {
  eyebrow:string; specificationsTitle:string; featuresTitle:string; applicationsTitle:string; whyTitle:string;
  requestQuoteLabel:string; whatsappLabel:string; whatsappNumber:string; showWhySection:boolean; showGallery:boolean; whyItems:WhyItem[];
};
const defaults:DetailSettings={eyebrow:"Product Details",specificationsTitle:"Product Specifications",featuresTitle:"Key Features",applicationsTitle:"Applications",whyTitle:"Why Buy From The Salt Origin?",requestQuoteLabel:"Request Quotation",whatsappLabel:"WhatsApp Inquiry",whatsappNumber:"923462771693",showWhySection:true,showGallery:true,whyItems:[{icon:"globe",title:"Global Export Support",text:"Documentation and supply support for international B2B buyers."},{icon:"package",title:"Flexible Packaging",text:"Retail, bulk and private-label packaging options for different markets."},{icon:"shield",title:"Quality-Focused Supply",text:"Product specifications, quality documents and traceability support where available."},{icon:"tag",title:"Private Label Ready",text:"Custom branding and packaging support for qualified projects."}]};
function lines(value:unknown){return Array.isArray(value)?value.join("\n"):String(value||"")}
function parseLines(value:string){return value.split("\n").map(item=>item.trim()).filter(Boolean)}
function specText(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return"";return Object.entries(value as Record<string,string>).map(([key,item])=>`${key}: ${item}`).join("\n")}
function parseSpecs(value:string){const output:Record<string,string>={};parseLines(value).forEach(row=>{const [key,...rest]=row.split(":");if(key&&rest.length)output[key.trim()]=rest.join(":").trim()});return output}

export default function ProductDetailEditor(){
  const params=useParams<{id:string}>(); const id=Number(params.id);
  const[product,setProduct]=useState<Product|null>(null);const[form,setForm]=useState<Record<string,any>>({});const[settings,setSettings]=useState<DetailSettings>(defaults);
  const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");const[uploading,setUploading]=useState("");
  const load=useCallback(async()=>{if(!id)return;setLoading(true);setError("");const[productResult,pageResult]=await Promise.all([supabase.from("products").select("*").eq("id",id).maybeSingle(),supabase.from("page_content").select("content").eq("page_slug",`product:${id}`).maybeSingle()]);if(productResult.error||!productResult.data){setError(productResult.error?.message||"Product not found.");setLoading(false);return}const row=productResult.data as Product;setProduct(row);setForm({...row,features:lines(row.features),applications:lines(row.applications),gallery:lines(row.gallery),specifications:specText(row.specifications),incoterms:lines(row.incoterms),available_markets:lines(row.available_markets)});const content=pageResult.data?.content;setSettings({...defaults,...(content&&typeof content==="object"&&!Array.isArray(content)?content:{}),whyItems:Array.isArray((content as any)?.whyItems)&&((content as any).whyItems.length)?(content as any).whyItems:defaults.whyItems});setLoading(false)},[id]);
  useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(timer)},[toast]);
  const publicUrl=useMemo(()=>product?`/products/${form.slug||product.slug}`:"/products",[product,form.slug]);
  function patch(key:string,value:any){setForm(previous=>({...previous,[key]:value}))}
  function patchSetting<K extends keyof DetailSettings>(key:K,value:DetailSettings[K]){setSettings(previous=>({...previous,[key]:value}))}
  function patchWhy(index:number,key:keyof WhyItem,value:string){setSettings(previous=>({...previous,whyItems:previous.whyItems.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item)}))}
  async function upload(event:ChangeEvent<HTMLInputElement>,target:"image"|"gallery"){const file=event.target.files?.[0];if(!file)return;setUploading(target);setError("");const path=`products/${id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const result=await supabase.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(result.error)setError(result.error.message);else{const url=supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl;if(target==="image")patch("image",url);else patch("gallery",`${String(form.gallery||"").trim()}${form.gallery?"\n":""}${url}`)}setUploading("");event.target.value=""}
  async function save(){if(!form.title?.trim()){setError("Product title is required.");return}setSaving(true);setError("");const productPayload={title:String(form.title).trim(),slug:String(form.slug||"").trim(),subtitle:String(form.subtitle||""),category:String(form.category||""),description:String(form.description||""),short_description:String(form.short_description||""),image:String(form.image||""),gallery:parseLines(String(form.gallery||"")),status:String(form.status||"draft"),moq:String(form.moq||""),packaging:String(form.packaging||""),grain_type:String(form.grain_type||""),sizes:String(form.sizes||""),packaging_type:String(form.packaging_type||""),best_for:String(form.best_for||""),features:parseLines(String(form.features||"")),applications:parseLines(String(form.applications||"")),specifications:parseSpecs(String(form.specifications||"")),brochure_url:String(form.brochure_url||""),origin:String(form.origin||""),grade:String(form.grade||""),granulation:String(form.granulation||""),mesh_size:String(form.mesh_size||""),purity:String(form.purity||""),moisture:String(form.moisture||""),available_pack_sizes:String(form.available_pack_sizes||""),bulk_packaging:String(form.bulk_packaging||""),private_label_available:Boolean(form.private_label_available),production_capacity:String(form.production_capacity||""),lead_time:String(form.lead_time||""),hs_code:String(form.hs_code||""),incoterms:parseLines(String(form.incoterms||"")),port_of_loading:String(form.port_of_loading||""),coa_url:String(form.coa_url||""),msds_url:String(form.msds_url||""),specification_sheet_url:String(form.specification_sheet_url||""),seo_title:String(form.seo_title||""),seo_description:String(form.seo_description||""),updated_at:new Date().toISOString()};const[productResult,pageResult]=await Promise.all([supabase.from("products").update(productPayload).eq("id",id),supabase.from("page_content").upsert({page_slug:`product:${id}`,content:settings,updated_at:new Date().toISOString()},{onConflict:"page_slug"})]);setSaving(false);if(productResult.error||pageResult.error){setError(productResult.error?.message||pageResult.error?.message||"Unable to save product page.");return}setToast("Product detail page saved");await load()}
  if(loading)return <AdminShell><div className="os-empty" style={{minHeight:"70vh"}}><RefreshCw className="animate-spin"/><h3>Loading product page editor…</h3></div></AdminShell>;
  if(!product)return <AdminShell><div className="os-page"><div className="os-empty"><h3>Product unavailable</h3><p>{error}</p><Link className="os-btn primary" href="/admin/products">Back to Products</Link></div></div></AdminShell>;
  return <AdminShell><div className="os-page">
    <header className="os-page-header"><div><Link href="/admin/products" className="os-page-eyebrow" style={{display:"inline-flex",alignItems:"center",gap:7}}><ArrowLeft/>Products</Link><h1 className="os-page-title">Product Detail Page Editor</h1><p className="os-page-subtitle">Edit the exact text, images, specifications, CTAs, SEO and section labels used on this product’s public page.</p></div><div className="os-page-actions"><Link href={publicUrl} target="_blank" className="os-btn soft"><Eye/>Open Live Page</Link><button className="os-btn primary" onClick={()=>void save()} disabled={saving}><Save/>{saving?"Saving…":"Save Product Page"}</button></div></header>
    {error&&<section className="os-card" style={{borderColor:"rgba(239,68,68,.35)"}}><div className="os-card-body"><strong>Product page action failed</strong><p className="os-page-subtitle">{error}</p></div></section>}
    <div className="product-page-editor-layout">
      <div className="product-page-editor-fields">
        <EditorSection title="Core Product Content" description="Main title, URL and buyer-facing summary."><div className="os-form-grid"><Field label="Product Title" value={form.title} onChange={value=>patch("title",value)}/><Field label="URL Slug" value={form.slug} onChange={value=>patch("slug",value)}/><Field label="Subtitle" value={form.subtitle} onChange={value=>patch("subtitle",value)}/><Field label="Category" value={form.category} onChange={value=>patch("category",value)}/><TextArea label="Short Description" value={form.short_description} onChange={value=>patch("short_description",value)} full/><TextArea label="Full Product Description" value={form.description} onChange={value=>patch("description",value)} full/></div></EditorSection>
        <EditorSection title="Product Images" description="Main image and gallery images used on the public product page."><div className="os-form-grid"><label className="os-label full"><span>Main Image URL</span><input value={form.image||""} onChange={event=>patch("image",event.target.value)}/><label className="os-btn soft" style={{width:"fit-content",cursor:"pointer"}}><ImagePlus/>{uploading==="image"?"Uploading…":"Upload Main Image"}<input hidden type="file" accept="image/*" onChange={event=>void upload(event,"image")}/></label></label>{form.image&&<img src={form.image} alt="Product preview" className="product-editor-image-preview"/>}<TextArea label="Gallery Image URLs — one per line" value={form.gallery} onChange={value=>patch("gallery",value)} full/><label className="os-btn soft" style={{width:"fit-content",cursor:"pointer"}}><UploadCloud/>{uploading==="gallery"?"Uploading…":"Add Gallery Image"}<input hidden type="file" accept="image/*" onChange={event=>void upload(event,"gallery")}/></label></div></EditorSection>
        <EditorSection title="Specifications & Applications" description="All values below appear in the product specification and use-case panels."><div className="os-form-grid"><Field label="Origin" value={form.origin} onChange={value=>patch("origin",value)}/><Field label="Grade" value={form.grade} onChange={value=>patch("grade",value)}/><Field label="Grain Type" value={form.grain_type} onChange={value=>patch("grain_type",value)}/><Field label="Granulation" value={form.granulation} onChange={value=>patch("granulation",value)}/><Field label="Mesh Size" value={form.mesh_size} onChange={value=>patch("mesh_size",value)}/><Field label="Purity" value={form.purity} onChange={value=>patch("purity",value)}/><Field label="Moisture" value={form.moisture} onChange={value=>patch("moisture",value)}/><Field label="Available Sizes" value={form.available_pack_sizes||form.sizes} onChange={value=>patch("available_pack_sizes",value)}/><Field label="Packaging" value={form.packaging} onChange={value=>patch("packaging",value)}/><Field label="Bulk Packaging" value={form.bulk_packaging} onChange={value=>patch("bulk_packaging",value)}/><Field label="MOQ" value={form.moq} onChange={value=>patch("moq",value)}/><Field label="Lead Time" value={form.lead_time} onChange={value=>patch("lead_time",value)}/><Field label="Production Capacity" value={form.production_capacity} onChange={value=>patch("production_capacity",value)}/><Field label="HS Code" value={form.hs_code} onChange={value=>patch("hs_code",value)}/><Field label="Port of Loading" value={form.port_of_loading} onChange={value=>patch("port_of_loading",value)}/><Field label="Best For" value={form.best_for} onChange={value=>patch("best_for",value)}/><TextArea label="Features — one per line" value={form.features} onChange={value=>patch("features",value)} full/><TextArea label="Applications — one per line" value={form.applications} onChange={value=>patch("applications",value)} full/><TextArea label="Additional Specifications — Label: Value" value={form.specifications} onChange={value=>patch("specifications",value)} full/></div></EditorSection>
        <EditorSection title="Documents & SEO" description="Public downloadable files and search metadata."><div className="os-form-grid"><Field label="Specification Sheet URL" value={form.specification_sheet_url} onChange={value=>patch("specification_sheet_url",value)}/><Field label="COA URL" value={form.coa_url} onChange={value=>patch("coa_url",value)}/><Field label="MSDS URL" value={form.msds_url} onChange={value=>patch("msds_url",value)}/><Field label="Brochure URL" value={form.brochure_url} onChange={value=>patch("brochure_url",value)}/><Field label="SEO Title" value={form.seo_title} onChange={value=>patch("seo_title",value)} full/><TextArea label="SEO Description" value={form.seo_description} onChange={value=>patch("seo_description",value)} full/><label className="os-label"><span>Website Status</span><select value={form.status||"draft"} onChange={event=>patch("status",event.target.value)}><option value="active">Active — visible</option><option value="draft">Draft — hidden</option><option value="archived">Archived</option></select></label><label className="os-label"><span>Private Label Available</span><input type="checkbox" checked={Boolean(form.private_label_available)} onChange={event=>patch("private_label_available",event.target.checked)} style={{width:22,height:22}}/></label></div></EditorSection>
        <EditorSection title="Product Page Labels & Sections" description="Change the fixed headings, button labels and partnership cards without opening source code."><div className="os-form-grid"><Field label="Eyebrow" value={settings.eyebrow} onChange={value=>patchSetting("eyebrow",value)}/><Field label="Specifications Heading" value={settings.specificationsTitle} onChange={value=>patchSetting("specificationsTitle",value)}/><Field label="Features Heading" value={settings.featuresTitle} onChange={value=>patchSetting("featuresTitle",value)}/><Field label="Applications Heading" value={settings.applicationsTitle} onChange={value=>patchSetting("applicationsTitle",value)}/><Field label="Why Buy Heading" value={settings.whyTitle} onChange={value=>patchSetting("whyTitle",value)} full/><Field label="Quotation Button" value={settings.requestQuoteLabel} onChange={value=>patchSetting("requestQuoteLabel",value)}/><Field label="WhatsApp Button" value={settings.whatsappLabel} onChange={value=>patchSetting("whatsappLabel",value)}/><Field label="WhatsApp Number" value={settings.whatsappNumber} onChange={value=>patchSetting("whatsappNumber",value)}/><label className="os-label"><span>Show Gallery</span><input type="checkbox" checked={settings.showGallery} onChange={event=>patchSetting("showGallery",event.target.checked)} style={{width:22,height:22}}/></label><label className="os-label"><span>Show Why Buy Section</span><input type="checkbox" checked={settings.showWhySection} onChange={event=>patchSetting("showWhySection",event.target.checked)} style={{width:22,height:22}}/></label></div><div className="os-grid two" style={{marginTop:16}}>{settings.whyItems.map((item,index)=><article className="os-card" style={{boxShadow:"none"}} key={`${item.title}-${index}`}><div className="os-card-body"><Field label="Card Title" value={item.title} onChange={value=>patchWhy(index,"title",value)}/><TextArea label="Card Text" value={item.text} onChange={value=>patchWhy(index,"text",value)}/><label className="os-label"><span>Icon</span><select value={item.icon} onChange={event=>patchWhy(index,"icon",event.target.value)}><option value="globe">Globe</option><option value="package">Package</option><option value="shield">Shield</option><option value="tag">Tag</option></select></label><button className="os-btn danger" onClick={()=>patchSetting("whyItems",settings.whyItems.filter((_,itemIndex)=>itemIndex!==index))}><Trash2/>Remove</button></div></article>)}</div><button className="os-btn soft" style={{marginTop:14}} onClick={()=>patchSetting("whyItems",[...settings.whyItems,{icon:"globe",title:"",text:""}])}><Plus/>Add Partnership Card</button></EditorSection>
      </div>
      <aside className="os-card product-page-preview-panel"><div className="os-card-header"><div><h2>Live Product Page</h2><p>Saved changes appear on the real product URL</p></div><Eye/></div><div className="os-card-body"><div className="product-page-mini-preview">{form.image?<img src={form.image} alt=""/>:<div/>}<span>{settings.eyebrow}</span><h3>{form.title}</h3><p>{form.description||form.short_description}</p><div><b>{form.origin||"Origin"}</b><b>{form.moq||"MOQ"}</b></div></div><Link className="os-btn primary" style={{width:"100%",marginTop:14}} href={publicUrl} target="_blank"><Eye/>Open Full Preview</Link></div></aside>
    </div>
    {toast&&<div className="os-toast-stack"><div className="os-toast"><span className="os-toast-icon"><CheckCircle2/></span><div><strong>{toast}</strong><span>The live product and page settings were updated.</span></div></div></div>}
  </div></AdminShell>
}
function EditorSection({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="os-card"><div className="os-card-header"><div><h2>{title}</h2><p>{description}</p></div></div><div className="os-card-body">{children}</div></section>}
function Field({label,value,onChange,full=false}:{label:string;value:any;onChange:(value:string)=>void;full?:boolean}){return <label className={`os-label ${full?"full":""}`}><span>{label}</span><input value={String(value??"")} onChange={event=>onChange(event.target.value)}/></label>}
function TextArea({label,value,onChange,full=false}:{label:string;value:any;onChange:(value:string)=>void;full?:boolean}){return <label className={`os-label ${full?"full":""}`}><span>{label}</span><textarea value={String(value??"")} onChange={event=>onChange(event.target.value)}/></label>}
