"use client";
import { useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { MessageCircle, Send, Smartphone, CheckCircle2 } from "lucide-react";
export default function WhatsAppPage(){
 const[phone,setPhone]=useState("");const[message,setMessage]=useState("Test notification from The Salt Origin CMS");const[sending,setSending]=useState(false);const[result,setResult]=useState("");
 async function test(){setSending(true);setResult("");const r=await fetch('/api/whatsapp/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,message})});const j=await r.json();setSending(false);setResult(r.ok?'WhatsApp connection successful.':j.error||'Test failed.');}
 return <AdminShell><div className="space-y-7"><div><p className="text-xs font-black uppercase tracking-[5px] text-emerald-500">Messaging</p><h1 className="mt-2 text-4xl font-black">WhatsApp Center</h1><p className="mt-3 text-slate-500">Receive every new inquiry on WhatsApp and open buyer chats directly from CRM.</p></div><div className="grid gap-5 md:grid-cols-3">{[[MessageCircle,'Inquiry Alerts','Complete buyer inquiry is sent to your WhatsApp.'],[Smartphone,'Quick Reply','Open a buyer chat from the inquiry dashboard.'],[CheckCircle2,'Cloud API','Uses Meta WhatsApp Cloud API or your webhook.']].map(([I,t,d]:any)=><article key={t} className="cms-panel rounded-3xl border p-6"><I className="h-6 w-6 text-emerald-500"/><h2 className="mt-4 font-black">{t}</h2><p className="mt-2 text-sm text-slate-500">{d}</p></article>)}</div><section className="cms-panel rounded-3xl border p-6"><h2 className="text-xl font-black">Connection Test</h2><p className="mt-2 text-sm text-slate-500">Use international format without +, for example 923212430365. Configure WHATSAPP_CLOUD_ACCESS_TOKEN, WHATSAPP_CLOUD_PHONE_NUMBER_ID and WHATSAPP_NOTIFICATION_TO.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="923212430365" className="rounded-xl border p-3"/><input value={message} onChange={e=>setMessage(e.target.value)} className="rounded-xl border p-3"/></div><button onClick={test} disabled={sending} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 font-black text-white"><Send className="h-4 w-4"/>{sending?'Testing...':'Send Test'}</button>{result&&<p className="mt-4 rounded-xl border p-3 text-sm font-bold">{result}</p>}</section></div></AdminShell>
}
