"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { adminFetch } from "@/lib/admin-client";
import { Check, Copy, ExternalLink, Globe2, HelpCircle, RefreshCw, Search, Sparkles, Star, Target } from "lucide-react";

type Row = Record<string, any>;
const tabs = ["Keyword Overview", "Buyer Intent", "Questions", "Keyword Clusters", "Content Opportunities", "Research History"];
function normalizeKeyword(item: any) { return typeof item === "string" ? { keyword: item, intent: "Not classified", priority: "target" } : item || {}; }

export default function KeywordResearchPage() {
  const router = useRouter();
  const [rows, setRows] = useState<Row[]>([]);
  const [tab, setTab] = useState("Keyword Overview");
  const [market, setMarket] = useState("global");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState("");
  const [query, setQuery] = useState("");
  async function load() { const { data, error: loadError } = await supabase.from("keyword_research_runs").select("*").order("created_at", { ascending: false }).limit(30); if (loadError) setError(loadError.message); setRows(data || []); }
  useEffect(() => { void load(); }, []);
  async function generate() { setBusy(true); setError(""); const response = await adminFetch(`/api/seo/keyword-research?market=${encodeURIComponent(market || "global")}`, { method: "POST" }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || "Research failed"); else await load(); setBusy(false); }
  async function copy(text: string) { await navigator.clipboard.writeText(text); setCopied(text); setTimeout(() => setCopied(""), 1200); }
  function openStudio(keyword: string, title?: string) { const params = new URLSearchParams({ keyword, title: title || keyword }); router.push(`/admin/content-studio?${params.toString()}`); }
  async function createFaq(question: string) { const { error: insertError } = await supabase.from("faq_research_questions").insert({ question, source: "Keyword Research", source_mode: "Connected AI Web Research", recommended_category: "Buyer Questions", ai_answer: "", status: "New Suggestion" }); if (insertError) return setError(insertError.message); router.push("/admin/faq-intelligence"); }
  const latest = rows.find(row => String(row.market || "global").toLowerCase() === market.toLowerCase()) || rows[0];
  const primary = useMemo(() => (latest?.primary_keywords || []).map(normalizeKeyword).filter((item: any) => !query || `${item.keyword} ${item.intent}`.toLowerCase().includes(query.toLowerCase())), [latest, query]);
  const secondary = useMemo(() => (latest?.secondary_keywords || []).filter((item: string) => !query || item.toLowerCase().includes(query.toLowerCase())), [latest, query]);
  const clusters = useMemo(() => { const map = new Map<string, string[]>(); (latest?.primary_keywords || []).map(normalizeKeyword).forEach((item: any) => { const key = item.intent || "Unclassified"; map.set(key, [...(map.get(key) || []), item.keyword]); }); return [...map.entries()]; }, [latest]);
  const questions: string[] = latest?.questions || [];
  const opportunities: Row[] = latest?.content_opportunities || [];

  return <AdminShell><div className="os-page keyword-command-center">
    <header className="os-page-header"><div><div className="os-page-eyebrow">B2B buyer-search intelligence</div><h1 className="os-page-title">Keyword Research</h1><p className="os-page-subtitle">Research current supplier, manufacturer, private-label, bulk-purchase and certification questions through the connected AI web-research provider. Unsupported volume, CPC and ranking numbers are never invented.</p></div><div className="os-page-actions"><input className="os-field market-input" value={market} onChange={event => setMarket(event.target.value)} placeholder="Target market e.g. USA"/><button className="os-btn primary" onClick={() => void generate()} disabled={busy}><RefreshCw className={busy ? "animate-spin" : ""}/>{busy ? "Researching…" : "Run Market Research"}</button></div></header>
    {error && <section className="os-card"><div className="os-card-body geo-alert"><HelpCircle/><div><strong>Research could not be completed</strong><p>{error}</p></div></div></section>}
    <section className="os-grid four seo-summary-grid">{[["Primary Keywords", primary.length, Search], ["Buyer Questions", questions.length, HelpCircle], ["Intent Clusters", clusters.length, Target], ["Content Opportunities", opportunities.length, Sparkles]].map(([label, value, Icon]) => { const Component = Icon as typeof Search; return <article className="os-metric" key={String(label)}><div className="os-metric-top"><span className="os-metric-label">{String(label)}</span><span className="os-metric-icon"><Component/></span></div><div className="os-metric-value">{String(value)}</div><div className="os-metric-foot"><b>{latest ? `Latest: ${latest.research_date}` : "No research run"}</b><span className="os-source-badge">AI WEB</span></div></article>; })}</section>
    <div className="os-tabs">{tabs.map(value => <button className={`os-tab ${tab === value ? "active" : ""}`} onClick={() => setTab(value)} key={value}>{value}</button>)}</div>
    {!latest ? <section className="os-card"><div className="os-empty"><div className="os-empty-icon"><Search/></div><h3>No keyword research yet</h3><p>Run research for a target market. The CMS will not display fabricated search-volume or ranking data.</p></div></section> : <>
      {tab === "Keyword Overview" && <section className="os-grid two"><article className="os-card"><div className="os-card-header"><div><h2>Primary Buyer Keywords</h2><p>{latest.market || "Global"} · {latest.provider || "Connected provider"}</p></div><label className="os-search-field"><Search/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filter keywords…"/></label></div><div className="os-card-body"><div className="os-list">{primary.map((item: any, index: number) => <div className="os-list-row" key={`${item.keyword}-${index}`}><span className="os-list-icon"><Search/></span><div className="os-list-main"><strong>{item.keyword}</strong><span>{item.intent || "Not classified"}</span></div><span className={`os-badge ${item.priority === "high" ? "pink" : "blue"}`}>{item.priority || "target"}</span><button className="os-icon-button" onClick={() => void copy(item.keyword)}>{copied === item.keyword ? <Check/> : <Copy/>}</button></div>)}</div></div></article><article className="os-card"><div className="os-card-header"><div><h2>Secondary Keywords</h2><p>Supporting terms from the same research run</p></div></div><div className="os-card-body"><div className="keyword-chip-grid">{secondary.map((item: string) => <button key={item} onClick={() => void copy(item)}>{copied === item ? <Check/> : <Copy/>}{item}</button>)}</div>{!secondary.length && <div className="os-empty compact"><p>No secondary terms returned.</p></div>}</div></article></section>}
      {tab === "Buyer Intent" && <section className="os-card"><div className="os-card-header"><div><h2>Intent Classification</h2><p>Use commercial and supplier-search terms first for lead-generation content.</p></div></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Keyword</th><th>Intent</th><th>Priority</th><th>Next Action</th></tr></thead><tbody>{primary.map((item: any, index: number) => <tr key={index}><td><strong>{item.keyword}</strong></td><td>{item.intent || "Not classified"}</td><td><span className="os-badge blue">{item.priority || "target"}</span></td><td><button className="os-btn soft" onClick={() => openStudio(item.keyword)}><ExternalLink/>Create Content Brief</button></td></tr>)}</tbody></table></div></section>}
      {tab === "Questions" && <section className="os-card"><div className="os-card-header"><div><h2>International Buyer Questions</h2><p>Questions discovered in the latest connected research run.</p></div></div><div className="os-card-body"><div className="os-list">{questions.map((question, index) => <div className="os-list-row" key={index}><span className="os-list-icon"><HelpCircle/></span><div className="os-list-main"><strong>{question}</strong><span>Ready for FAQ Intelligence review</span></div><button className="os-btn soft" onClick={() => void createFaq(question)}><Star/>Create FAQ Draft</button></div>)}</div>{!questions.length && <div className="os-empty compact"><p>No buyer questions returned.</p></div>}</div></section>}
      {tab === "Keyword Clusters" && <section className="os-grid three">{clusters.map(([intent, terms]) => <article className="os-card" key={intent}><div className="os-card-header"><div><h2>{intent}</h2><p>{terms.length} related terms</p></div></div><div className="os-card-body"><div className="keyword-chip-grid">{terms.map(term => <button key={term} onClick={() => openStudio(term)}><Target/>{term}</button>)}</div></div></article>)}</section>}
      {tab === "Content Opportunities" && <section className="os-card"><div className="os-card-header"><div><h2>Content Opportunities</h2><p>Open a real opportunity in AI Content Studio.</p></div></div><div className="os-card-body"><div className="os-list">{opportunities.map((item: any, index: number) => <button className="os-list-row keyword-opportunity" key={index} onClick={() => openStudio(item.primary_keyword || item.title, item.title)}><span className="os-list-icon"><Sparkles/></span><div className="os-list-main"><strong>{item.title || String(item)}</strong><span>{item.primary_keyword || "Keyword not supplied"}</span></div><span className="os-badge green">{item.content_type || "Content"}</span><ExternalLink/></button>)}</div></div></section>}
      {tab === "Research History" && <section className="os-card"><div className="os-card-header"><div><h2>Research History</h2><p>Saved research runs from Supabase.</p></div></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Date</th><th>Market</th><th>Primary Terms</th><th>Questions</th><th>Provider</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.research_date}</td><td>{row.market}</td><td>{row.primary_keywords?.length || 0}</td><td>{row.questions?.length || 0}</td><td>{row.provider || "—"}</td><td><span className="os-badge green">{row.status}</span></td></tr>)}</tbody></table></div></section>}
      {latest.source_summary && <section className="os-card"><div className="os-card-header"><div><h2>Research Source Summary</h2><p>Provider-supplied context for this run</p></div><Globe2/></div><div className="os-card-body"><p className="os-page-subtitle keyword-source-summary">{latest.source_summary}</p></div></section>}
    </>}
  </div></AdminShell>;
}
