"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { adminFetch } from "@/lib/admin-client";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, Mail, Plus, Save, Send, UsersRound } from "lucide-react";

type Subscriber=Record<string,any>;type Campaign=Record<string,any>;
export default function NewsletterPage(){
 const[subs,setSubs]=useState<Subscriber[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[working,setWorking]=useState(""),[error,setError]=useState(""),[toast,setToast]=useState("");
 const[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[audience,setAudience]=useState("subscribed"),[campaignId,setCampaignId]=useState<string>("");
 const load=useCallback(async()=>{setLoading(true);const[a,b]=await Promise.all([supabase.from("newsletter_subscribers").select("*").order("created_at",{ascending:false}).limit(1000),supabase.from("marketing_campaigns").select("*").in("campaign_type",["newsletter","email"]).order("created_at",{ascending:false}).limit(100)]);if(a.error)setError(a.error.message);else setSubs(a.data||[]);setCampaigns(b.error?[]:b.data||[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)},[toast]);
 const stats=useMemo(()=>({subscribed:subs.filter(x=>String(x.status).toLowerCase()==="subscribed").length,pending:subs.filter(x=>String(x.status).toLowerCase().includes("pending")).length,unsubscribed:subs.filter(x=>String(x.status).toLowerCase().includes("unsub")).length}),[subs]);
 const statCards=useMemo(()=>[
  {label:"Subscribers",value:stats.subscribed,note:"Permission-based audience",icon:UsersRound},
  {label:"Pending Opt-In",value:stats.pending,note:"Awaiting confirmation",icon:Mail},
  {label:"Unsubscribed",value:stats.unsubscribed,note:"Suppression list",icon:UsersRound},
  {label:"Campaigns",value:campaigns.length,note:"Saved email campaigns",icon:Mail},
  {label:"Open Rate",value:"—",note:"Available when provider tracking is connected",icon:Mail},
  {label:"Click Rate",value:"—",note:"Available when provider tracking is connected",icon:Mail},
 ],[stats,campaigns.length]);
 function reset(){setSubject("");setMessage("");setAudience("subscribed");setCampaignId("")}
 async function saveDraft(){if(!subject.trim()||!message.trim())return setError("Subject and message are required.");setWorking("save");setError("");const payload={name:subject,campaign_type:"newsletter",subject,target_audience:audience,content:message,channels:["email"],status:"draft",updated_at:new Date().toISOString()};const result=campaignId?await supabase.from("marketing_campaigns").update(payload).eq("id",campaignId).select().single():await supabase.from("marketing_campaigns").insert(payload).select().single();setWorking("");if(result.error)return setError(result.error.message);setCampaignId(String(result.data?.id||campaignId));setToast("Newsletter draft saved.");await load()}
 async function sendCampaign(){if(!subject.trim()||!message.trim())return setError("Subject and message are required.");if(!confirm(`Send this newsletter to ${stats.subscribed} subscribed contact${stats.subscribed===1?"":"s"}?`))return;setWorking("send");setError("");let id=campaignId;if(!id){const result=await supabase.from("marketing_campaigns").insert({name:subject,campaign_type:"newsletter",subject,target_audience:audience,content:message,channels:["email"],status:"approved",updated_at:new Date().toISOString()}).select().single();if(result.error){setWorking("");return setError(result.error.message)}id=String(result.data?.id||"");setCampaignId(id)}const response=await adminFetch("/api/admin/newsletter/send",{method:"POST",body:JSON.stringify({subject,message,audience,campaignId:id})});const data=await response.json();setWorking("");if(!response.ok)return setError(data.error||"Newsletter send failed.");setToast(`Sent to ${data.sent} subscriber${data.sent===1?"":"s"}${data.failed?`; ${data.failed} failed`:""}.`);await load()}
 return <AdminShell><div className="os-page newsletter-premium-page">
  <header className="os-page-header"><div><div className="os-page-eyebrow">Audience growth</div><h1 className="os-page-title">Newsletter</h1><p className="os-page-subtitle">Manage subscribers, consent status, campaign drafts and approved email sends from one workspace.</p></div><button className="os-btn primary" onClick={reset}><Plus/>Create Campaign</button></header>
  {error&&<div className="os-connection-strip"><Mail/><span>{error}</span></div>}
  <section className="os-grid six newsletter-stat-grid">{statCards.map((card)=>{const Icon=card.icon;return <article className="os-metric" key={card.label}><div className="os-metric-top"><span className="os-metric-label">{card.label}</span><span className="os-metric-icon"><Icon/></span></div><div className="os-metric-value">{String(card.value)}</div><div className="os-metric-foot"><b>{card.note}</b></div></article>})}</section>
  <div className="newsletter-main-grid"><section className="os-card"><div className="os-card-header"><div><h2>Subscriber Directory</h2><p>Locale, source and consent status.</p></div><span className="os-badge green">DOUBLE OPT-IN READY</span></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Email</th><th>Status</th><th>Language</th><th>Source</th><th>Subscribed</th></tr></thead><tbody>{subs.map(row=><tr key={row.id||row.email}><td><strong>{row.email}</strong></td><td><span className={`os-badge ${String(row.status).toLowerCase()==="subscribed"?"green":"amber"}`}>{row.status||"—"}</span></td><td>{row.language||"—"}</td><td>{row.source||"—"}</td><td>{row.created_at?new Date(row.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div>{!loading&&!subs.length&&<div className="os-empty"><UsersRound/><h3>No subscribers yet</h3><p>Website newsletter subscriptions will appear here automatically.</p></div>}</section>
  <section className="os-card newsletter-composer"><div className="os-card-header"><div><h2>Email Campaign</h2><p>Prepare, review, save and send a premium newsletter.</p></div></div><div className="os-card-body"><label className="os-label"><span>Saved Campaign</span><select value={campaignId} onChange={e=>{const id=e.target.value;setCampaignId(id);const c=campaigns.find(x=>String(x.id)===id);if(c){setSubject(String(c.subject||c.name||""));setMessage(String(c.content||""));setAudience(String(c.target_audience||"subscribed"))}}}><option value="">New campaign</option>{campaigns.map(c=><option value={c.id} key={c.id}>{c.subject||c.name}</option>)}</select></label><label className="os-label"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Premium salt market update"/></label><label className="os-label"><span>Audience</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option value="subscribed">All subscribed contacts</option><option value="confirmed">Confirmed subscribers</option></select></label><label className="os-label"><span>Message</span><textarea rows={12} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write or generate campaign copy…"/></label><div className="os-page-actions" style={{justifyContent:"flex-start"}}><button className="os-btn soft" onClick={()=>void saveDraft()} disabled={Boolean(working)}><Save/>{working==="save"?"Saving…":"Save Draft"}</button><button className="os-btn primary" onClick={()=>void sendCampaign()} disabled={Boolean(working)||stats.subscribed===0}><Send/>{working==="send"?"Sending…":"Approve & Send"}</button></div></div></section></div>
  {toast&&<div className="os-toast-stack"><div className="os-toast"><CheckCircle2/><strong>{toast}</strong></div></div>}
 </div></AdminShell>
}
