"use client";
import { useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, Copy, Eye, Plus, Save, Search, Sparkles, Trash2 } from "lucide-react";

type Faq={id?:string;question:string;answer:string;category:string;status:string;display_order:number;created_at?:string};
const blank:Faq={question:"",answer:"",category:"General",status:"draft",display_order:0};
export default function FaqManager(){
 const[rows,setRows]=useState<Faq[]>([]),[form,setForm]=useState<Faq>(blank),[editing,setEditing]=useState<string|null>(null),[search,setSearch]=useState("");
 async function load(){const{data}=await supabase.from("cms_faqs").select("*").order("display_order").order("created_at",{ascending:false});setRows((data as Faq[])||[])}
 useEffect(()=>{void load()},[]);
 async function save(){if(!form.question.trim()||!form.answer.trim())return alert("Question and answer are required.");const payload={...form,updated_at:new Date().toISOString()};const{error}=editing?await supabase.from("cms_faqs").update(payload).eq("id",editing):await supabase.from("cms_faqs").insert(payload);if(error)return alert(error.message);setForm(blank);setEditing(null);await load()}
 async function setStatus(id:string|undefined,status:string){if(!id)return;await supabase.from("cms_faqs").update({status,updated_at:new Date().toISOString()}).eq("id",id);await load()}
 async function remove(id:string|undefined){if(!id||!confirm("Delete this FAQ?"))return;await supabase.from("cms_faqs").delete().eq("id",id);await load()}
 const shown=useMemo(()=>rows.filter(r=>`${r.question} ${r.answer} ${r.category}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 return <AdminShell><div className="enterprise-page faq-admin"><header className="enterprise-page-header"><div><p className="enterprise-kicker">SEARCH & BUYER EDUCATION</p><h1>FAQ MANAGER</h1><p className="module-subcopy">Turn buyer questions into reviewed answers, approve them, and publish them on the website.</p></div><a href="/faqs" target="_blank" className="secondary-enterprise-button"><Eye/>Preview website FAQs</a></header>
 <section className="faq-workspace"><article className="executive-card faq-editor"><h2>{editing?"Edit FAQ":"Create FAQ draft"}</h2><label>Buyer question<input value={form.question} onChange={e=>setForm({...form,question:e.target.value})} placeholder="e.g. What is the MOQ for private label salt?"/></label><label>Answer<textarea value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} placeholder="Write a clear, factual answer for buyers."/></label><div className="faq-form-grid"><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="approved">Approved</option><option value="published">Published</option></select></label><label>Display order<input type="number" value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)})}/></label></div><div className="brief-actions"><button className="cms-gradient-button" onClick={save}><Save/>{editing?"Update FAQ":"Save FAQ draft"}</button>{editing&&<button className="secondary-enterprise-button" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></article>
 <article className="executive-card faq-queue"><div className="faq-toolbar"><div><h2>Review queue</h2><p>{shown.length} questions</p></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search FAQs…"/></label></div><div className="faq-list">{shown.map(row=><article key={row.id}><div className="faq-row-head"><span className={`status-badge ${row.status}`}>{row.status}</span><small>{row.category}</small></div><h3>{row.question}</h3><p>{row.answer}</p><div className="faq-actions"><button onClick={()=>navigator.clipboard.writeText(`${row.question}\n${row.answer}`)} title="Copy"><Copy/></button><button onClick={()=>{setEditing(row.id||null);setForm(row);window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button>{row.status!=="published"&&<button onClick={()=>setStatus(row.id,row.status==="draft"?"approved":"published")}><CheckCircle2/>{row.status==="draft"?"Approve":"Publish"}</button>}<button onClick={()=>remove(row.id)} className="danger"><Trash2/></button></div></article>)}{!shown.length&&<div className="empty-state"><Sparkles/>No FAQs yet. Create the first buyer answer.</div>}</div></article></section>
 <style jsx>{`.faq-workspace{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(0,1.4fr);gap:18px}.faq-editor{position:sticky;top:86px;height:max-content}.faq-editor label{display:grid;gap:7px;margin-top:14px;font-size:11px;font-weight:800}.faq-editor input,.faq-editor textarea,.faq-editor select{border:1px solid var(--cms-line);border-radius:13px;padding:12px;background:white}.faq-editor textarea{min-height:180px;resize:vertical}.faq-form-grid{display:grid;grid-template-columns:1fr 1fr 120px;gap:10px}.faq-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px}.faq-toolbar p{color:var(--cms-muted);font-size:11px}.faq-toolbar label{display:flex;align-items:center;gap:8px;border:1px solid var(--cms-line);border-radius:12px;padding:0 10px}.faq-toolbar input{border:0;padding:10px;outline:0}.faq-list{display:grid;gap:12px;margin-top:15px}.faq-list>article{border:1px solid var(--cms-line);border-radius:16px;padding:16px;background:#fbfcfe}.faq-row-head{display:flex;align-items:center;justify-content:space-between}.faq-row-head small{color:var(--cms-muted)}.faq-list h3{margin:11px 0 7px;font-size:15px}.faq-list p{color:var(--cms-muted);font-size:12px;line-height:1.65}.faq-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.faq-actions button{border:1px solid var(--cms-line);background:white;border-radius:10px;padding:8px 11px;display:flex;align-items:center;gap:6px;font-weight:800;font-size:11px}.faq-actions svg{width:15px}.faq-actions .danger{color:#c52d55}@media(max-width:1050px){.faq-workspace{grid-template-columns:1fr}.faq-editor{position:static}}@media(max-width:700px){.faq-form-grid{grid-template-columns:1fr}.faq-toolbar{align-items:stretch;flex-direction:column}}`}</style></div></AdminShell>
}
