"use client";

import { useCallback, useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { adminFetch } from "@/lib/admin-client";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, Eye, EyeOff, Plus, RefreshCw, Search, Sparkles, Trash2 } from "lucide-react";

type Faq = { id?: string; question: string; answer: string; category?: string|null; status: string; display_order?: number; source?: string|null; related_keyword?: string|null };
type Research = { id:string; question:string; ai_answer:string; recommended_category?:string; related_keyword?:string; source?:string; status?:string; target_country?:string };

export default function FAQIntelligencePage(){
 const[faqs,setFaqs]=useState<Faq[]>([]),[research,setResearch]=useState<Research[]>([]),[topic,setTopic]=useState("Himalayan pink salt buyer questions"),[loading,setLoading]=useState(true),[working,setWorking]=useState(""),[error,setError]=useState(""),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const[a,b]=await Promise.all([supabase.from("cms_faqs").select("*").order("display_order").order("created_at"),supabase.from("faq_research_questions").select("*").order("created_at",{ascending:false}).limit(30)]);if(a.error)setError(a.error.message);else setFaqs((a.data||[]) as Faq[]);if(b.error)setError(v=>v||b.error!.message);else setResearch((b.data||[]) as Research[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
 function update(index:number,patch:Partial<Faq>){setFaqs(items=>items.map((item,i)=>i===index?{...item,...patch}:item))}
 function addManual(){setFaqs(items=>[...items,{question:"",answer:"",category:"Buyer Questions",status:"draft",display_order:items.length}])}
 async function saveFaq(item:Faq,index:number){setWorking(`faq-${index}`);const payload={question:item.question.trim(),answer:item.answer.trim(),category:item.category||"Buyer Questions",status:item.status||"draft",display_order:item.display_order??index,source:item.source||"Manual",related_keyword:item.related_keyword||null,updated_at:new Date().toISOString()};if(!payload.question){setError("FAQ question is required.");setWorking("");return}const result=item.id?await supabase.from("cms_faqs").update(payload).eq("id",item.id).select().single():await supabase.from("cms_faqs").insert(payload).select().single();setWorking("");if(result.error){setError(result.error.message);return}update(index,result.data as Faq);setToast("FAQ saved to the website content registry.");window.dispatchEvent(new Event("salt-cms-updated"))}
 async function remove(item:Faq,index:number){if(item.id&&!confirm("Delete this FAQ?"))return;if(item.id){const{error}=await supabase.from("cms_faqs").delete().eq("id",item.id);if(error){setError(error.message);return}}setFaqs(items=>items.filter((_,i)=>i!==index));setToast("FAQ removed.")}
 async function runResearch(){setWorking("research");setError("");try{const response=await adminFetch("/api/faq/daily-research",{method:"POST",body:JSON.stringify({topic})});const payload=await response.json();if(!response.ok&&!payload.skipped)throw new Error(payload.error||"FAQ research failed.");await load();setToast(payload.skipped?"Today’s AI research is already available.":"Fresh buyer questions are ready for review.")}catch(reason){setError(reason instanceof Error?reason.message:"FAQ research failed.")}finally{setWorking("")}}
 async function addResearch(item:Research){setWorking(item.id);const{error:insertError}=await supabase.from("cms_faqs").insert({question:item.question,answer:item.ai_answer||"",category:item.recommended_category||"Buyer Questions",status:"draft",display_order:faqs.length,source:item.source||"AI Research",target_country:item.target_country||"Global",related_keyword:item.related_keyword||null,reference_notes:"Added from FAQ Intelligence research",updated_at:new Date().toISOString()});if(insertError)setError(insertError.message);else{await supabase.from("faq_research_questions").update({status:"Added to FAQ",approved_at:new Date().toISOString()}).eq("id",item.id);await load();setToast("Research question added as a website FAQ draft.")}setWorking("")}
 return <AdminShell><div className="os-page faq-intelligence-v2"><header className="os-page-header"><div><div className="os-page-eyebrow">Buyer Intelligence</div><h1 className="os-page-title">FAQ Intelligence</h1><p className="os-page-subtitle">Manage website questions manually or research the public web for current buyer-intent questions. Every AI suggestion stays under review before it appears on the website.</p></div><div className="os-page-actions"><button className="os-btn soft" onClick={addManual}><Plus/>Add Manual FAQ</button><button className="os-btn primary" onClick={()=>void runResearch()} disabled={Boolean(working)}><Sparkles/>{working==="research"?"Researching…":"AI Research Questions"}</button></div></header>{error&&<section className="os-card content-alert"><strong>FAQ Intelligence needs attention</strong><p>{error}</p></section>}
 <div className="faq-intelligence-layout"><section className="os-card"><div className="os-card-header"><div><h2>Website FAQ Editor</h2><p>Questions and answers are fully editable, publishable and hideable.</p></div><span className="os-badge green">{faqs.length} QUESTIONS</span></div><div className="os-card-body faq-editor-list">{loading?<div className="os-empty"><RefreshCw className="animate-spin"/></div>:faqs.map((item,index)=><article className="faq-editor-item" key={item.id||`new-${index}`}><div className="faq-editor-top"><strong>FAQ {String(index+1).padStart(2,"0")}</strong><div><button title={item.status==="published"?"Hide":"Publish"} onClick={()=>update(index,{status:item.status==="published"?"hidden":"published"})}>{item.status==="published"?<Eye/>:<EyeOff/>}</button><button title="Delete" onClick={()=>void remove(item,index)}><Trash2/></button></div></div><input value={item.question} onChange={e=>update(index,{question:e.target.value})} placeholder="Question"/><textarea rows={4} value={item.answer} onChange={e=>update(index,{answer:e.target.value})} placeholder="Answer"/><div className="faq-editor-footer"><select value={item.status} onChange={e=>update(index,{status:e.target.value})}><option value="draft">Draft</option><option value="published">Visible</option><option value="hidden">Hidden</option></select><input value={item.category||""} onChange={e=>update(index,{category:e.target.value})} placeholder="Category"/><button className="os-btn primary" onClick={()=>void saveFaq(item,index)} disabled={working===`faq-${index}`}><CheckCircle2/>Save</button></div></article>)}<button className="os-btn soft" onClick={addManual}><Plus/>Add another question</button></div></section>
 <aside className="os-card"><div className="os-card-header"><div><h2>AI Question Research</h2><p>Find likely buyer-intent FAQ angles using public web research.</p></div><span className="os-badge pink">RESEARCH WORKFLOW</span></div><div className="os-card-body"><label className="os-label"><span>Topic / Product</span><input value={topic} onChange={e=>setTopic(e.target.value)}/></label><button className="os-btn primary" style={{marginTop:12}} onClick={()=>void runResearch()} disabled={Boolean(working)}><Search/>Research Question Ideas</button><div className="faq-research-list">{research.filter(item=>item.status!=="Added to FAQ").map(item=><article key={item.id}><div><strong>{item.question}</strong><p>{item.ai_answer}</p><small>{item.related_keyword||item.recommended_category||"Buyer research"}</small></div><button className="os-btn soft" onClick={()=>void addResearch(item)} disabled={working===item.id}><Plus/>Add FAQ</button></article>)}{!research.length&&!loading&&<div className="os-empty"><Search/><h3>No research run yet</h3><p>Run AI research to discover current public buyer questions.</p></div>}</div></div></aside></div>{toast&&<div className="os-toast-stack"><div className="os-toast"><CheckCircle2/><div><strong>{toast}</strong></div></div></div>}</div></AdminShell>;
}
