"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { SocialPlatformIcon, socialPlatformOptions } from "@/components/SocialPlatformIcon";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, Eye, EyeOff, Plus, RefreshCw, Save, Trash2 } from "lucide-react";

type SocialLink={id?:string;platform:string;label:string;url:string;icon_key:string;enabled:boolean;display_order:number;updated_at?:string};
const empty=():SocialLink=>({platform:"facebook",label:"Facebook",url:"",icon_key:"facebook",enabled:true,display_order:0});
export default function SocialLinksPage(){
  const[rows,setRows]=useState<SocialLink[]>([]);const[form,setForm]=useState<SocialLink>(empty());const[editing,setEditing]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");const result=await supabase.from("social_links").select("*").order("display_order").order("created_at");if(result.error)setError(result.error.message);else setRows(result.data||[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(timer)},[toast]);
  const active=useMemo(()=>rows.filter(row=>row.enabled&&row.url).length,[rows]);
  function choosePlatform(value:string){const label=socialPlatformOptions.find(item=>item[0]===value)?.[1]||value;setForm(previous=>({...previous,platform:value,icon_key:value,label:previous.label&&previous.label!==socialPlatformOptions.find(item=>item[0]===previous.platform)?.[1]?previous.label:label}))}
  function edit(row:SocialLink){setEditing(row.id||null);setForm({...row});window.scrollTo({top:0,behavior:"smooth"})}
  function reset(){setEditing(null);setForm({...empty(),display_order:rows.length})}
  async function save(){if(!form.label.trim()||!form.url.trim()){setError("Platform name and profile link are required.");return}try{new URL(form.url)}catch{setError("Enter a complete public link beginning with https://");return}setSaving(true);setError("");const payload={platform:form.platform.trim().toLowerCase(),label:form.label.trim(),url:form.url.trim(),icon_key:(form.icon_key||form.platform).trim().toLowerCase(),enabled:form.enabled,display_order:Number(form.display_order)||0,updated_at:new Date().toISOString()};const result=editing?await supabase.from("social_links").update(payload).eq("id",editing):await supabase.from("social_links").insert(payload);setSaving(false);if(result.error){setError(result.error.message);return}window.dispatchEvent(new Event("salt-cms-updated"));setToast(editing?"Social profile updated":"Social profile added to the website footer");reset();await load()}
  async function toggle(row:SocialLink){const result=await supabase.from("social_links").update({enabled:!row.enabled,updated_at:new Date().toISOString()}).eq("id",row.id);if(result.error)setError(result.error.message);else{window.dispatchEvent(new Event("salt-cms-updated"));await load()}}
  async function remove(row:SocialLink){if(!confirm(`Remove ${row.label} from the website footer?`))return;const result=await supabase.from("social_links").delete().eq("id",row.id);if(result.error)setError(result.error.message);else{window.dispatchEvent(new Event("salt-cms-updated"));setToast("Social profile removed");await load()}}
  return <AdminShell><div className="os-page">
    <header className="os-page-header"><div><div className="os-page-eyebrow">Website social profiles</div><h1 className="os-page-title">Social Profile Links</h1><p className="os-page-subtitle">Add real profile links once. Enabled platform logos appear automatically in the public website footer.</p></div><div className="os-page-actions"><button className="os-btn soft" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?"animate-spin":""}/>Refresh</button><button className="os-btn primary" onClick={reset}><Plus/>Add Social Profile</button></div></header>
    {error&&<section className="os-card" style={{borderColor:"rgba(239,68,68,.35)"}}><div className="os-card-body"><strong>Social profile action failed</strong><p className="os-page-subtitle">{error}</p></div></section>}
    <section className="social-links-overview"><article><span>Saved Profiles</span><strong>{rows.length}</strong><small>Real CMS records</small></article><article><span>Visible in Footer</span><strong>{active}</strong><small>Enabled links</small></article></section>
    <div className="os-grid two" style={{alignItems:"start"}}><section className="os-card"><div className="os-card-header"><div><h2>{editing?"Edit Social Profile":"Add Social Profile"}</h2><p>Select a platform, paste its public profile URL and save.</p></div><SocialPlatformIcon platform={form.icon_key||form.platform}/></div><div className="os-card-body"><div className="os-form-grid"><label className="os-label"><span>Platform</span><select value={form.platform} onChange={event=>choosePlatform(event.target.value)}>{socialPlatformOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="os-label"><span>Display Name</span><input value={form.label} onChange={event=>setForm(previous=>({...previous,label:event.target.value}))}/></label><label className="os-label full"><span>Profile URL</span><input value={form.url} onChange={event=>setForm(previous=>({...previous,url:event.target.value}))} placeholder="https://www.linkedin.com/company/…"/></label><label className="os-label"><span>Display Order</span><input type="number" value={form.display_order} onChange={event=>setForm(previous=>({...previous,display_order:Number(event.target.value)}))}/></label><label className="os-label"><span>Visible in Website Footer</span><input type="checkbox" checked={form.enabled} onChange={event=>setForm(previous=>({...previous,enabled:event.target.checked}))} style={{width:22,height:22}}/></label></div><div className="os-page-actions" style={{marginTop:16,justifyContent:"flex-start"}}><button className="os-btn primary" onClick={()=>void save()} disabled={saving}><Save/>{saving?"Saving…":editing?"Update Profile":"Save Profile"}</button>{editing&&<button className="os-btn soft" onClick={reset}>Cancel</button>}</div></div></section>
    <section className="os-card"><div className="os-card-header"><div><h2>Website Footer Profiles</h2><p>Only enabled links with a valid URL are displayed.</p></div></div><div className="os-card-body">{rows.length?<div className="os-list">{rows.map(row=><div className="os-list-row" key={row.id}><span className="social-platform-logo"><SocialPlatformIcon platform={row.icon_key||row.platform}/></span><div className="os-list-main"><strong>{row.label}</strong><span>{row.url}</span></div><span className={`os-badge ${row.enabled?"green":""}`}>{row.enabled?"Visible":"Hidden"}</span><div className="os-row-actions"><button className="os-icon-button" onClick={()=>edit(row)} aria-label="Edit"><Save/></button><button className="os-icon-button" onClick={()=>void toggle(row)} aria-label={row.enabled?"Hide":"Show"}>{row.enabled?<EyeOff/>:<Eye/>}</button><button className="os-icon-button" onClick={()=>void remove(row)} aria-label="Delete"><Trash2/></button></div></div>)}</div>:<div className="os-empty"><h3>No social profile links yet</h3><p>Add a real profile to display its platform logo in the website footer.</p></div>}</div></section></div>
    {toast&&<div className="os-toast-stack"><div className="os-toast"><span className="os-toast-icon"><CheckCircle2/></span><div><strong>{toast}</strong><span>The public footer reads these records automatically.</span></div></div></div>}
  </div></AdminShell>
}
