"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { Mail,Phone,MapPin,MessageCircle } from "lucide-react";
import { FaInstagram,FaFacebookF,FaLinkedinIn,FaYoutube,FaTiktok,FaPinterestP,FaXTwitter } from "react-icons/fa6";
import { loadCmsImages,loadCmsText,loadSocialLinks } from "@/lib/cms";
import { supabase } from "@/lib/supabase-client";

type Settings={site_name?:string;contact_email?:string;whatsapp_number?:string;address?:string;footer_text?:string};
type Social={platform:string;label:string;url:string;icon_key:string};
const iconMap:Record<string,React.ReactNode>={whatsapp:<MessageCircle className="w-4 h-4"/>,instagram:<FaInstagram/>,facebook:<FaFacebookF/>,linkedin:<FaLinkedinIn/>,youtube:<FaYoutube/>,tiktok:<FaTiktok/>,pinterest:<FaPinterestP/>,x:<FaXTwitter/>};
export default function Footer(){
  const[settings,setSettings]=useState<Settings>({site_name:"The Salt Origin",contact_email:"thekhanandco@gmail.com",whatsapp_number:"92331281289",address:"Pakistan"});
  const[description,setDescription]=useState("Premium Himalayan Pink Salt supplier offering retail packaging, bulk supply and private label solutions for distributors, wholesalers and international buyers worldwide.");
  const[logo,setLogo]=useState("/logo.png");const[socials,setSocials]=useState<Social[]>([]);
  useEffect(()=>{void load();const handler=(e:Event)=>void load((e as CustomEvent<string>).detail);const refresh=()=>void load(localStorage.getItem("salt-language")||"en");window.addEventListener("salt-language-change",handler);window.addEventListener("salt-cms-updated",refresh);return()=>{window.removeEventListener("salt-language-change",handler);window.removeEventListener("salt-cms-updated",refresh)}},[]);
  async function load(lang=localStorage.getItem("salt-language")||"en"){const[{data},texts,images,links]=await Promise.all([supabase.from("site_settings").select("*").limit(1).maybeSingle(),loadCmsText("global",lang),loadCmsImages("global"),loadSocialLinks()]);if(data)setSettings(data);setDescription(texts["global.footer.description"]||data?.footer_text||description);setLogo(images["global.branding.logo"]?.url||"/logo.png");setSocials(links)}
  const whats=(settings.whatsapp_number||"92331281289").replace(/\D/g,"");
  const links=socials.length?socials:[{platform:"whatsapp",label:"WhatsApp",url:`https://wa.me/${whats}`,icon_key:"whatsapp"}];
  return <footer className="bg-[#3A3A3A] text-white"><div className="max-w-[1700px] mx-auto px-6 lg:px-16 py-7"><div className="grid lg:grid-cols-[1.8fr_1fr_1fr] gap-8"><div><div className="flex items-center gap-3"><img src={logo} alt={settings.site_name||"The Salt Origin"} className="w-16 h-16 object-contain"/><div><h3 className="text-xl font-black">{settings.site_name||"The Salt Origin"}</h3><p className="text-gray-300 text-xs">Himalayan Pink Salt Exporter</p></div></div><p className="text-gray-300 mt-4 leading-8 max-w-md">{description}</p><div className="flex flex-wrap gap-2 mt-4">{links.filter(item=>item.url).map(item=><Link key={item.platform} href={item.url} target="_blank" rel="noreferrer" aria-label={item.label} className="social">{iconMap[item.icon_key||item.platform]||<MessageCircle className="w-4 h-4"/>}</Link>)}</div></div><div><h4 className="font-bold text-lg mb-4">Quick Links</h4><ul className="space-y-2 text-gray-300"><li><Link href="/">Home</Link></li><li><Link href="/about">About Us</Link></li><li><Link href="/products">Products</Link></li><li><Link href="/private-label">Private Label</Link></li><li><Link href="/blog">Blog</Link></li><li><Link href="/contact">Contact</Link></li></ul></div><div><h4 className="font-bold text-lg mb-4">Contact Info</h4><div className="space-y-3 text-gray-300"><div className="flex gap-3"><Mail className="w-4 h-4 text-[#C23B4A]"/><span>{settings.contact_email}</span></div><div className="flex gap-3"><Phone className="w-4 h-4 text-[#C23B4A]"/><span>+{whats}</span></div><div className="flex gap-3"><MapPin className="w-4 h-4 text-[#C23B4A]"/><span>{settings.address}</span></div></div><Link href="/contact" className="inline-flex mt-5 bg-[#C23B4A] px-5 py-2.5 rounded-lg font-semibold">Request Quote</Link></div></div><div className="border-t border-white/10 mt-5 pt-4 flex flex-col sm:flex-row justify-between gap-2 text-gray-400 text-xs"><p>© 2026 {settings.site_name||"The Salt Origin"}. All Rights Reserved.</p><p>Premium Himalayan Pink Salt Supplier & Private Label Partner</p></div></div><style jsx>{`.social{width:40px;height:40px;border-radius:999px;border:1px solid rgba(255,255,255,.2);display:flex;align-items:center;justify-content:center}.social:hover{background:#C23B4A}`}</style></footer>
}
