"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase-client";
import { isLocalBrowserDevelopment } from "@/lib/local-development";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, KeyRound, LockKeyhole, Mail, ShieldCheck } from "lucide-react";

export default function AdminLoginPage() {
  const router = useRouter();
  const [mode,setMode]=useState<"login"|"forgot"|"recovery">("login");
  const [email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[newPassword,setNewPassword]=useState(""); const[confirmPassword,setConfirmPassword]=useState("");
  const[showPassword,setShowPassword]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const recovery=params.get("recovery")==="1";if(recovery)setMode("recovery");if(params.get("disabled")==="1")setError("Your CMS profile is pending or disabled. On localhost, sign in once more and the secure owner-recovery check will restore approved access when eligible.");void supabase.auth.getSession().then(({data})=>{if(data.session&&!recovery)router.replace("/admin")});const{data:listener}=supabase.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY")setMode("recovery")});return()=>listener.subscription.unsubscribe()},[router]);
  async function handleLogin(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const{data,error:loginError}=await supabase.auth.signInWithPassword({email,password});if(loginError||!data.session?.access_token)throw new Error("Unable to sign in with those credentials.");if(isLocalBrowserDevelopment()){const response=await fetch("/api/admin/local-access-recovery",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||"Local CMS access recovery failed.");}router.replace("/admin");router.refresh()}catch(reason){await supabase.auth.signOut({scope:"local"}).catch(()=>undefined);setError(reason instanceof Error?reason.message:"Unable to sign in.")}finally{setLoading(false)}}
  async function requestReset(event:FormEvent){event.preventDefault();setLoading(true);setError("");setMessage("");try{const response=await fetch("/api/auth/password-reset-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Request failed.");setMessage(payload.message||"Reset request submitted for administrator approval.")}catch(reason){setError(reason instanceof Error?reason.message:"Request failed.")}finally{setLoading(false)}}
  async function updatePassword(event:FormEvent){event.preventDefault();if(newPassword.length<8)return setError("Use at least 8 characters.");if(newPassword!==confirmPassword)return setError("Passwords do not match.");setLoading(true);setError("");const{error:updateError}=await supabase.auth.updateUser({password:newPassword});setLoading(false);if(updateError)return setError(updateError.message);setMessage("Password updated. You can now continue to the CMS.");window.setTimeout(()=>router.replace("/admin"),1000)}
  return <main className="premium-login-page final-login-page"><div className="premium-login-orb premium-login-orb-one"/><div className="premium-login-orb premium-login-orb-two"/><div className="login-mountain-watermark"/><section className="premium-login-card"><div className="premium-login-logo-wrap"><Image src="/salt-origin-logo.png" alt="The Salt Origin" width={180} height={150} priority/></div><div className="login-security"><ShieldCheck/>SECURE ENTERPRISE WORKSPACE</div><h1>{mode==="recovery"?<>CREATE NEW<br/>PASSWORD</>:<>THE SALT ORIGIN<br/>ENTERPRISE CMS</>}</h1>
    {mode==="login"&&<form onSubmit={handleLogin} className="premium-login-form"><label><span>Email address</span><div className="premium-login-input"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@thesaltorigin.com" required/></div></label><label><span>Password</span><div className="premium-login-input"><LockKeyhole/><input type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="premium-login-error">{error}</p>}<button className="premium-login-button" disabled={loading}>{loading?"Signing in…":"Sign in"}</button><button type="button" className="login-link-button" onClick={()=>{setMode("forgot");setError("");setMessage("")}}>Forgot password?</button></form>}
    {mode==="forgot"&&<form onSubmit={requestReset} className="premium-login-form"><p className="login-explainer">Enter the email connected to your CMS account. The request will appear for administrator approval before a recovery email is sent.</p><label><span>CMS Email</span><div className="premium-login-input"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div></label>{error&&<p className="premium-login-error">{error}</p>}{message&&<p className="premium-login-success"><CheckCircle2/>{message}</p>}<button className="premium-login-button" disabled={loading}><KeyRound/>{loading?"Submitting…":"Request Password Reset"}</button><button type="button" className="login-link-button" onClick={()=>setMode("login")}><ArrowLeft/>Back to sign in</button></form>}
    {mode==="recovery"&&<form onSubmit={updatePassword} className="premium-login-form"><label><span>New Password</span><div className="premium-login-input"><LockKeyhole/><input type={showPassword?"text":"password"} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></div></label><label><span>Confirm Password</span><div className="premium-login-input"><LockKeyhole/><input type={showPassword?"text":"password"} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="premium-login-error">{error}</p>}{message&&<p className="premium-login-success"><CheckCircle2/>{message}</p>}<button className="premium-login-button" disabled={loading}>{loading?"Updating…":"Save New Password"}</button></form>}
    <p className="premium-login-footer">PRIVATE BUSINESS OPERATIONS PLATFORM · THE SALT ORIGIN</p></section></main>;
}
