"use client";

import { useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { ImagePlus, Pencil, Save, Trash2 } from "lucide-react";

type Category = { id:number; name:string; slug:string; description:string; subtitle:string; image:string; status:string; display_order:number };
const blank = { name:"", slug:"", description:"", subtitle:"", image:"", status:"active", display_order:"0" };

export default function CategoriesPage(){
  const [items,setItems]=useState<Category[]>([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState<number|null>(null); const [uploading,setUploading]=useState(false);
  useEffect(()=>{void load()},[]);
  async function load(){const{data,error}=await supabase.from("categories").select("*").order("display_order");if(error)alert(error.message);setItems((data as Category[])||[])}
  function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
  async function upload(file?:File){if(!file)return;setUploading(true);const path=`categories/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error}=await supabase.storage.from("product-images").upload(path,file,{upsert:true});if(error)alert(error.message);else setForm(f=>({...f,image:supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl}));setUploading(false)}
  async function save(){if(!form.name.trim())return alert("Category name required");const payload={name:form.name,slug:form.slug||slugify(form.name),description:form.description,subtitle:form.subtitle,image:form.image,status:form.status,display_order:Number(form.display_order)||0,updated_at:new Date().toISOString()};const{error}=editing?await supabase.from("categories").update(payload).eq("id",editing):await supabase.from("categories").insert(payload);if(error)return alert(error.message);setForm(blank);setEditing(null);void load()}
  async function remove(id:number){if(!confirm("Delete category?"))return;await supabase.from("categories").delete().eq("id",id);void load()}
  return <AdminShell><div className="space-y-7"><div><p className="uppercase tracking-[5px] text-[#C23B4A] font-black text-xs">Products</p><h1 className="text-4xl font-black mt-2">Category Manager</h1><p className="text-slate-500 mt-2">Edit the category names, descriptions and images shown on the products page.</p></div>
  <section className="rounded-[26px] bg-white text-[#081325] border border-[#EFE3E5] p-6"><div className="grid md:grid-cols-2 gap-4"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:editing?form.slug:slugify(e.target.value)})} placeholder="Category name" className="border rounded-xl p-4"/><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Slug" className="border rounded-xl p-4"/><input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} placeholder="Short subtitle" className="border rounded-xl p-4"/><input value={form.display_order} onChange={e=>setForm({...form,display_order:e.target.value})} placeholder="Display order" className="border rounded-xl p-4"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="border rounded-xl p-4 md:col-span-2 h-28"/><input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="Image URL" className="border rounded-xl p-4"/><label className="inline-flex items-center justify-center gap-2 bg-[#081325] text-white rounded-xl p-4 font-black cursor-pointer"><ImagePlus className="w-5 h-5"/>{uploading?"Uploading...":"Upload Category Image"}<input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/></label></div>{form.image&&<img src={form.image} alt="Preview" className="mt-4 h-40 w-60 object-contain bg-[#FFF8F5] rounded-xl"/>}<button onClick={save} className="mt-5 inline-flex items-center gap-2 bg-[#C23B4A] text-white px-7 py-4 rounded-xl font-black"><Save className="w-5 h-5"/>{editing?"Update Category":"Add Category"}</button></section>
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{items.map(item=><article key={item.id} className="rounded-[24px] bg-white text-[#081325] border border-[#EFE3E5] p-5"><div className="h-48 bg-[#FFF8F5] rounded-xl flex items-center justify-center">{item.image&&<img src={item.image} alt={item.name} className="max-h-full max-w-full object-contain"/>}</div><h2 className="text-xl font-black mt-4">{item.name}</h2><p className="text-sm text-[#C23B4A] font-bold">{item.subtitle}</p><p className="text-sm text-slate-500 mt-2">{item.description}</p><div className="flex gap-2 mt-4"><button onClick={()=>{setEditing(item.id);setForm({name:item.name,slug:item.slug,description:item.description||"",subtitle:item.subtitle||"",image:item.image||"",status:item.status||"active",display_order:String(item.display_order||0)});window.scrollTo({top:0,behavior:"smooth"})}} className="p-3 bg-blue-50 text-blue-700 rounded-xl"><Pencil className="w-4 h-4"/></button><button onClick={()=>remove(item.id)} className="p-3 bg-red-50 text-red-600 rounded-xl"><Trash2 className="w-4 h-4"/></button></div></article>)}</div></div></AdminShell>;
}
