"use client";

import { useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { ImagePlus, Pencil, RefreshCw, Save, Trash2 } from "lucide-react";

type Category={id:number;name:string;slug:string;description:string;subtitle:string;image:string;status:string;display_order:number};
const blank={name:"",slug:"",description:"",subtitle:"",image:"",status:"active",display_order:"0"};
const websiteCategories=[
 {name:"Salt Shaker Bottles",slug:"salt-shaker-bottles",subtitle:"Fine grain PET shaker bottles",description:"Retail Himalayan pink salt shaker bottles in 100g, 200g and 250g formats.",image:"/retail-packaging.png",status:"active",display_order:10},
 {name:"Salt Jars",slug:"salt-jars",subtitle:"Fine grain PET retail jars",description:"Retail PET jars in 500g, 750g, 1kg and 2kg formats.",image:"/pet-jars.png",status:"active",display_order:20},
 {name:"Stand-Up Pouches",slug:"stand-up-pouches",subtitle:"Fine grain zip-lock pouches",description:"Retail and e-commerce stand-up pouches in 250g, 500g and 1kg formats.",image:"/pouches.png",status:"active",display_order:30},
 {name:"Plastic Grinder Bottles",slug:"plastic-grinder-bottles",subtitle:"Coarse salt with plastic grinder",description:"Plastic grinder-cap bottles in 100g, 200g, 225g, 360g and 500g formats.",image:"/grinder-bottles.png",status:"active",display_order:40},
 {name:"Ceramic Grinder Bottles",slug:"ceramic-grinder-bottles",subtitle:"Coarse salt with ceramic grinder",description:"Premium ceramic grinder bottles in 100g, 200g, 225g, 360g and 500g formats.",image:"/ceramic-grinders.png",status:"active",display_order:50},
 {name:"Bulk Fine Grain Salt",slug:"bulk-fine-grain-salt",subtitle:"Fine grain industrial supply",description:"Fine grain Himalayan pink salt in 5kg, 10kg, 20kg, 25kg, 30kg and 50kg bulk bags.",image:"/white-sack.png",status:"active",display_order:60},
 {name:"Bulk Coarse Grain Salt",slug:"bulk-coarse-grain-salt",subtitle:"Coarse grain industrial supply",description:"Coarse grain Himalayan pink salt in 5kg, 10kg, 20kg, 25kg, 30kg and 50kg bulk bags.",image:"/white-sack.png",status:"active",display_order:70},
 {name:"Private Label Solutions",slug:"private-label-solutions",subtitle:"Custom labels and packaging",description:"Buyer-specific labels, bottles, pouches, cartons and export-ready private-label programs.",image:"/custom-packaging.png",status:"active",display_order:80},
];
export default function CategoriesPage(){
 const[items,setItems]=useState<Category[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[uploading,setUploading]=useState(false),[syncing,setSyncing]=useState(false),[search,setSearch]=useState("");
 useEffect(()=>{void load()},[]);async function load(){const{data,error}=await supabase.from("categories").select("*").order("display_order");if(error)alert(error.message);setItems((data as Category[])||[])}
 function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
 async function upload(file?:File){if(!file)return;setUploading(true);const path=`categories/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error}=await supabase.storage.from("product-images").upload(path,file,{upsert:true});if(error)alert(error.message);else setForm(f=>({...f,image:supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl}));setUploading(false)}
 async function save(){if(!form.name.trim())return alert("Category name required");const payload={name:form.name,slug:form.slug||slugify(form.name),description:form.description,subtitle:form.subtitle,image:form.image,status:form.status,display_order:Number(form.display_order)||0,updated_at:new Date().toISOString()};const{error}=editing?await supabase.from("categories").update(payload).eq("id",editing):await supabase.from("categories").insert(payload);if(error)return alert(error.message);setForm(blank);setEditing(null);void load()}
 async function remove(id:number){if(!confirm("Delete category?"))return;const{error}=await supabase.from("categories").delete().eq("id",id);if(error)return alert(error.message);void load()}
 async function syncWebsiteCategories(){setSyncing(true);const{error}=await supabase.from("categories").upsert(websiteCategories,{onConflict:"slug"});setSyncing(false);if(error)return alert(error.message);await load();alert("Website categories synchronized. Shakers, jars, pouches, plastic grinders, ceramic grinders, bulk fine grain, bulk coarse grain and private label are separately editable.")}
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.subtitle} ${x.slug}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 return <AdminShell><div className="os-page legacy-unified-page category-manager-page enterprise-page"><header className="enterprise-page-header"><div><p className="enterprise-kicker">Product Taxonomy</p><h1>Category Manager</h1><p className="module-subcopy">Every storefront collection has its own editable category, image, text and display order.</p></div><button onClick={syncWebsiteCategories} disabled={syncing} className="cms-gradient-button"><RefreshCw/>{syncing?"Synchronizing…":"Sync website categories"}</button></header>
 <section className="executive-card"><div className="brief-grid"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:editing?form.slug:slugify(e.target.value)})} placeholder="Category name"/><input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Slug"/><input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} placeholder="Short subtitle"/><input value={form.display_order} onChange={e=>setForm({...form,display_order:e.target.value})} placeholder="Display order"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description"/><input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="Image URL"/><label className="cms-gradient-button"><ImagePlus/>{uploading?"Uploading…":"Upload category image"}<input type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0])}/></label></div>{form.image&&<img src={form.image} alt="Preview" className="category-edit-preview"/>}<button onClick={save} className="cms-gradient-button"><Save/>{editing?"Update category":"Add category"}</button></section>
 <section className="category-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search categories…"/><strong>{filtered.length} editable categories</strong></section>
 <section className="category-enterprise-grid">{filtered.map(item=><article key={item.id} className="executive-card"><div className="category-image-wrap">{item.image?<img src={item.image} alt={item.name}/>:<ImagePlus/>}</div><div className="category-order">#{item.display_order}</div><h2>{item.name}</h2><b>{item.subtitle}</b><p>{item.description}</p><small>/{item.slug}</small><div className="brief-actions"><button onClick={()=>{setEditing(item.id);setForm({name:item.name,slug:item.slug,description:item.description||"",subtitle:item.subtitle||"",image:item.image||"",status:item.status||"active",display_order:String(item.display_order||0)});window.scrollTo({top:0,behavior:"smooth"})}} className="secondary-enterprise-button"><Pencil/>Edit</button><button onClick={()=>remove(item.id)} className="secondary-enterprise-button"><Trash2/>Delete</button></div></article>)}</section>
 <style jsx>{`.category-toolbar{display:flex;align-items:center;justify-content:space-between;margin:20px 0}.category-toolbar input{min-width:300px;border:1px solid var(--line);background:var(--surface);padding:13px 15px;border-radius:13px}.category-enterprise-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.category-image-wrap{height:190px;border-radius:16px;background:var(--surface-2);display:grid;place-items:center;overflow:hidden}.category-image-wrap img{width:100%;height:100%;object-fit:contain}.category-order{float:right;margin-top:12px;font-size:10px;color:var(--muted)}.category-enterprise-grid h2{margin-top:16px}.category-enterprise-grid b{display:block;color:#bd3e63;font-size:11px;margin-top:5px}.category-enterprise-grid p{color:var(--muted);font-size:12px;line-height:1.65;min-height:60px}.category-enterprise-grid small{color:var(--muted)}.category-edit-preview{width:220px;height:130px;object-fit:contain;background:var(--surface-2);border-radius:14px;margin:15px 0}@media(max-width:1050px){.category-enterprise-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.category-enterprise-grid{grid-template-columns:1fr}.category-toolbar{align-items:stretch;flex-direction:column;gap:10px}.category-toolbar input{min-width:0}}`}</style></div></AdminShell>}
