"use client";

import { useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { BookOpen, FileText, LineChart, PackageSearch, Search, ShieldCheck, Sparkles, Share2, Link2, Mail, ChevronRight, ListTodo, MonitorSmartphone, Image as ImageIcon, FileCheck2, FileSpreadsheet, Truck, Cable, UsersRound, Target, MessageSquareText } from "lucide-react";

const guides = [
  {icon:ListTodo,title:"Team Tasks",summary:"Assign, prioritize and follow team work from one board.",steps:["Select Add Task and enter the task title and full description.","Choose the responsible staff member, priority, status, labels and work list.","Set due date/time and an optional reminder. Enable browser reminders if you want local notifications.","Use recurring rules only for genuinely repeated work.","Update status from the task card as work moves through To Do, In Progress, Waiting, Review and Completed.","Use the team avatars, search and filters to review one employee or overdue work quickly."]},
  {icon:Sparkles,title:"AI Content Studio",summary:"Turn one researched buyer topic into a blog and platform-specific social package.",steps:["Open the studio each morning. The scheduled daily workflow creates or loads today's researched content pack.","Review the topic, target market, buyer intent, primary keyword and SEO/GEO scores before editing copy.","Open each social platform tab. The CMS adapts copy to that platform's character target and maximum length.","Create a square campaign image with AI or upload your own image; the preview keeps the full image visible.","Open Full Review to check the complete blog, keywords, SEO/GEO quality and selected publishing destinations.","Choose Draft, Reject or Approve. Website approval publishes the blog; selected social approvals move those versions into their publishing queue."]},
  {icon:BookOpen,title:"Blog Center",summary:"Review the daily buyer-focused blog before publishing it to the website.",steps:["The daily automation creates one concise buyer-focused blog draft, not a long-form article.","Open Review to inspect title, excerpt, content, primary/secondary keywords, SEO score and GEO score.","Use Edit + Image to revise copy and upload a square image or create a topic-related image with AI.","Keep uncertain content in Draft or move it to Review after fact checking.","Approve only verified content. Publish to Website changes the blog status to published and makes it available to the public blog feed.","Use rejected status for topics that should not be published or reused."]},
  {icon:MessageSquareText,title:"FAQ Intelligence",summary:"Manage live FAQs and research new buyer questions.",steps:["Existing website FAQ questions appear in the Website FAQ Editor.","Edit the question or answer, then save it; use Hide when a question should remain in the database but disappear from the website.","Delete only questions that are no longer required.","Use Add Manual FAQ when sales or operations identifies a useful buyer question.","Use AI Research Questions to research likely buyer-intent questions from connected search/AI sources.","Review each suggestion, then add it to the FAQ editor as a draft before publishing it to the website."]},
  {icon:MonitorSmartphone,title:"Website Visual Editor",summary:"Control page sections without changing source code.",steps:["Select the website page you want to edit.","Use the eye control to show or hide a section.","Use Up and Down controls to reorder sections on the live page.","Adjust minimum height and top/bottom spacing only when the section needs more or less visual space.","Use the preview frame in desktop, tablet and mobile widths before saving.","Save changes, then open the live page to verify that the new order and spacing are correct."]},
  {icon:FileText,title:"Website Text Manager",summary:"Edit every mapped page and section with typography controls.",steps:["Choose a page from the left panel. Every mapped section appears as a separate card.","Edit Eyebrow, Heading, Accent/Italic segment, subtext, buttons and supporting copy in their own fields.","Use the font selector, weight, italic, underline, size, color, highlight, alignment, case, line-height and letter-spacing controls beside the text field.","Mixed headings keep the normal and accent/italic segments separate so each can have its own color and font style.","Preview changes before saving when editing major headings.","Save Text Changes and confirm the result on the live page."]},
  {icon:ImageIcon,title:"Images Manager",summary:"See and replace every mapped website image page-by-page.",steps:["Choose the website page and then the section from the filters.","The card shows the image currently visible on the website, recommended size and live/hidden state.","Choose Upload / Replace to use an image from your computer; uploaded files are stored in the existing site-media storage.","Choose Create with AI to generate a brand-matched image for that exact slot.","Edit ALT text for accessibility and SEO.","Use Hide/Show to control visibility, Reset to restore the original mapped image, and Open Live Page to verify the result."]},
  {icon:FileCheck2,title:"Certifications & Buyer Requests",summary:"Manage verified documents and controlled buyer access.",steps:["Upload or replace only certificates and reports that the company can verify.","Public visitors can submit a document request with name, company, designation, email/WhatsApp and the documents required.","Review each request in the Certifications page and select the exact approved documents to release.","Approve & Send uses the configured email service and WhatsApp integration when available.","If automated WhatsApp delivery is unavailable, use the generated WhatsApp handoff link without exposing private files publicly.","Keep expired, superseded or restricted documents unavailable to public requests."]},
  {icon:FileSpreadsheet,title:"Quotations & Export Documents",summary:"Build professional A4 B2B documents with a live letterhead preview.",steps:["Choose the correct document type: quotation, proforma invoice, commercial invoice, packing list, sales contract, order confirmation, sample invoice, COA cover, certificate of origin, specification sheet or other listed export document.","Complete seller, buyer, document number, dates, currency, Incoterm, ports and payment/delivery terms.","Add line items, packaging, quantity, unit price and weights where the selected document requires them.","The A4 preview updates while you type so you can verify the final letterhead composition before saving.","Use the approved company letterhead from Settings or upload a replacement before producing final documents.","Save for review, then print/PDF or send only after commercial approval."]},
  {icon:Mail,title:"Email Reply Assistant",summary:"Draft buyer replies using inquiry and commercial-sheet data.",steps:["Select the incoming inquiry or buyer request.","The assistant loads the buyer contact details and matches requested products where possible.","Commercial prices and product information are read from the Product Commercial Sheet; review them before generation.","Generate Reply to create a professional response, then edit any commercial terms that require human judgement.","Save as Draft if the message needs internal review.","Approve & Send emails the approved reply to the buyer through the configured Resend account and records the activity."]},
  {icon:PackageSearch,title:"Product Commercial Sheet",summary:"Keep controlled product pricing and export reference data.",steps:["Create one commercial record per product/packaging combination.","Maintain export reference, pack size, packaging, currency, cost, expected selling price, FOB price, private-label price, margin, MOQ, lead time and notes.","Use role-based access because this is internal commercial information.","The Email Reply Assistant and quotation workflow can use these records to prepare buyer responses.","Update pricing as soon as approved commercial rates change."]},
  {icon:Truck,title:"Production & Shipments",summary:"Track approved orders from production through delivery.",steps:["Create or update an order only after the commercial workflow is approved.","Move the order through Production Planning, Quality & Packing, Export Documents, Dispatch and Shipment Tracking.","Store client, tracking reference, carrier, ETD, ETA, ports and document actions on the shipment record.","Open the shipment map in full screen for operational review. Live positions appear only when a carrier/tracking provider is connected.","Use the real carrier tracking URL for external verification until live map data is connected.","Mark completed only after delivery confirmation."]},
  {icon:Share2,title:"Social Media Studio",summary:"Review platform-native versions and previews before publishing.",steps:["The daily social automation prepares one campaign topic and platform versions for every enabled channel.","Select a platform from the left list to edit its title/caption, hashtags/keywords and image prompt.","Watch the character counter: each platform has its own maximum and recommended length.","The right-side preview shows how the selected image and copy will be presented.","Approve, reject or schedule each version independently.","Only approved content enters the publishing queue; actual posting requires the relevant social API/OAuth connection."]},
  {icon:Link2,title:"Social Profile Links",summary:"Control website social icons and profile destinations.",steps:["Select a platform and paste the complete public profile URL.","Save the record, then keep Visible enabled if the platform should appear in the website footer and other mapped social areas.","Use Hide to keep the record without showing the public icon.","Edit the URL whenever the official profile changes.","Add another platform when required; supported platform icons are supplied by the CMS."]},
  {icon:Target,title:"Campaigns & Content Calendar",summary:"Keep blog, social and B2B CTA work under one commercial campaign.",steps:["Create a campaign with market, buyer, objective, channels and schedule.","Use the 7-Day Content Pulse to see current and upcoming campaign slots.","Link related blog and social work to the same campaign so messaging stays consistent.","Move campaigns through Draft, Review, Approved, Scheduled, Active and Completed states.","Open the campaign record to update CTA links, subject lines and channel notes."]},
  {icon:Mail,title:"Newsletter",summary:"Manage subscribers and send approved campaigns.",steps:["Website subscriptions appear automatically in the Subscriber Directory with source, language and status.","Never send to unsubscribed contacts.","Create or load a campaign, enter subject, audience and message, then Save Draft.","Review the message and recipient count before choosing Approve & Send.","The configured Resend account sends the campaign and the CMS records the result in Activity Logs.","Open/click rates display only when provider tracking is connected; the CMS does not invent analytics."]},
  {icon:Cable,title:"Integrations",summary:"Check the real connection state without exposing secrets.",steps:["Open Integrations and find the service you need.","Configured means the required server-side environment variables or stored connection are present.","Choose Configure to see missing configuration names; secret values are never displayed.","After updating .env.local or Vercel Environment Variables, use Check Connection.","External tools open their official service page instead of storing fake connection states."]},
  {icon:UsersRound,title:"Access, Roles & Activity",summary:"Control staff permissions and review who changed what.",steps:["Invite a separate CMS user for each staff member; do not share administrator credentials.","Assign the minimum role needed for the employee's work.","Disable access immediately when it is no longer required.","Use Activity Logs to filter by employee, module and date range.","Review sensitive actions such as publishing, commercial changes, document release, email sends and access changes regularly.","Password-reset requests appear for administrator approval before the recovery email is sent."]},
  {icon:LineChart,title:"Analytics",summary:"Understand real GA4 and Search Console measurements.",steps:["Live Now comes from the GA4 Realtime report when GA4 credentials are connected.","Users, sessions, page views and engagement use the selected reporting period.","Search clicks, impressions, queries and average position come from Search Console.","Zero means the connected source returned zero or the event is not configured; missing services are shown as connection-required.","Do not treat social or shipment metrics as live unless their provider API is connected."]},
  {icon:ShieldCheck,title:"Daily Governance",summary:"Recommended review routine before anything publishes or leaves the company.",steps:["Review Team Tasks, leads and operational reminders.","Review today's AI blog, FAQ suggestions and social pack.","Verify facts, product claims, pricing, certificates and images before approval.","Check quotations/email replies before sending them to buyers.","Review production/shipment records and outstanding documents.","Check Activity Logs for unusual changes and close the day with approved work clearly assigned."]},
];

export default function HelpPage(){
  const [query,setQuery]=useState("");
  const [open,setOpen]=useState(guides[0].title);
  const filtered=useMemo(()=>guides.filter(g=>`${g.title} ${g.summary} ${g.steps.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const selected=filtered.find(g=>g.title===open) || filtered[0];
  const SelectedIcon=selected?.icon;
  return <AdminShell><div className="os-page help-guide-page">
    <header className="os-page-header"><div><div className="os-page-eyebrow">Team knowledge base</div><h1 className="os-page-title">Help & Guide</h1><p className="os-page-subtitle">Clear operating instructions for website editing, content review, quotations, social publishing, analytics and daily CMS control.</p></div><label className="os-search-field help-guide-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search workflow guides…"/></label></header>
    <section className="help-guide-grid">{filtered.map(({icon:Icon,title,summary})=><button key={title} className={`os-card help-guide-tile ${selected?.title===title?"active":""}`} onClick={()=>setOpen(title)}><span className="os-list-icon"><Icon/></span><span><strong>{title}</strong><small>{summary}</small></span><ChevronRight/></button>)}</section>
    {selected?<section className="os-card help-guide-detail"><div className="os-card-header"><div className="help-guide-heading"><span className="os-list-icon">{SelectedIcon&&<SelectedIcon/>}</span><div><div className="os-page-eyebrow">Operating guide</div><h2>{selected.title}</h2><p>{selected.summary}</p></div></div></div><div className="os-card-body"><ol>{selected.steps.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,"0")}</b><span>{step}</span></li>)}</ol></div></section>:<div className="os-empty"><div className="os-empty-icon"><BookOpen/></div><h3>No guide found</h3><p>No help guide matches the current search.</p></div>}
  </div></AdminShell>;
}
