"use client";

import { useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { BookOpen, FileText, LineChart, PackageSearch, Search, ShieldCheck, Sparkles, Share2, Link2, Mail, ChevronRight } from "lucide-react";

const guides = [
  {icon:Sparkles,title:"AI Content Studio",summary:"Research, create, illustrate and publish website blogs.",steps:["Enter a topic or primary keyword in New AI Blog Brief.","Run keyword and competitor research. The studio finds buyer-intent, secondary and long-tail phrases.","Create Review Draft. Researched keywords are placed naturally in the SEO title, introduction, headings, body and FAQ.","Review facts, slug, meta description and keyword chips before approval.","Select Create AI Image. The CMS tries the configured OpenAI image model and stores the resulting featured image.","Choose Approve & Publish to make the post live, or keep it as a draft for revision."]},
  {icon:Share2,title:"Social Media Publishing",summary:"Prepare complete campaigns before external APIs are connected.",steps:["Enter the campaign topic.","Generate platform-specific captions, keywords, hashtags and CTA copy.","Create a topic-related AI image from the same campaign screen.","Review the visual and text preview.","Save as draft or approve and schedule.","Once external platform APIs are connected, approved posts publish through the same queue."]},
  {icon:LineChart,title:"Analytics",summary:"Understand every number displayed in the CMS.",steps:["Live Now is requested from the GA4 Realtime report.","Users, sessions, page views, engagement and bounce rate cover the selected reporting period.","Top pages, countries, devices and traffic channels are returned by GA4.","Search queries and average ranking position come from Google Search Console, not GA4.","Zero means the connected API returned zero or the event has not been configured.","The CMS must never replace missing analytics with sample visitor numbers."]},
  {icon:FileText,title:"Business Documents",summary:"Create branded A4 quotations and export documents for The Salt Origin.",steps:["Open document settings and confirm The Salt Origin company details, logo, address and contact information.","Use the live The Salt Origin A4 letterhead or upload an approved replacement in Settings.","Enter seller and buyer details, document number, dates, Incoterm, currency and payment terms.","Add line items, quantities, packing, weights and prices.","The preview shows the same A4 composition used for printing.","Select Print / PDF and keep paper size A4, margins None and scale 100%."]},
  {icon:PackageSearch,title:"Products & Categories",summary:"Keep every storefront product collection separately editable.",steps:["Products are B2B information records used on the website and in quotations.","Categories control the public website product groups and navigation labels.","Create only the categories actually required by the public website and assign published products to them.","Edit each category title, subtitle, description, image, slug and display order independently.","Use clear names, live images, descriptions, SEO fields and display order for every category."]},
  {icon:Link2,title:"Backlink Intelligence",summary:"Find genuine off-page SEO opportunities.",steps:["Enter the target keyword and market.","Research ranking articles, industry publications, directories and supplier portals.","Review content gaps and referring-domain opportunities.","Use the opportunity list for directory submission, supplier profiles, editorial outreach and guest articles.","The system does not create fake backlinks.","A backlink is marked acquired only after the external website publishes it."]},
  {icon:Mail,title:"Newsletter",summary:"Manage website subscribers and future campaigns.",steps:["Visitors subscribe from the public website footer.","The email is saved in Newsletter with source, language and subscription status.","Use filters to review active and unsubscribed contacts.","Export only for legitimate business use.","Respect unsubscribe status before sending any campaign."]},
  {icon:ShieldCheck,title:"Roles, Security & Audit",summary:"Control staff access and accountability.",steps:["Create a separate user for each worker.","Assign only required module permissions.","Use Audit Logs to review create, update, publish and delete activity.","Remove access immediately when it is no longer required."]},
  {icon:BookOpen,title:"Daily Operations",summary:"Recommended daily CMS control routine.",steps:["Review live analytics, inquiries and system health.","Check keyword research, Blog Center drafts and FAQ Intelligence suggestions.","Verify every fact and image, then move suitable content through Review, Approved and Published statuses.","Review social drafts and schedule approved posts.","Update quotations, client records and carrier tracking before closing the day."]},
];

export default function HelpPage(){
  const [query,setQuery]=useState("");
  const [open,setOpen]=useState(guides[0].title);
  const filtered=useMemo(()=>guides.filter(g=>`${g.title} ${g.summary} ${g.steps.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const selected=filtered.find(g=>g.title===open) || filtered[0];
  const SelectedIcon=selected?.icon;
  return <AdminShell><div className="os-page help-guide-page">
    <header className="os-page-header"><div><div className="os-page-eyebrow">Team knowledge base</div><h1 className="os-page-title">Help & Guide</h1><p className="os-page-subtitle">Clear operating instructions for website editing, content review, quotations, social publishing, analytics and daily CMS control.</p></div><label className="os-search-field help-guide-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search workflow guides…"/></label></header>
    <section className="help-guide-grid">{filtered.map(({icon:Icon,title,summary})=><button key={title} className={`os-card help-guide-tile ${selected?.title===title?"active":""}`} onClick={()=>setOpen(title)}><span className="os-list-icon"><Icon/></span><span><strong>{title}</strong><small>{summary}</small></span><ChevronRight/></button>)}</section>
    {selected?<section className="os-card help-guide-detail"><div className="os-card-header"><div className="help-guide-heading"><span className="os-list-icon">{SelectedIcon&&<SelectedIcon/>}</span><div><div className="os-page-eyebrow">Operating guide</div><h2>{selected.title}</h2><p>{selected.summary}</p></div></div></div><div className="os-card-body"><ol>{selected.steps.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,"0")}</b><span>{step}</span></li>)}</ol></div></section>:<div className="os-empty"><div className="os-empty-icon"><BookOpen/></div><h3>No guide found</h3><p>No help guide matches the current search.</p></div>}
  </div></AdminShell>;
}
