"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { CalendarDays, CheckCircle2, Edit3, Plus, Save, Target, Trash2, X } from "lucide-react";

type Campaign = Record<string, any>;
type CampaignForm = { name:string; campaign_type:string; objective:string; target_countries:string; target_audience:string; channels:string; landing_page:string; subject:string; content:string; scheduled_at:string; status:string };
const emptyForm=():CampaignForm=>({name:"",campaign_type:"Export Market Campaign",objective:"",target_countries:"",target_audience:"Importer / Distributor",channels:"Blog, Social",landing_page:"",subject:"",content:"",scheduled_at:"",status:"draft"});
const types=["Export Market Campaign","New Product Launch","Private Label Campaign","Trade Show Campaign","Distributor Outreach","Certification Announcement","Seasonal Content Campaign","email","newsletter"];
const statuses=["draft","review","approved","scheduled","active","completed","paused","archived"];
function listValue(value:unknown){return Array.isArray(value)?value.join(", "):String(value||"")}
function toArray(value:string){return value.split(",").map(item=>item.trim()).filter(Boolean)}
function pretty(value:unknown){return String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function dayKey(value?:string){const date=value?new Date(value):new Date();return Number.isNaN(date.getTime())?"":date.toISOString().slice(0,10)}

export default function CampaignsPage(){
  const[rows,setRows]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[toast,setToast]=useState("");
  const[modal,setModal]=useState(false),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<CampaignForm>(emptyForm());
  const load=useCallback(async()=>{setLoading(true);setError("");const result=await supabase.from("marketing_campaigns").select("*").order("created_at",{ascending:false}).limit(200);if(result.error)setError(result.error.message);else setRows(result.data||[]);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]); useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
  const week=useMemo(()=>Array.from({length:7},(_,index)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()+index);const key=dayKey(date.toISOString());return{date,key,items:rows.filter(row=>dayKey(row.scheduled_at||row.created_at)===key)}}),[rows]);
  const openNew=()=>{setEditing(null);setForm(emptyForm());setModal(true)};
  const openEdit=(row:Campaign)=>{setEditing(row.id);setForm({name:String(row.name||""),campaign_type:String(row.campaign_type||"Export Market Campaign"),objective:String(row.objective||""),target_countries:listValue(row.target_countries),target_audience:String(row.target_audience||""),channels:listValue(row.channels),landing_page:String(row.landing_page||""),subject:String(row.subject||""),content:String(row.content||""),scheduled_at:row.scheduled_at?new Date(row.scheduled_at).toISOString().slice(0,16):"",status:String(row.status||"draft")});setModal(true)};
  async function save(){if(!form.name.trim())return setError("Campaign name is required.");setError("");const payload={...form,target_countries:toArray(form.target_countries),channels:toArray(form.channels),scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():null,updated_at:new Date().toISOString()};const result=editing?await supabase.from("marketing_campaigns").update(payload).eq("id",editing):await supabase.from("marketing_campaigns").insert(payload);if(result.error)return setError(result.error.message);setModal(false);setToast(editing?"Campaign updated.":"Campaign created.");await load()}
  async function remove(row:Campaign){if(!confirm(`Delete ${row.name||"this campaign"}?`))return;const result=await supabase.from("marketing_campaigns").delete().eq("id",row.id);if(result.error)setError(result.error.message);else{setToast("Campaign deleted.");await load()}}
  return <AdminShell><div className="os-page campaigns-premium-page">
    <header className="os-page-header"><div><div className="os-page-eyebrow">Marketing operations</div><h1 className="os-page-title">Campaigns & Content Calendar</h1><p className="os-page-subtitle">Link blog, social, image and B2B lead-CTA work under one campaign so every channel stays aligned.</p></div><button className="os-btn primary" onClick={openNew}><Plus/>New Campaign</button></header>
    {error&&<div className="os-connection-strip"><Target/><span>{error}</span></div>}
    <section className="os-card campaign-pulse"><div className="os-card-header"><div><h2>7-Day Content Pulse</h2><p>Recent and upcoming campaign activity.</p></div><span className="os-badge green">{rows.length} CAMPAIGN{rows.length===1?"":"S"}</span></div><div className="os-card-body"><div className="campaign-week-grid">{week.map(day=><article key={day.key} className={day.items.length?"has-items":""}><strong>{day.date.toLocaleDateString(undefined,{weekday:"short"})}</strong><span>{day.date.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span>{day.items.length?day.items.slice(0,2).map(item=><button key={item.id} onClick={()=>openEdit(item)}>{item.name}</button>):<small>Available slot</small>}</article>)}</div></div></section>
    <section className="os-card"><div className="os-card-header"><div><h2>Campaign Registry</h2><p>Topic → buyer → CTA → content → approval.</p></div></div><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Campaign</th><th>Type</th><th>Market</th><th>Buyer</th><th>Channels</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><br/><small>{row.objective||"—"}</small></td><td>{pretty(row.campaign_type)}</td><td>{listValue(row.target_countries)||"Global"}</td><td>{row.target_audience||"—"}</td><td>{listValue(row.channels)||"—"}</td><td>{row.scheduled_at?new Date(row.scheduled_at).toLocaleString():"—"}</td><td><span className={`os-badge ${["approved","active","completed"].includes(String(row.status))?"green":String(row.status)==="review"?"amber":"blue"}`}>{pretty(row.status)}</span></td><td><div className="os-table-actions"><button onClick={()=>openEdit(row)}><Edit3/></button><button onClick={()=>void remove(row)}><Trash2/></button></div></td></tr>)}</tbody></table></div>{!loading&&!rows.length&&<div className="os-empty"><CalendarDays/><h3>No campaign records yet</h3><p>Create the first campaign to populate the 7-day calendar.</p></div>}</section>
    {modal&&<div className="os-modal-backdrop" onMouseDown={()=>setModal(false)}><section className="os-modal" onMouseDown={event=>event.stopPropagation()}><div className="os-modal-header"><div><h2>{editing?"Edit Campaign":"New Campaign"}</h2><p className="os-page-subtitle">Keep the same commercial topic consistent across content and channels.</p></div><button className="os-icon-button" onClick={()=>setModal(false)}><X/></button></div><div className="os-modal-body"><div className="os-form-grid"><label className="os-label full"><span>Campaign Name</span><input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label className="os-label"><span>Type</span><select value={form.campaign_type} onChange={e=>setForm(v=>({...v,campaign_type:e.target.value}))}>{types.map(v=><option key={v}>{v}</option>)}</select></label><label className="os-label"><span>Status</span><select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}>{statuses.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label><label className="os-label full"><span>Objective</span><textarea value={form.objective} onChange={e=>setForm(v=>({...v,objective:e.target.value}))}/></label><label className="os-label"><span>Target Countries</span><input value={form.target_countries} onChange={e=>setForm(v=>({...v,target_countries:e.target.value}))} placeholder="USA, UK, UAE"/></label><label className="os-label"><span>Buyer</span><input value={form.target_audience} onChange={e=>setForm(v=>({...v,target_audience:e.target.value}))}/></label><label className="os-label"><span>Channels</span><input value={form.channels} onChange={e=>setForm(v=>({...v,channels:e.target.value}))} placeholder="Blog, LinkedIn, Instagram"/></label><label className="os-label"><span>Schedule</span><input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm(v=>({...v,scheduled_at:e.target.value}))}/></label><label className="os-label full"><span>Subject / Headline</span><input value={form.subject} onChange={e=>setForm(v=>({...v,subject:e.target.value}))}/></label><label className="os-label full"><span>Campaign Content</span><textarea rows={7} value={form.content} onChange={e=>setForm(v=>({...v,content:e.target.value}))}/></label><label className="os-label full"><span>Landing Page / CTA URL</span><input value={form.landing_page} onChange={e=>setForm(v=>({...v,landing_page:e.target.value}))}/></label></div></div><div className="os-modal-footer"><button className="os-btn soft" onClick={()=>setModal(false)}>Cancel</button><button className="os-btn primary" onClick={()=>void save()}><Save/>{editing?"Save Changes":"Create Campaign"}</button></div></section></div>}
    {toast&&<div className="os-toast-stack"><div className="os-toast"><CheckCircle2/><strong>{toast}</strong></div></div>}
  </div></AdminShell>
}
