"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { adminFetch } from "@/lib/admin-client";
import { supabase } from "@/lib/supabase-client";
import { CheckCircle2, MailPlus, RefreshCw, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";

type UserRow={id:string;email:string;fullName:string;role:string;enabled:boolean;createdAt?:string;lastSignInAt?:string|null};
type ResetRequest={id:string;title:string;description?:string;metadata?:{email?:string;status?:string};created_at:string};
const roleDescriptions:Record<string,string>={super_admin:"Full system access",admin:"Full administrative operations",executive:"Dashboard, reports and approvals",sales:"Leads, contacts, quotations and commercial sheet",marketing:"Content, blog, social, newsletter, SEO/GEO",operations:"Production, shipments and documents",website_editor:"Pages, text, images and visual editor",viewer:"Read-only operational visibility"};
export default function AccessRolesPage(){const[users,setUsers]=useState<UserRow[]>([]),[resetRequests,setResetRequests]=useState<ResetRequest[]>([]),[email,setEmail]=useState(""),[fullName,setFullName]=useState(""),[role,setRole]=useState("viewer"),[loading,setLoading]=useState(true),[working,setWorking]=useState(""),[error,setError]=useState(""),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [response,resetResult]=await Promise.all([adminFetch("/api/admin/users"),supabase.from("b2b_activities").select("id,title,description,metadata,created_at").eq("module","Authentication").eq("activity_type","password_reset_request").order("created_at",{ascending:false}).limit(100)]);const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load users.");setUsers(payload.users||[]);if(!resetResult.error)setResetRequests((resetResult.data||[]) as ResetRequest[])}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load users.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
 async function invite(){if(!email.includes("@")){setError("Enter a valid email.");return}setWorking("invite");setError("");try{const response=await adminFetch("/api/admin/users",{method:"POST",body:JSON.stringify({email,fullName,role})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Invite failed.");setEmail("");setFullName("");await load();setToast("Staff invitation sent.")}catch(reason){setError(reason instanceof Error?reason.message:"Invite failed.")}finally{setWorking("")}}
 async function updateUser(user:UserRow,patch:Partial<UserRow>){setWorking(user.id);setError("");try{const response=await adminFetch("/api/admin/users",{method:"PATCH",body:JSON.stringify({id:user.id,role:patch.role??user.role,fullName:patch.fullName??user.fullName,enabled:patch.enabled??user.enabled})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Update failed.");await load();setToast("Staff access updated.")}catch(reason){setError(reason instanceof Error?reason.message:"Update failed.")}finally{setWorking("")}}
 async function approveReset(request:ResetRequest){const resetEmail=String(request.metadata?.email||"");if(!resetEmail)return;setWorking(request.id);setError("");try{const response=await adminFetch("/api/admin/password-reset-approve",{method:"POST",body:JSON.stringify({activityId:request.id,email:resetEmail})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Approval failed.");await load();setToast("Password recovery email approved and requested.")}catch(reason){setError(reason instanceof Error?reason.message:"Approval failed.")}finally{setWorking("")}}
 const roles=useMemo(()=>["super_admin","admin","executive","sales","marketing","operations","website_editor","viewer"],[]);
 return <AdminShell><div className="os-page access-roles-v2"><header className="os-page-header"><div><div className="os-page-eyebrow">Security & Governance</div><h1 className="os-page-title">Access & Roles</h1><p className="os-page-subtitle">Give every staff member a separate CMS account, assign only the modules they need and keep accountability through Activity Logs.</p></div><button className="os-btn soft" onClick={()=>void load()}><RefreshCw/>Refresh</button></header>{error&&<section className="os-card content-alert"><strong>Access management needs attention</strong><p>{error}</p></section>}
 <div className="access-roles-layout"><section className="os-card"><div className="os-card-header"><div><h2>Role Architecture</h2><p>Recommended enterprise access model.</p></div><span className="os-badge green">LEAST PRIVILEGE</span></div><div className="os-card-body role-architecture-list">{roles.map(r=><article key={r}><span className="os-list-icon"><UsersRound/></span><div><strong>{r.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}</strong><p>{roleDescriptions[r]}</p></div><ShieldCheck/></article>)}</div></section>
 <section className="os-card"><div className="os-card-header"><div><h2>Invite Staff Member</h2><p>An email invitation creates an authenticated CMS account.</p></div><MailPlus/></div><div className="os-card-body"><div className="os-form-grid"><label className="os-label"><span>Full Name</span><input value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label className="os-label"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="os-label full"><span>Role</span><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label></div><button className="os-btn primary" style={{marginTop:14}} onClick={()=>void invite()} disabled={working==="invite"}><MailPlus/>{working==="invite"?"Sending…":"Invite Staff Member"}</button></div></section></div>
 <section className="os-card"><div className="os-card-header"><div><h2>Staff Access</h2><p>Authorized CMS users and their current role.</p></div><span className="os-badge pink">{users.length} ACCOUNTS</span></div><div className="os-card-body"><div className="os-table-wrap"><table className="os-table"><thead><tr><th>Staff Member</th><th>Role</th><th>Status</th><th>Last Sign In</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.fullName}</strong><small>{user.email}</small></td><td><select value={user.role} onChange={e=>void updateUser(user,{role:e.target.value})} disabled={working===user.id}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></td><td><span className={`os-badge ${user.enabled?"green":"amber"}`}>{user.enabled?"Active":"Disabled"}</span></td><td>{user.lastSignInAt?new Date(user.lastSignInAt).toLocaleString():"Never"}</td><td><button className={`os-btn ${user.enabled?"danger":"primary"}`} onClick={()=>void updateUser(user,{enabled:!user.enabled})} disabled={working===user.id}><UserRoundCheck/>{user.enabled?"Disable":"Enable"}</button></td></tr>)}{!users.length&&!loading&&<tr><td colSpan={5}>No staff accounts found.</td></tr>}</tbody></table></div></div></section>
 <section className="os-card"><div className="os-card-header"><div><h2>Password Reset Requests</h2><p>Approve a request before the recovery email is released to the staff member.</p></div><span className="os-badge amber">{resetRequests.filter(item=>item.metadata?.status!=="approved").length} PENDING</span></div><div className="os-card-body"><div className="role-architecture-list">{resetRequests.map(item=><article key={item.id}><span className="os-list-icon"><MailPlus/></span><div><strong>{item.metadata?.email||item.title}</strong><p>{item.metadata?.status==="approved"?"Approved — recovery email requested":`Requested ${new Date(item.created_at).toLocaleString()}`}</p></div>{item.metadata?.status==="approved"?<span className="os-badge green">Approved</span>:<button className="os-btn primary" onClick={()=>void approveReset(item)} disabled={working===item.id}>Approve Reset</button>}</article>)}{!resetRequests.length&&!loading&&<div className="os-empty"><ShieldCheck/><h3>No password reset requests</h3><p>New requests from the login page will appear here.</p></div>}</div></div></section>
 {toast&&<div className="os-toast-stack"><div className="os-toast"><CheckCircle2/><div><strong>{toast}</strong></div></div></div>}</div></AdminShell>}
