import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { parseJsonResponse, runOpenAI } from "@/lib/openai-server";
import { publicApiError } from "@/lib/api-errors";
import { requireAdminUser } from "@/lib/admin-auth";
import { SOCIAL_PLATFORM_KEYS, SOCIAL_PLATFORM_META, clampPlatformText, type SocialPlatformKey } from "@/lib/social-platforms";

const platformKeys = [...SOCIAL_PLATFORM_KEYS];
const platformRules = platformKeys.map((key) => { const meta = SOCIAL_PLATFORM_META[key]; return `${meta.label}: maximum ${meta.maxChars} characters; target about ${meta.recommendedChars}; image ${meta.dimensions} (${meta.aspect})`; }).join("\n");
export async function GET(request: Request) { return create(request, true); }
export async function POST(request: Request) { return create(request, false); }
async function create(request: Request, cron: boolean) {
  try {
    if (cron) {
      if (process.env.CRON_SECRET && request.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    } else await requireAdminUser(request);
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) return NextResponse.json({ error: "Supabase server configuration missing." }, { status: 500 });
    const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
    const start = new Date(); start.setUTCHours(0,0,0,0); const end = new Date(start); end.setUTCDate(end.getUTCDate()+1);
    const { data: existing } = await supabase.from("social_scheduled_posts").select("id,brief").gte("created_at", start.toISOString()).lt("created_at", end.toISOString()).eq("status","draft").contains("brief", { autoGenerated: true }).limit(1).maybeSingle();
    if (existing) return NextResponse.json({ skipped: true, reason: "Today's social campaign draft already exists." });
    const { data: todayBlog } = await supabase.from("blog_posts").select("id,title,excerpt,primary_keyword,keywords,category").gte("created_at", start.toISOString()).lt("created_at", end.toISOString()).eq("content_type", "blog").in("status", ["draft","review","approved","scheduled","published"]).order("created_at", { ascending: false }).limit(1).maybeSingle();
    const dayNumber = Math.floor(Date.now() / 86400000);
    const strategy = todayBlog
      ? "campaign-reuse: adapt today's researched website blog into platform-native social content using the exact same core topic"
      : dayNumber % 3 === 0
        ? "buyer-help: answer a timely importer, distributor, food-manufacturer or private-label buyer question"
        : dayNumber % 3 === 1
          ? "product-education: explain one real packaging, grain-size, sourcing, documentation or application topic"
          : "commercial-awareness: promote The Salt Origin's bulk supply or private-label capability without inventing price, MOQ, capacity, certification or client claims";
    const blogContext = todayBlog ? `Today's approved research direction already exists as a website blog. Use this exact topic for every social platform; do not choose a different topic.\nBlog title: ${String(todayBlog.title || "")}\nBlog excerpt: ${String(todayBlog.excerpt || "")}\nPrimary keyword: ${String(todayBlog.primary_keyword || "")}\nCategory: ${String(todayBlog.category || "")}` : "No website blog exists yet today, so research and choose one useful topic.";
    const { text, model } = await runOpenAI({
      model: process.env.OPENAI_MODEL,
      timeoutMs: 55_000,
      tools: todayBlog ? undefined : [{ type: "web_search", search_context_size: "medium" }],
      input: `Create today's human-review social campaign for The Salt Origin, a B2B Himalayan pink salt exporter and private-label supplier.
Daily strategy: ${strategy}.
${blogContext}
Research current public buyer interests only as needed for factual framing. If today's blog context is present, preserve its topic and keyword direction. The SAME topic and SAME campaign image will be used everywhere, but write platform-native copy for every platform. Avoid medical claims and never invent prices, MOQ, certifications, statistics, capacity, clients or laboratory results.
Return valid JSON only with: topic, campaign_type, primary_keyword, keywords (array), image_prompt, platforms object containing linkedin, instagram, facebook, pinterest, threads, x, tiktok, youtube, reddit, whatsapp, telegram, discord, snapchat, mastodon and bluesky. Each platform object must contain title, text, hashtags (string), image_prompt.
LinkedIn: professional B2B explanation and CTA.
Instagram: engaging caption and focused hashtags.
Facebook: conversational business post.
Pinterest: searchable pin title and descriptive copy.
Threads: concise conversational post.
X: under 280 characters.
TikTok: short caption plus video concept in title.
YouTube: title, description and thumbnail concept.
Reddit: community-first title and helpful post body, avoiding promotional spam.
WhatsApp: concise broadcast copy with a clear enquiry CTA.
Telegram: concise channel post with a practical buyer takeaway.
Discord: community update with one discussion prompt.
Snapchat: short overlay concept and vertical story caption.
Mastodon: concise professional post with restrained hashtags.
Bluesky: concise conversational business post.
Keep every item in Draft status for human approval.
Respect these platform limits and recommended lengths exactly:
${platformRules}`
    });
    const result = parseJsonResponse(text); const platforms = result.platforms && typeof result.platforms === "object" ? result.platforms : {};
    const imagePrompt = String(result.image_prompt || platforms.linkedin?.image_prompt || result.topic || "Himalayan pink salt export packaging");
    let imageUrl = "";
    if (process.env.OPENAI_API_KEY && process.env.OPENAI_IMAGE_AUTOGENERATE === "true") {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 90_000);
      try {
        const imageResponse = await fetch("https://api.openai.com/v1/images/generations", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.OPENAI_IMAGE_MODEL || "gpt-image-1", prompt: `${imagePrompt}. Premium commercial editorial image for The Salt Origin, no invented text, no third-party logo, adaptable crop for all social platforms.`, size: "1024x1024" }), signal: controller.signal });
        const payload = await imageResponse.json().catch(() => ({})); const b64 = payload?.data?.[0]?.b64_json;
        if (imageResponse.ok && b64) {
          const bytes = Uint8Array.from(Buffer.from(b64,"base64"));
          const path = `social/auto-${new Date().toISOString().slice(0,10)}.png`;
          const { error } = await supabase.storage.from("cms-media").upload(path, bytes, { contentType: "image/png", upsert: true });
          if (!error) imageUrl = supabase.storage.from("cms-media").getPublicUrl(path).data.publicUrl;
        }
      } catch {
        // Keep the researched social draft usable; the image can be generated or uploaded during review.
      } finally {
        clearTimeout(timeout);
      }
    }
    const platformContent = Object.fromEntries(platformKeys.map((key) => {
      const item = platforms[key] || {};
      const platform = key as SocialPlatformKey;
      const hashtags = Array.isArray(item.hashtags) ? item.hashtags.join(" ") : String(item.hashtags || "");
      const rawText = [String(item.text || "").trim(), hashtags.trim()].filter(Boolean).join(hashtags ? "\n\n" : "");
      const clamped = clampPlatformText(platform, rawText);
      return [key, {
        title: String(item.title || result.topic || ""),
        text: clamped,
        hashtags: clamped.includes(hashtags.trim()) ? hashtags : "",
        imagePrompt: String(item.image_prompt || imagePrompt),
        status: "Draft",
        maxChars: SOCIAL_PLATFORM_META[platform].maxChars,
        recommendedChars: SOCIAL_PLATFORM_META[platform].recommendedChars,
      }];
    }));
    const platformImages = Object.fromEntries(platformKeys.map(key => [key, imageUrl]));
    const scheduled = new Date(); scheduled.setUTCHours(9,0,0,0); if (scheduled.getTime() < Date.now()) scheduled.setUTCDate(scheduled.getUTCDate()+1);
    const linkedin = platformContent.linkedin as any;
    const { data, error } = await supabase.from("social_scheduled_posts").insert({ title: String(result.topic || linkedin.title || "Daily social campaign"), caption: String(linkedin.text || ""), hashtags: String(linkedin.hashtags || ""), keywords: Array.isArray(result.keywords) ? result.keywords.join(", ") : String(result.primary_keyword || ""), image_url: imageUrl, platforms: platformKeys, platform_content: platformContent, platform_images: platformImages, scheduled_at: scheduled.toISOString(), status: "draft", approval_status: "Draft", brief: { strategy, campaignType: String(result.campaign_type || "daily campaign"), primaryKeyword: String(result.primary_keyword || todayBlog?.primary_keyword || ""), autoGenerated: true, linkedBlogId: todayBlog?.id || null, linkedBlogTitle: todayBlog?.title || null } }).select("*").single();
    if (error) throw new Error(error.message);
    return NextResponse.json({ success: true, draft: data, model, image_generated: Boolean(imageUrl) });
  } catch (error) { if (error instanceof Response) return error; return NextResponse.json({ error: publicApiError(error,"Social draft generation failed.") }, { status: 500 }); }
}
