"use client";
import { useEffect,useMemo,useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { MailPlus,ShieldCheck,Trash2,UserPlus } from "lucide-react";

type Role={id:string;name:string;description:string;permissions:Record<string,boolean>};
type Profile={id:string;full_name:string;role_name:string;enabled:boolean;email?:string};
const permissionKeys=["dashboard","content","products","categories","blogs","media","documents","inquiries","seo","languages","social","users","settings"];
export default function WorkflowPage(){
 const[roles,setRoles]=useState<Role[]>([]),[profiles,setProfiles]=useState<Profile[]>([]);const[email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState("content_writer"),[roleName,setRoleName]=useState(""),[description,setDescription]=useState(""),[permissions,setPermissions]=useState<Record<string,boolean>>({dashboard:true});
 useEffect(()=>{void load()},[]);async function load(){const[{data:r},{data:p}]=await Promise.all([supabase.from("cms_roles").select("*").order("name"),supabase.from("cms_profiles").select("*").order("created_at",{ascending:false})]);setRoles((r as Role[])||[]);setProfiles((p as Profile[])||[])}
 async function invite(){const r=await fetch('/api/admin/users/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,full_name:name,role_name:role})});const j=await r.json();if(!r.ok)return alert(j.error||'Invite failed');setEmail('');setName('');await load();alert('Invitation sent.');}
 async function updateUser(p:Profile,patch:Partial<Profile>){const next={...p,...patch};const r=await fetch('/api/admin/users/role',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,role_name:next.role_name,enabled:next.enabled})});const j=await r.json();if(!r.ok)return alert(j.error);setProfiles(x=>x.map(v=>v.id===p.id?next:v));}
 async function createRole(){const r=await fetch('/api/admin/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:roleName,description,permissions})});const j=await r.json();if(!r.ok)return alert(j.error);setRoleName('');setDescription('');setPermissions({dashboard:true});await load();}
 async function deleteRole(id:string){if(!confirm('Delete this custom role?'))return;const r=await fetch('/api/admin/roles',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return alert(j.error);await load();}
 async function removeUser(id:string){if(!confirm('Remove this CMS user permanently?'))return;const r=await fetch('/api/admin/users/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)return alert(j.error);await load();}
 const builtins=useMemo(()=>new Set(['admin','editor','content_writer','sales','viewer']),[]);
 return <AdminShell><div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[4px] text-[#C23B4A]">Security & Workflow</p><h1 className="mt-2 text-4xl font-black">Users, Roles & Access</h1><p className="mt-2 text-slate-500">Create custom roles, assign exact access and remove users whenever needed.</p></div>
 <div className="grid gap-5 xl:grid-cols-2"><section className="cms-panel rounded-3xl border p-6"><div className="flex items-center gap-3"><MailPlus className="text-[#C23B4A]"/><h2 className="text-xl font-black">Invite CMS User</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="rounded-xl border p-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="rounded-xl border p-3"/><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border p-3">{roles.map(r=><option key={r.id} value={r.name}>{r.name.replaceAll('_',' ')}</option>)}</select><button onClick={invite} className="rounded-xl bg-[#C23B4A] p-3 font-black text-white"><UserPlus className="mr-2 inline h-4 w-4"/>Send Invitation</button></div></section>
 <section className="cms-panel rounded-3xl border p-6"><div className="flex items-center gap-3"><ShieldCheck className="text-[#C23B4A]"/><h2 className="text-xl font-black">Create Custom Role</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={roleName} onChange={e=>setRoleName(e.target.value)} placeholder="Role name" className="rounded-xl border p-3"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="rounded-xl border p-3"/></div><div className="mt-4 flex flex-wrap gap-2">{permissionKeys.map(k=><label key={k} className="inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs font-bold"><input type="checkbox" checked={!!permissions[k]} onChange={e=>setPermissions(p=>({...p,[k]:e.target.checked}))}/>{k}</label>)}</div><button onClick={createRole} className="mt-4 rounded-xl bg-blue-600 px-5 py-3 font-black text-white">Create Role</button></section></div>
 <section className="cms-panel overflow-hidden rounded-3xl border"><div className="border-b p-5"><h2 className="text-xl font-black">CMS Users</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="cms-table-head"><tr><th className="p-4 text-left">User</th><th className="p-4 text-left">Role</th><th className="p-4 text-left">Access</th><th className="p-4 text-left">Status</th><th className="p-4">Remove</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id} className="border-t cms-row"><td className="p-4"><b>{p.full_name||'CMS User'}</b><span className="block text-xs text-slate-500">{p.email||p.id}</span></td><td className="p-4"><select value={p.role_name} onChange={e=>updateUser(p,{role_name:e.target.value})} className="rounded-xl border p-2">{roles.map(r=><option key={r.id} value={r.name}>{r.name.replaceAll('_',' ')}</option>)}</select></td><td className="p-4"><div className="flex flex-wrap gap-1">{Object.entries(roles.find(r=>r.name===p.role_name)?.permissions||{}).filter(([,v])=>v).map(([k])=><span key={k} className="rounded-full bg-blue-500/10 px-2 py-1 text-xs text-blue-500">{k}</span>)}</div></td><td className="p-4"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={p.enabled} onChange={e=>updateUser(p,{enabled:e.target.checked})}/>{p.enabled?'Active':'Disabled'}</label></td><td className="p-4 text-center"><button onClick={()=>removeUser(p.id)} className="rounded-lg bg-red-600 p-2 text-white"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></section>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roles.map(r=><article key={r.id} className="cms-panel rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black capitalize">{r.name.replaceAll('_',' ')}</h3><p className="mt-1 text-xs text-slate-500">{r.description}</p></div>{!builtins.has(r.name)&&<button onClick={()=>deleteRole(r.id)} className="text-red-500"><Trash2 className="h-4 w-4"/></button>}</div></article>)}</div></div></AdminShell>
}
