"use client";
import { useEffect, useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { supabase } from "@/lib/supabase-client";
import { MailPlus, ShieldCheck, UserCheck, Users } from "lucide-react";

type Role={id:string;name:string;description:string;permissions:Record<string,boolean>};
type Profile={id:string;full_name:string;role_name:string;enabled:boolean;email?:string};
export default function WorkflowPage(){
 const[roles,setRoles]=useState<Role[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[email,setEmail]=useState("");const[name,setName]=useState("");const[role,setRole]=useState("content_writer");const[inviting,setInviting]=useState(false);
 useEffect(()=>{void load()},[]);
 async function load(){const[{data:r},{data:p}]=await Promise.all([supabase.from("cms_roles").select("*").order("name"),supabase.from("cms_profiles").select("*").order("created_at",{ascending:false})]);setRoles((r as Role[])||[]);setProfiles((p as Profile[])||[])}
 async function invite(){if(!email)return alert("Enter an email address.");setInviting(true);const response=await fetch("/api/admin/users/invite",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,full_name:name,role_name:role})});const result=await response.json();setInviting(false);if(!response.ok)return alert(result.error||"Invite failed");setEmail("");setName("");alert("Invitation sent. The user can set a password and log in.");await load()}
 async function updateUser(profile:Profile,patch:Partial<Profile>){const next={...profile,...patch};const response=await fetch("/api/admin/users/role",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:profile.id,role_name:next.role_name,enabled:next.enabled})});const result=await response.json();if(!response.ok)return alert(result.error);setProfiles(p=>p.map(x=>x.id===profile.id?next:x))}
 return <AdminShell><div className="space-y-6"><div><p className="uppercase tracking-[4px] text-blue-400 font-black text-xs">Security & Workflow</p><h1 className="text-4xl font-black mt-2">Users, Roles & Approval Rules</h1><p className="text-slate-500 mt-2">Invite staff, assign access and control the publishing workflow.</p></div>
 <section className="cms-panel border rounded-2xl p-5"><div className="flex items-center gap-3"><MailPlus className="text-blue-500"/><h2 className="text-xl font-black">Invite CMS User</h2></div><div className="grid md:grid-cols-4 gap-3 mt-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="border rounded-xl p-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="border rounded-xl p-3"/><select value={role} onChange={e=>setRole(e.target.value)} className="border rounded-xl p-3">{roles.map(r=><option key={r.id} value={r.name}>{r.name.replaceAll("_"," ")}</option>)}</select><button onClick={invite} disabled={inviting} className="bg-blue-600 text-white rounded-xl font-black">{inviting?"Sending...":"Send Invitation"}</button></div><p className="text-xs text-slate-500 mt-3">Requires SUPABASE_SERVICE_ROLE_KEY and NEXT_PUBLIC_SITE_URL on Vercel.</p></section>
 <section className="cms-panel border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="text-xl font-black">CMS Users</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="cms-table-head"><th className="text-left p-4">User</th><th className="text-left p-4">Role</th><th className="text-left p-4">Access</th><th className="text-left p-4">Status</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id} className="border-t"><td className="p-4"><b>{p.full_name||"CMS User"}</b><span className="block text-xs text-slate-500">{p.id}</span></td><td className="p-4"><select value={p.role_name} onChange={e=>updateUser(p,{role_name:e.target.value})} className="border rounded-xl p-2">{roles.map(r=><option key={r.id} value={r.name}>{r.name.replaceAll("_"," ")}</option>)}</select></td><td className="p-4"><div className="flex flex-wrap gap-2">{Object.entries(roles.find(r=>r.name===p.role_name)?.permissions||{}).filter(([,v])=>v).map(([k])=><span key={k} className="rounded-full border px-3 py-1 text-xs text-blue-500 bg-blue-500/10">{k}</span>)}</div></td><td className="p-4"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={p.enabled} onChange={e=>updateUser(p,{enabled:e.target.checked})}/>{p.enabled?"Active":"Disabled"}</label></td></tr>)}{!profiles.length&&<tr><td colSpan={4} className="p-10 text-center text-slate-500">No profiles yet. Invite your first user.</td></tr>}</tbody></table></div></section>
 <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{roles.map(role=><article key={role.id} className="cms-panel rounded-2xl border p-5"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-violet-600/15 flex items-center justify-center"><ShieldCheck className="h-5 w-5 text-violet-500"/></div><div><h2 className="font-black capitalize">{role.name.replaceAll("_"," ")}</h2><p className="text-xs text-slate-500">{role.description}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(role.permissions||{}).filter(([,v])=>v).map(([k])=><span key={k} className="rounded-full bg-blue-600/10 border border-blue-500/20 px-3 py-1 text-xs text-blue-500">{k}</span>)}</div></article>)}</div>
 <div className="cms-panel rounded-2xl border p-5"><div className="flex items-center gap-3"><Users className="text-blue-500"/><h2 className="font-black">Recommended workflow</h2></div><div className="mt-4 grid md:grid-cols-4 gap-3 text-sm">{[["1. Draft","Writer creates content."],["2. Review","Editor verifies accuracy and SEO."],["3. Approve","Admin approves the final version."],["4. Publish","Content becomes visible online."]].map(([h,p])=><div key={h} className="cms-muted rounded-xl p-4"><b>{h}</b><p className="text-slate-500 mt-1">{p}</p></div>)}</div></div>
 </div></AdminShell>}
